/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingCategoryData } from './AccountingCategoryData';
import {
    AccountingCategoryDataFromJSON,
    AccountingCategoryDataFromJSONTyped,
    AccountingCategoryDataToJSON,
    AccountingCategoryDataToJSONTyped,
} from './AccountingCategoryData';

/**
 * 
 * @export
 * @interface AccountingCategoryResponse
 */
export interface AccountingCategoryResponse {
    /**
     * 
     * @type {AccountingCategoryData}
     * @memberof AccountingCategoryResponse
     */
    data?: AccountingCategoryData;
}

/**
 * Check if a given object implements the AccountingCategoryResponse interface.
 */
export function instanceOfAccountingCategoryResponse(value: object): value is AccountingCategoryResponse {
    return true;
}

export function AccountingCategoryResponseFromJSON(json: any): AccountingCategoryResponse {
    return AccountingCategoryResponseFromJSONTyped(json, false);
}

export function AccountingCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AccountingCategoryDataFromJSON(json['data']),
    };
}

export function AccountingCategoryResponseToJSON(json: any): AccountingCategoryResponse {
    return AccountingCategoryResponseToJSONTyped(json, false);
}

export function AccountingCategoryResponseToJSONTyped(value?: AccountingCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AccountingCategoryDataToJSON(value['data']),
    };
}

