/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryData } from './AccountingSubcategoryData';
import {
    AccountingSubcategoryDataFromJSON,
    AccountingSubcategoryDataFromJSONTyped,
    AccountingSubcategoryDataToJSON,
    AccountingSubcategoryDataToJSONTyped,
} from './AccountingSubcategoryData';

/**
 * 
 * @export
 * @interface AccountingSubcategoryCollection
 */
export interface AccountingSubcategoryCollection {
    /**
     * 
     * @type {Array<AccountingSubcategoryData>}
     * @memberof AccountingSubcategoryCollection
     */
    data?: Array<AccountingSubcategoryData>;
}

/**
 * Check if a given object implements the AccountingSubcategoryCollection interface.
 */
export function instanceOfAccountingSubcategoryCollection(value: object): value is AccountingSubcategoryCollection {
    return true;
}

export function AccountingSubcategoryCollectionFromJSON(json: any): AccountingSubcategoryCollection {
    return AccountingSubcategoryCollectionFromJSONTyped(json, false);
}

export function AccountingSubcategoryCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AccountingSubcategoryDataFromJSON)),
    };
}

export function AccountingSubcategoryCollectionToJSON(json: any): AccountingSubcategoryCollection {
    return AccountingSubcategoryCollectionToJSONTyped(json, false);
}

export function AccountingSubcategoryCollectionToJSONTyped(value?: AccountingSubcategoryCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AccountingSubcategoryDataToJSON)),
    };
}

