/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryData } from './AccountingSubcategoryData';
import {
    AccountingSubcategoryDataFromJSON,
    AccountingSubcategoryDataFromJSONTyped,
    AccountingSubcategoryDataToJSON,
    AccountingSubcategoryDataToJSONTyped,
} from './AccountingSubcategoryData';

/**
 * 
 * @export
 * @interface AccountingSubcategoryResponse
 */
export interface AccountingSubcategoryResponse {
    /**
     * 
     * @type {AccountingSubcategoryData}
     * @memberof AccountingSubcategoryResponse
     */
    data?: AccountingSubcategoryData;
}

/**
 * Check if a given object implements the AccountingSubcategoryResponse interface.
 */
export function instanceOfAccountingSubcategoryResponse(value: object): value is AccountingSubcategoryResponse {
    return true;
}

export function AccountingSubcategoryResponseFromJSON(json: any): AccountingSubcategoryResponse {
    return AccountingSubcategoryResponseFromJSONTyped(json, false);
}

export function AccountingSubcategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AccountingSubcategoryDataFromJSON(json['data']),
    };
}

export function AccountingSubcategoryResponseToJSON(json: any): AccountingSubcategoryResponse {
    return AccountingSubcategoryResponseToJSONTyped(json, false);
}

export function AccountingSubcategoryResponseToJSONTyped(value?: AccountingSubcategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AccountingSubcategoryDataToJSON(value['data']),
    };
}

