/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountingCategoryAttributes
 */
export interface AccountingCategoryAttributes {
    /**
     * 
     * @type {string}
     * @memberof AccountingCategoryAttributes
     */
    readonly prefix?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountingCategoryAttributes
     */
    readonly name?: string;
    /**
     * 
     * @type {AccountingCategoryAttributesKindEnum}
     * @memberof AccountingCategoryAttributes
     */
    readonly kind?: AccountingCategoryAttributesKindEnum;
}


/**
 * @export
 */
export const AccountingCategoryAttributesKindEnum = {
    Income: 'income',
    Expenses: 'expenses',
    Assets: 'assets'
} as const;
export type AccountingCategoryAttributesKindEnum = typeof AccountingCategoryAttributesKindEnum[keyof typeof AccountingCategoryAttributesKindEnum];


/**
 * Check if a given object implements the AccountingCategoryAttributes interface.
 */
export function instanceOfAccountingCategoryAttributes(value: object): value is AccountingCategoryAttributes {
    return true;
}

export function AccountingCategoryAttributesFromJSON(json: any): AccountingCategoryAttributes {
    return AccountingCategoryAttributesFromJSONTyped(json, false);
}

export function AccountingCategoryAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingCategoryAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'name': json['name'] == null ? undefined : json['name'],
        'kind': json['kind'] == null ? undefined : json['kind'],
    };
}

export function AccountingCategoryAttributesToJSON(json: any): AccountingCategoryAttributes {
    return AccountingCategoryAttributesToJSONTyped(json, false);
}

export function AccountingCategoryAttributesToJSONTyped(value?: Omit<AccountingCategoryAttributes, 'prefix'|'name'|'kind'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

