/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryRelationships } from './AccountingSubcategoryRelationships';
import {
    AccountingSubcategoryRelationshipsFromJSON,
    AccountingSubcategoryRelationshipsFromJSONTyped,
    AccountingSubcategoryRelationshipsToJSON,
    AccountingSubcategoryRelationshipsToJSONTyped,
} from './AccountingSubcategoryRelationships';
import type { AccountingSubcategoryAttributes } from './AccountingSubcategoryAttributes';
import {
    AccountingSubcategoryAttributesFromJSON,
    AccountingSubcategoryAttributesFromJSONTyped,
    AccountingSubcategoryAttributesToJSON,
    AccountingSubcategoryAttributesToJSONTyped,
} from './AccountingSubcategoryAttributes';

/**
 * 
 * @export
 * @interface AccountingSubcategoryData
 */
export interface AccountingSubcategoryData {
    /**
     * 
     * @type {string}
     * @memberof AccountingSubcategoryData
     */
    id?: string;
    /**
     * 
     * @type {AccountingSubcategoryDataTypeEnum}
     * @memberof AccountingSubcategoryData
     */
    type?: AccountingSubcategoryDataTypeEnum;
    /**
     * 
     * @type {AccountingSubcategoryAttributes}
     * @memberof AccountingSubcategoryData
     */
    attributes?: AccountingSubcategoryAttributes;
    /**
     * 
     * @type {AccountingSubcategoryRelationships}
     * @memberof AccountingSubcategoryData
     */
    relationships?: AccountingSubcategoryRelationships;
}


/**
 * @export
 */
export const AccountingSubcategoryDataTypeEnum = {
    AccountingSubcategories: 'accounting_subcategories'
} as const;
export type AccountingSubcategoryDataTypeEnum = typeof AccountingSubcategoryDataTypeEnum[keyof typeof AccountingSubcategoryDataTypeEnum];


/**
 * Check if a given object implements the AccountingSubcategoryData interface.
 */
export function instanceOfAccountingSubcategoryData(value: object): value is AccountingSubcategoryData {
    return true;
}

export function AccountingSubcategoryDataFromJSON(json: any): AccountingSubcategoryData {
    return AccountingSubcategoryDataFromJSONTyped(json, false);
}

export function AccountingSubcategoryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : AccountingSubcategoryAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : AccountingSubcategoryRelationshipsFromJSON(json['relationships']),
    };
}

export function AccountingSubcategoryDataToJSON(json: any): AccountingSubcategoryData {
    return AccountingSubcategoryDataToJSONTyped(json, false);
}

export function AccountingSubcategoryDataToJSONTyped(value?: AccountingSubcategoryData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': AccountingSubcategoryAttributesToJSON(value['attributes']),
        'relationships': AccountingSubcategoryRelationshipsToJSON(value['relationships']),
    };
}

