/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryCreateData } from './AccountingSubcategoryCreateData';
import {
    AccountingSubcategoryCreateDataFromJSON,
    AccountingSubcategoryCreateDataFromJSONTyped,
    AccountingSubcategoryCreateDataToJSON,
    AccountingSubcategoryCreateDataToJSONTyped,
} from './AccountingSubcategoryCreateData';

/**
 * 
 * @export
 * @interface AccountingSubcategoryCreate
 */
export interface AccountingSubcategoryCreate {
    /**
     * 
     * @type {AccountingSubcategoryCreateData}
     * @memberof AccountingSubcategoryCreate
     */
    data: AccountingSubcategoryCreateData;
}

/**
 * Check if a given object implements the AccountingSubcategoryCreate interface.
 */
export function instanceOfAccountingSubcategoryCreate(value: object): value is AccountingSubcategoryCreate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AccountingSubcategoryCreateFromJSON(json: any): AccountingSubcategoryCreate {
    return AccountingSubcategoryCreateFromJSONTyped(json, false);
}

export function AccountingSubcategoryCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AccountingSubcategoryCreateDataFromJSON(json['data']),
    };
}

export function AccountingSubcategoryCreateToJSON(json: any): AccountingSubcategoryCreate {
    return AccountingSubcategoryCreateToJSONTyped(json, false);
}

export function AccountingSubcategoryCreateToJSONTyped(value?: AccountingSubcategoryCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AccountingSubcategoryCreateDataToJSON(value['data']),
    };
}

