/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryUpdateData } from './AccountingSubcategoryUpdateData';
import {
    AccountingSubcategoryUpdateDataFromJSON,
    AccountingSubcategoryUpdateDataFromJSONTyped,
    AccountingSubcategoryUpdateDataToJSON,
    AccountingSubcategoryUpdateDataToJSONTyped,
} from './AccountingSubcategoryUpdateData';

/**
 * 
 * @export
 * @interface AccountingSubcategoryUpdate
 */
export interface AccountingSubcategoryUpdate {
    /**
     * 
     * @type {AccountingSubcategoryUpdateData}
     * @memberof AccountingSubcategoryUpdate
     */
    data: AccountingSubcategoryUpdateData;
}

/**
 * Check if a given object implements the AccountingSubcategoryUpdate interface.
 */
export function instanceOfAccountingSubcategoryUpdate(value: object): value is AccountingSubcategoryUpdate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AccountingSubcategoryUpdateFromJSON(json: any): AccountingSubcategoryUpdate {
    return AccountingSubcategoryUpdateFromJSONTyped(json, false);
}

export function AccountingSubcategoryUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AccountingSubcategoryUpdateDataFromJSON(json['data']),
    };
}

export function AccountingSubcategoryUpdateToJSON(json: any): AccountingSubcategoryUpdate {
    return AccountingSubcategoryUpdateToJSONTyped(json, false);
}

export function AccountingSubcategoryUpdateToJSONTyped(value?: AccountingSubcategoryUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AccountingSubcategoryUpdateDataToJSON(value['data']),
    };
}

