/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryRelationshipsAccountingCategory } from './AccountingSubcategoryRelationshipsAccountingCategory';
import {
    AccountingSubcategoryRelationshipsAccountingCategoryFromJSON,
    AccountingSubcategoryRelationshipsAccountingCategoryFromJSONTyped,
    AccountingSubcategoryRelationshipsAccountingCategoryToJSON,
    AccountingSubcategoryRelationshipsAccountingCategoryToJSONTyped,
} from './AccountingSubcategoryRelationshipsAccountingCategory';

/**
 * 
 * @export
 * @interface AccountingSubcategoryRelationships
 */
export interface AccountingSubcategoryRelationships {
    /**
     * 
     * @type {AccountingSubcategoryRelationshipsAccountingCategory}
     * @memberof AccountingSubcategoryRelationships
     */
    accountingCategory?: AccountingSubcategoryRelationshipsAccountingCategory;
}

/**
 * Check if a given object implements the AccountingSubcategoryRelationships interface.
 */
export function instanceOfAccountingSubcategoryRelationships(value: object): value is AccountingSubcategoryRelationships {
    return true;
}

export function AccountingSubcategoryRelationshipsFromJSON(json: any): AccountingSubcategoryRelationships {
    return AccountingSubcategoryRelationshipsFromJSONTyped(json, false);
}

export function AccountingSubcategoryRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'accountingCategory': json['accounting_category'] == null ? undefined : AccountingSubcategoryRelationshipsAccountingCategoryFromJSON(json['accounting_category']),
    };
}

export function AccountingSubcategoryRelationshipsToJSON(json: any): AccountingSubcategoryRelationships {
    return AccountingSubcategoryRelationshipsToJSONTyped(json, false);
}

export function AccountingSubcategoryRelationshipsToJSONTyped(value?: AccountingSubcategoryRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounting_category': AccountingSubcategoryRelationshipsAccountingCategoryToJSON(value['accountingCategory']),
    };
}

