/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountingSubcategoryAttributes
 */
export interface AccountingSubcategoryAttributes {
    /**
     * 
     * @type {string}
     * @memberof AccountingSubcategoryAttributes
     */
    suffix?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountingSubcategoryAttributes
     */
    name?: string;
}

/**
 * Check if a given object implements the AccountingSubcategoryAttributes interface.
 */
export function instanceOfAccountingSubcategoryAttributes(value: object): value is AccountingSubcategoryAttributes {
    return true;
}

export function AccountingSubcategoryAttributesFromJSON(json: any): AccountingSubcategoryAttributes {
    return AccountingSubcategoryAttributesFromJSONTyped(json, false);
}

export function AccountingSubcategoryAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AccountingSubcategoryAttributesToJSON(json: any): AccountingSubcategoryAttributes {
    return AccountingSubcategoryAttributesToJSONTyped(json, false);
}

export function AccountingSubcategoryAttributesToJSONTyped(value?: AccountingSubcategoryAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suffix': value['suffix'],
        'name': value['name'],
    };
}

