/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingCategoryData } from './AccountingCategoryData';
import {
    AccountingCategoryDataFromJSON,
    AccountingCategoryDataFromJSONTyped,
    AccountingCategoryDataToJSON,
    AccountingCategoryDataToJSONTyped,
} from './AccountingCategoryData';

/**
 * 
 * @export
 * @interface AccountingCategoryCollection
 */
export interface AccountingCategoryCollection {
    /**
     * 
     * @type {Array<AccountingCategoryData>}
     * @memberof AccountingCategoryCollection
     */
    data?: Array<AccountingCategoryData>;
}

/**
 * Check if a given object implements the AccountingCategoryCollection interface.
 */
export function instanceOfAccountingCategoryCollection(value: object): value is AccountingCategoryCollection {
    return true;
}

export function AccountingCategoryCollectionFromJSON(json: any): AccountingCategoryCollection {
    return AccountingCategoryCollectionFromJSONTyped(json, false);
}

export function AccountingCategoryCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingCategoryCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AccountingCategoryDataFromJSON)),
    };
}

export function AccountingCategoryCollectionToJSON(json: any): AccountingCategoryCollection {
    return AccountingCategoryCollectionToJSONTyped(json, false);
}

export function AccountingCategoryCollectionToJSONTyped(value?: AccountingCategoryCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AccountingCategoryDataToJSON)),
    };
}

