/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryRelationshipsAccountingCategoryData } from './AccountingSubcategoryRelationshipsAccountingCategoryData';
import {
    AccountingSubcategoryRelationshipsAccountingCategoryDataFromJSON,
    AccountingSubcategoryRelationshipsAccountingCategoryDataFromJSONTyped,
    AccountingSubcategoryRelationshipsAccountingCategoryDataToJSON,
    AccountingSubcategoryRelationshipsAccountingCategoryDataToJSONTyped,
} from './AccountingSubcategoryRelationshipsAccountingCategoryData';

/**
 * 
 * @export
 * @interface AccountingSubcategoryRelationshipsAccountingCategory
 */
export interface AccountingSubcategoryRelationshipsAccountingCategory {
    /**
     * 
     * @type {AccountingSubcategoryRelationshipsAccountingCategoryData}
     * @memberof AccountingSubcategoryRelationshipsAccountingCategory
     */
    data?: AccountingSubcategoryRelationshipsAccountingCategoryData;
}

/**
 * Check if a given object implements the AccountingSubcategoryRelationshipsAccountingCategory interface.
 */
export function instanceOfAccountingSubcategoryRelationshipsAccountingCategory(value: object): value is AccountingSubcategoryRelationshipsAccountingCategory {
    return true;
}

export function AccountingSubcategoryRelationshipsAccountingCategoryFromJSON(json: any): AccountingSubcategoryRelationshipsAccountingCategory {
    return AccountingSubcategoryRelationshipsAccountingCategoryFromJSONTyped(json, false);
}

export function AccountingSubcategoryRelationshipsAccountingCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryRelationshipsAccountingCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AccountingSubcategoryRelationshipsAccountingCategoryDataFromJSON(json['data']),
    };
}

export function AccountingSubcategoryRelationshipsAccountingCategoryToJSON(json: any): AccountingSubcategoryRelationshipsAccountingCategory {
    return AccountingSubcategoryRelationshipsAccountingCategoryToJSONTyped(json, false);
}

export function AccountingSubcategoryRelationshipsAccountingCategoryToJSONTyped(value?: AccountingSubcategoryRelationshipsAccountingCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AccountingSubcategoryRelationshipsAccountingCategoryDataToJSON(value['data']),
    };
}

