/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingCategoryAttributes } from './AccountingCategoryAttributes';
import {
    AccountingCategoryAttributesFromJSON,
    AccountingCategoryAttributesFromJSONTyped,
    AccountingCategoryAttributesToJSON,
    AccountingCategoryAttributesToJSONTyped,
} from './AccountingCategoryAttributes';

/**
 * 
 * @export
 * @interface AccountingCategoryData
 */
export interface AccountingCategoryData {
    /**
     * 
     * @type {string}
     * @memberof AccountingCategoryData
     */
    id?: string;
    /**
     * 
     * @type {AccountingCategoryDataTypeEnum}
     * @memberof AccountingCategoryData
     */
    type?: AccountingCategoryDataTypeEnum;
    /**
     * 
     * @type {AccountingCategoryAttributes}
     * @memberof AccountingCategoryData
     */
    attributes?: AccountingCategoryAttributes;
}


/**
 * @export
 */
export const AccountingCategoryDataTypeEnum = {
    AccountingCategories: 'accounting_categories'
} as const;
export type AccountingCategoryDataTypeEnum = typeof AccountingCategoryDataTypeEnum[keyof typeof AccountingCategoryDataTypeEnum];


/**
 * Check if a given object implements the AccountingCategoryData interface.
 */
export function instanceOfAccountingCategoryData(value: object): value is AccountingCategoryData {
    return true;
}

export function AccountingCategoryDataFromJSON(json: any): AccountingCategoryData {
    return AccountingCategoryDataFromJSONTyped(json, false);
}

export function AccountingCategoryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingCategoryData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : AccountingCategoryAttributesFromJSON(json['attributes']),
    };
}

export function AccountingCategoryDataToJSON(json: any): AccountingCategoryData {
    return AccountingCategoryDataToJSONTyped(json, false);
}

export function AccountingCategoryDataToJSONTyped(value?: AccountingCategoryData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': AccountingCategoryAttributesToJSON(value['attributes']),
    };
}

