/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryRelationships } from './AccountingSubcategoryRelationships';
import {
    AccountingSubcategoryRelationshipsFromJSON,
    AccountingSubcategoryRelationshipsFromJSONTyped,
    AccountingSubcategoryRelationshipsToJSON,
    AccountingSubcategoryRelationshipsToJSONTyped,
} from './AccountingSubcategoryRelationships';
import type { AccountingSubcategoryAttributes } from './AccountingSubcategoryAttributes';
import {
    AccountingSubcategoryAttributesFromJSON,
    AccountingSubcategoryAttributesFromJSONTyped,
    AccountingSubcategoryAttributesToJSON,
    AccountingSubcategoryAttributesToJSONTyped,
} from './AccountingSubcategoryAttributes';

/**
 * 
 * @export
 * @interface AccountingSubcategoryCreateData
 */
export interface AccountingSubcategoryCreateData {
    /**
     * 
     * @type {AccountingSubcategoryCreateDataTypeEnum}
     * @memberof AccountingSubcategoryCreateData
     */
    type: AccountingSubcategoryCreateDataTypeEnum;
    /**
     * 
     * @type {AccountingSubcategoryAttributes}
     * @memberof AccountingSubcategoryCreateData
     */
    attributes: AccountingSubcategoryAttributes;
    /**
     * 
     * @type {AccountingSubcategoryRelationships}
     * @memberof AccountingSubcategoryCreateData
     */
    relationships: AccountingSubcategoryRelationships;
}


/**
 * @export
 */
export const AccountingSubcategoryCreateDataTypeEnum = {
    AccountingSubcategories: 'accounting_subcategories'
} as const;
export type AccountingSubcategoryCreateDataTypeEnum = typeof AccountingSubcategoryCreateDataTypeEnum[keyof typeof AccountingSubcategoryCreateDataTypeEnum];


/**
 * Check if a given object implements the AccountingSubcategoryCreateData interface.
 */
export function instanceOfAccountingSubcategoryCreateData(value: object): value is AccountingSubcategoryCreateData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function AccountingSubcategoryCreateDataFromJSON(json: any): AccountingSubcategoryCreateData {
    return AccountingSubcategoryCreateDataFromJSONTyped(json, false);
}

export function AccountingSubcategoryCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': AccountingSubcategoryAttributesFromJSON(json['attributes']),
        'relationships': AccountingSubcategoryRelationshipsFromJSON(json['relationships']),
    };
}

export function AccountingSubcategoryCreateDataToJSON(json: any): AccountingSubcategoryCreateData {
    return AccountingSubcategoryCreateDataToJSONTyped(json, false);
}

export function AccountingSubcategoryCreateDataToJSONTyped(value?: AccountingSubcategoryCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': AccountingSubcategoryAttributesToJSON(value['attributes']),
        'relationships': AccountingSubcategoryRelationshipsToJSON(value['relationships']),
    };
}

