/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountingSubcategoryAttributes } from './AccountingSubcategoryAttributes';
import {
    AccountingSubcategoryAttributesFromJSON,
    AccountingSubcategoryAttributesFromJSONTyped,
    AccountingSubcategoryAttributesToJSON,
    AccountingSubcategoryAttributesToJSONTyped,
} from './AccountingSubcategoryAttributes';

/**
 * 
 * @export
 * @interface AccountingSubcategoryUpdateData
 */
export interface AccountingSubcategoryUpdateData {
    /**
     * 
     * @type {AccountingSubcategoryUpdateDataTypeEnum}
     * @memberof AccountingSubcategoryUpdateData
     */
    type: AccountingSubcategoryUpdateDataTypeEnum;
    /**
     * 
     * @type {AccountingSubcategoryAttributes}
     * @memberof AccountingSubcategoryUpdateData
     */
    attributes: AccountingSubcategoryAttributes;
}


/**
 * @export
 */
export const AccountingSubcategoryUpdateDataTypeEnum = {
    AccountingSubcategories: 'accounting_subcategories'
} as const;
export type AccountingSubcategoryUpdateDataTypeEnum = typeof AccountingSubcategoryUpdateDataTypeEnum[keyof typeof AccountingSubcategoryUpdateDataTypeEnum];


/**
 * Check if a given object implements the AccountingSubcategoryUpdateData interface.
 */
export function instanceOfAccountingSubcategoryUpdateData(value: object): value is AccountingSubcategoryUpdateData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function AccountingSubcategoryUpdateDataFromJSON(json: any): AccountingSubcategoryUpdateData {
    return AccountingSubcategoryUpdateDataFromJSONTyped(json, false);
}

export function AccountingSubcategoryUpdateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingSubcategoryUpdateData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': AccountingSubcategoryAttributesFromJSON(json['attributes']),
    };
}

export function AccountingSubcategoryUpdateDataToJSON(json: any): AccountingSubcategoryUpdateData {
    return AccountingSubcategoryUpdateDataToJSONTyped(json, false);
}

export function AccountingSubcategoryUpdateDataToJSONTyped(value?: AccountingSubcategoryUpdateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': AccountingSubcategoryAttributesToJSON(value['attributes']),
    };
}

