/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachmentRelationshipsBookEntryData
 */
export interface AttachmentRelationshipsBookEntryData {
    /**
     * 
     * @type {string}
     * @memberof AttachmentRelationshipsBookEntryData
     */
    id?: string;
    /**
     * 
     * @type {AttachmentRelationshipsBookEntryDataTypeEnum}
     * @memberof AttachmentRelationshipsBookEntryData
     */
    type?: AttachmentRelationshipsBookEntryDataTypeEnum;
}


/**
 * @export
 */
export const AttachmentRelationshipsBookEntryDataTypeEnum = {
    Invoices: 'invoices',
    Tickets: 'tickets',
    Paysheets: 'paysheets'
} as const;
export type AttachmentRelationshipsBookEntryDataTypeEnum = typeof AttachmentRelationshipsBookEntryDataTypeEnum[keyof typeof AttachmentRelationshipsBookEntryDataTypeEnum];


/**
 * Check if a given object implements the AttachmentRelationshipsBookEntryData interface.
 */
export function instanceOfAttachmentRelationshipsBookEntryData(value: object): value is AttachmentRelationshipsBookEntryData {
    return true;
}

export function AttachmentRelationshipsBookEntryDataFromJSON(json: any): AttachmentRelationshipsBookEntryData {
    return AttachmentRelationshipsBookEntryDataFromJSONTyped(json, false);
}

export function AttachmentRelationshipsBookEntryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentRelationshipsBookEntryData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function AttachmentRelationshipsBookEntryDataToJSON(json: any): AttachmentRelationshipsBookEntryData {
    return AttachmentRelationshipsBookEntryDataToJSONTyped(json, false);
}

export function AttachmentRelationshipsBookEntryDataToJSONTyped(value?: AttachmentRelationshipsBookEntryData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

