/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentRelationshipsBookEntry } from './AttachmentRelationshipsBookEntry';
import {
    AttachmentRelationshipsBookEntryFromJSON,
    AttachmentRelationshipsBookEntryFromJSONTyped,
    AttachmentRelationshipsBookEntryToJSON,
    AttachmentRelationshipsBookEntryToJSONTyped,
} from './AttachmentRelationshipsBookEntry';

/**
 * 
 * @export
 * @interface AttachmentRelationships
 */
export interface AttachmentRelationships {
    /**
     * 
     * @type {AttachmentRelationshipsBookEntry}
     * @memberof AttachmentRelationships
     */
    bookEntry?: AttachmentRelationshipsBookEntry;
}

/**
 * Check if a given object implements the AttachmentRelationships interface.
 */
export function instanceOfAttachmentRelationships(value: object): value is AttachmentRelationships {
    return true;
}

export function AttachmentRelationshipsFromJSON(json: any): AttachmentRelationships {
    return AttachmentRelationshipsFromJSONTyped(json, false);
}

export function AttachmentRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'bookEntry': json['book_entry'] == null ? undefined : AttachmentRelationshipsBookEntryFromJSON(json['book_entry']),
    };
}

export function AttachmentRelationshipsToJSON(json: any): AttachmentRelationships {
    return AttachmentRelationshipsToJSONTyped(json, false);
}

export function AttachmentRelationshipsToJSONTyped(value?: AttachmentRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'book_entry': AttachmentRelationshipsBookEntryToJSON(value['bookEntry']),
    };
}

