/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentRelationshipsBookEntryData } from './AttachmentRelationshipsBookEntryData';
import {
    AttachmentRelationshipsBookEntryDataFromJSON,
    AttachmentRelationshipsBookEntryDataFromJSONTyped,
    AttachmentRelationshipsBookEntryDataToJSON,
    AttachmentRelationshipsBookEntryDataToJSONTyped,
} from './AttachmentRelationshipsBookEntryData';

/**
 * 
 * @export
 * @interface AttachmentRelationshipsBookEntry
 */
export interface AttachmentRelationshipsBookEntry {
    /**
     * 
     * @type {AttachmentRelationshipsBookEntryData}
     * @memberof AttachmentRelationshipsBookEntry
     */
    data?: AttachmentRelationshipsBookEntryData;
}

/**
 * Check if a given object implements the AttachmentRelationshipsBookEntry interface.
 */
export function instanceOfAttachmentRelationshipsBookEntry(value: object): value is AttachmentRelationshipsBookEntry {
    return true;
}

export function AttachmentRelationshipsBookEntryFromJSON(json: any): AttachmentRelationshipsBookEntry {
    return AttachmentRelationshipsBookEntryFromJSONTyped(json, false);
}

export function AttachmentRelationshipsBookEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentRelationshipsBookEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AttachmentRelationshipsBookEntryDataFromJSON(json['data']),
    };
}

export function AttachmentRelationshipsBookEntryToJSON(json: any): AttachmentRelationshipsBookEntry {
    return AttachmentRelationshipsBookEntryToJSONTyped(json, false);
}

export function AttachmentRelationshipsBookEntryToJSONTyped(value?: AttachmentRelationshipsBookEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AttachmentRelationshipsBookEntryDataToJSON(value['data']),
    };
}

