/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachmentAttributes
 */
export interface AttachmentAttributes {
    /**
     * 
     * @type {string}
     * @memberof AttachmentAttributes
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentAttributes
     */
    smallUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentAttributes
     */
    thumbnailUrl?: string;
}

/**
 * Check if a given object implements the AttachmentAttributes interface.
 */
export function instanceOfAttachmentAttributes(value: object): value is AttachmentAttributes {
    return true;
}

export function AttachmentAttributesFromJSON(json: any): AttachmentAttributes {
    return AttachmentAttributesFromJSONTyped(json, false);
}

export function AttachmentAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'smallUrl': json['small_url'] == null ? undefined : json['small_url'],
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
    };
}

export function AttachmentAttributesToJSON(json: any): AttachmentAttributes {
    return AttachmentAttributesToJSONTyped(json, false);
}

export function AttachmentAttributesToJSONTyped(value?: AttachmentAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'small_url': value['smallUrl'],
        'thumbnail_url': value['thumbnailUrl'],
    };
}

