/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentRelationships } from './AttachmentRelationships';
import {
    AttachmentRelationshipsFromJSON,
    AttachmentRelationshipsFromJSONTyped,
    AttachmentRelationshipsToJSON,
    AttachmentRelationshipsToJSONTyped,
} from './AttachmentRelationships';
import type { AttachmentAttributes } from './AttachmentAttributes';
import {
    AttachmentAttributesFromJSON,
    AttachmentAttributesFromJSONTyped,
    AttachmentAttributesToJSON,
    AttachmentAttributesToJSONTyped,
} from './AttachmentAttributes';

/**
 * 
 * @export
 * @interface AttachmentData
 */
export interface AttachmentData {
    /**
     * 
     * @type {string}
     * @memberof AttachmentData
     */
    id?: string;
    /**
     * 
     * @type {AttachmentDataTypeEnum}
     * @memberof AttachmentData
     */
    type?: AttachmentDataTypeEnum;
    /**
     * 
     * @type {AttachmentAttributes}
     * @memberof AttachmentData
     */
    attributes?: AttachmentAttributes;
    /**
     * 
     * @type {AttachmentRelationships}
     * @memberof AttachmentData
     */
    relationships?: AttachmentRelationships;
}


/**
 * @export
 */
export const AttachmentDataTypeEnum = {
    Attachments: 'attachments'
} as const;
export type AttachmentDataTypeEnum = typeof AttachmentDataTypeEnum[keyof typeof AttachmentDataTypeEnum];


/**
 * Check if a given object implements the AttachmentData interface.
 */
export function instanceOfAttachmentData(value: object): value is AttachmentData {
    return true;
}

export function AttachmentDataFromJSON(json: any): AttachmentData {
    return AttachmentDataFromJSONTyped(json, false);
}

export function AttachmentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : AttachmentAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : AttachmentRelationshipsFromJSON(json['relationships']),
    };
}

export function AttachmentDataToJSON(json: any): AttachmentData {
    return AttachmentDataToJSONTyped(json, false);
}

export function AttachmentDataToJSONTyped(value?: AttachmentData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': AttachmentAttributesToJSON(value['attributes']),
        'relationships': AttachmentRelationshipsToJSON(value['relationships']),
    };
}

