/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentData } from './AttachmentData';
import {
    AttachmentDataFromJSON,
    AttachmentDataFromJSONTyped,
    AttachmentDataToJSON,
    AttachmentDataToJSONTyped,
} from './AttachmentData';

/**
 * 
 * @export
 * @interface AttachmentResponse
 */
export interface AttachmentResponse {
    /**
     * 
     * @type {AttachmentData}
     * @memberof AttachmentResponse
     */
    data?: AttachmentData;
}

/**
 * Check if a given object implements the AttachmentResponse interface.
 */
export function instanceOfAttachmentResponse(value: object): value is AttachmentResponse {
    return true;
}

export function AttachmentResponseFromJSON(json: any): AttachmentResponse {
    return AttachmentResponseFromJSONTyped(json, false);
}

export function AttachmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AttachmentDataFromJSON(json['data']),
    };
}

export function AttachmentResponseToJSON(json: any): AttachmentResponse {
    return AttachmentResponseToJSONTyped(json, false);
}

export function AttachmentResponseToJSONTyped(value?: AttachmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AttachmentDataToJSON(value['data']),
    };
}

