/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMetaMeta } from './PaginationMetaMeta';
import {
    PaginationMetaMetaFromJSON,
    PaginationMetaMetaFromJSONTyped,
    PaginationMetaMetaToJSON,
    PaginationMetaMetaToJSONTyped,
} from './PaginationMetaMeta';
import type { BookEntryCollectionAllOfData } from './BookEntryCollectionAllOfData';
import {
    BookEntryCollectionAllOfDataFromJSON,
    BookEntryCollectionAllOfDataFromJSONTyped,
    BookEntryCollectionAllOfDataToJSON,
    BookEntryCollectionAllOfDataToJSONTyped,
} from './BookEntryCollectionAllOfData';

/**
 * 
 * @export
 * @interface BookEntryCollection
 */
export interface BookEntryCollection {
    /**
     * 
     * @type {PaginationMetaMeta}
     * @memberof BookEntryCollection
     */
    meta?: PaginationMetaMeta;
    /**
     * 
     * @type {Array<BookEntryCollectionAllOfData>}
     * @memberof BookEntryCollection
     */
    data?: Array<BookEntryCollectionAllOfData>;
}

/**
 * Check if a given object implements the BookEntryCollection interface.
 */
export function instanceOfBookEntryCollection(value: object): value is BookEntryCollection {
    return true;
}

export function BookEntryCollectionFromJSON(json: any): BookEntryCollection {
    return BookEntryCollectionFromJSONTyped(json, false);
}

export function BookEntryCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookEntryCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PaginationMetaMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BookEntryCollectionAllOfDataFromJSON)),
    };
}

export function BookEntryCollectionToJSON(json: any): BookEntryCollection {
    return BookEntryCollectionToJSONTyped(json, false);
}

export function BookEntryCollectionToJSONTyped(value?: BookEntryCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PaginationMetaMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BookEntryCollectionAllOfDataToJSON)),
    };
}

