/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InvoiceData } from './InvoiceData';
import {
    instanceOfInvoiceData,
    InvoiceDataFromJSON,
    InvoiceDataFromJSONTyped,
    InvoiceDataToJSON,
} from './InvoiceData';
import type { PaysheetData } from './PaysheetData';
import {
    instanceOfPaysheetData,
    PaysheetDataFromJSON,
    PaysheetDataFromJSONTyped,
    PaysheetDataToJSON,
} from './PaysheetData';
import type { TicketData } from './TicketData';
import {
    instanceOfTicketData,
    TicketDataFromJSON,
    TicketDataFromJSONTyped,
    TicketDataToJSON,
} from './TicketData';

/**
 * @type BookEntryCollectionAllOfData
 * 
 * @export
 */
export type BookEntryCollectionAllOfData = InvoiceData | PaysheetData | TicketData;

export function BookEntryCollectionAllOfDataFromJSON(json: any): BookEntryCollectionAllOfData {
    return BookEntryCollectionAllOfDataFromJSONTyped(json, false);
}

export function BookEntryCollectionAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookEntryCollectionAllOfData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfInvoiceData(json)) {
        return InvoiceDataFromJSONTyped(json, true);
    }
    if (instanceOfPaysheetData(json)) {
        return PaysheetDataFromJSONTyped(json, true);
    }
    if (instanceOfTicketData(json)) {
        return TicketDataFromJSONTyped(json, true);
    }
    return {} as any;
}

export function BookEntryCollectionAllOfDataToJSON(json: any): any {
    return BookEntryCollectionAllOfDataToJSONTyped(json, false);
}

export function BookEntryCollectionAllOfDataToJSONTyped(value?: BookEntryCollectionAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfInvoiceData(value)) {
        return InvoiceDataToJSON(value as InvoiceData);
    }
    if (instanceOfPaysheetData(value)) {
        return PaysheetDataToJSON(value as PaysheetData);
    }
    if (instanceOfTicketData(value)) {
        return TicketDataToJSON(value as TicketData);
    }
    return {};
}

