/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactAttributes } from './ContactAttributes';
import {
    ContactAttributesFromJSON,
    ContactAttributesFromJSONTyped,
    ContactAttributesToJSON,
    ContactAttributesToJSONTyped,
} from './ContactAttributes';

/**
 * 
 * @export
 * @interface ContactCollectionAllOfData
 */
export interface ContactCollectionAllOfData {
    /**
     * 
     * @type {string}
     * @memberof ContactCollectionAllOfData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactCollectionAllOfData
     */
    type?: string;
    /**
     * 
     * @type {ContactAttributes}
     * @memberof ContactCollectionAllOfData
     */
    attributes?: ContactAttributes;
}

/**
 * Check if a given object implements the ContactCollectionAllOfData interface.
 */
export function instanceOfContactCollectionAllOfData(value: object): value is ContactCollectionAllOfData {
    return true;
}

export function ContactCollectionAllOfDataFromJSON(json: any): ContactCollectionAllOfData {
    return ContactCollectionAllOfDataFromJSONTyped(json, false);
}

export function ContactCollectionAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactCollectionAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : ContactAttributesFromJSON(json['attributes']),
    };
}

export function ContactCollectionAllOfDataToJSON(json: any): ContactCollectionAllOfData {
    return ContactCollectionAllOfDataToJSONTyped(json, false);
}

export function ContactCollectionAllOfDataToJSONTyped(value?: ContactCollectionAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': ContactAttributesToJSON(value['attributes']),
    };
}

