/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactCreateData } from './ContactCreateData';
import {
    ContactCreateDataFromJSON,
    ContactCreateDataFromJSONTyped,
    ContactCreateDataToJSON,
    ContactCreateDataToJSONTyped,
} from './ContactCreateData';

/**
 * 
 * @export
 * @interface ContactCreate
 */
export interface ContactCreate {
    /**
     * 
     * @type {ContactCreateData}
     * @memberof ContactCreate
     */
    data: ContactCreateData;
}

/**
 * Check if a given object implements the ContactCreate interface.
 */
export function instanceOfContactCreate(value: object): value is ContactCreate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ContactCreateFromJSON(json: any): ContactCreate {
    return ContactCreateFromJSONTyped(json, false);
}

export function ContactCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ContactCreateDataFromJSON(json['data']),
    };
}

export function ContactCreateToJSON(json: any): ContactCreate {
    return ContactCreateToJSONTyped(json, false);
}

export function ContactCreateToJSONTyped(value?: ContactCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ContactCreateDataToJSON(value['data']),
    };
}

