/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactAttributes } from './ContactAttributes';
import {
    ContactAttributesFromJSON,
    ContactAttributesFromJSONTyped,
    ContactAttributesToJSON,
    ContactAttributesToJSONTyped,
} from './ContactAttributes';

/**
 * 
 * @export
 * @interface ContactCreateData
 */
export interface ContactCreateData {
    /**
     * 
     * @type {ContactCreateDataTypeEnum}
     * @memberof ContactCreateData
     */
    type: ContactCreateDataTypeEnum;
    /**
     * 
     * @type {ContactAttributes}
     * @memberof ContactCreateData
     */
    attributes: ContactAttributes;
}


/**
 * @export
 */
export const ContactCreateDataTypeEnum = {
    Contacts: 'contacts'
} as const;
export type ContactCreateDataTypeEnum = typeof ContactCreateDataTypeEnum[keyof typeof ContactCreateDataTypeEnum];


/**
 * Check if a given object implements the ContactCreateData interface.
 */
export function instanceOfContactCreateData(value: object): value is ContactCreateData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ContactCreateDataFromJSON(json: any): ContactCreateData {
    return ContactCreateDataFromJSONTyped(json, false);
}

export function ContactCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': ContactAttributesFromJSON(json['attributes']),
    };
}

export function ContactCreateDataToJSON(json: any): ContactCreateData {
    return ContactCreateDataToJSONTyped(json, false);
}

export function ContactCreateDataToJSONTyped(value?: ContactCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': ContactAttributesToJSON(value['attributes']),
    };
}

