/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactCollectionAllOfData } from './ContactCollectionAllOfData';
import {
    ContactCollectionAllOfDataFromJSON,
    ContactCollectionAllOfDataFromJSONTyped,
    ContactCollectionAllOfDataToJSON,
    ContactCollectionAllOfDataToJSONTyped,
} from './ContactCollectionAllOfData';
import type { PaginationMetaMeta } from './PaginationMetaMeta';
import {
    PaginationMetaMetaFromJSON,
    PaginationMetaMetaFromJSONTyped,
    PaginationMetaMetaToJSON,
    PaginationMetaMetaToJSONTyped,
} from './PaginationMetaMeta';

/**
 * 
 * @export
 * @interface ContactCollection
 */
export interface ContactCollection {
    /**
     * 
     * @type {PaginationMetaMeta}
     * @memberof ContactCollection
     */
    meta?: PaginationMetaMeta;
    /**
     * 
     * @type {Array<ContactCollectionAllOfData>}
     * @memberof ContactCollection
     */
    data?: Array<ContactCollectionAllOfData>;
}

/**
 * Check if a given object implements the ContactCollection interface.
 */
export function instanceOfContactCollection(value: object): value is ContactCollection {
    return true;
}

export function ContactCollectionFromJSON(json: any): ContactCollection {
    return ContactCollectionFromJSONTyped(json, false);
}

export function ContactCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PaginationMetaMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ContactCollectionAllOfDataFromJSON)),
    };
}

export function ContactCollectionToJSON(json: any): ContactCollection {
    return ContactCollectionToJSONTyped(json, false);
}

export function ContactCollectionToJSONTyped(value?: ContactCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PaginationMetaMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ContactCollectionAllOfDataToJSON)),
    };
}

