/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactAttributes
 */
export interface ContactAttributes {
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    taxId?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    town?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    zipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    readonly totalPaidIncomes?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    readonly totalUnpaidIncomes?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    readonly totalIncomes?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    readonly totalPaidExpenses?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    readonly totalUnpaidExpenses?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    readonly totalExpenses?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    clientNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    supplierNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ContactAttributes
     */
    readonly isClient?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContactAttributes
     */
    readonly isSupplier?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContactAttributes
     */
    readonly isEmployee?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContactAttributes
     */
    isSupplierOfDirectGoods?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    bankAccountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAttributes
     */
    bankAccountSwiftBic?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContactAttributes
     */
    readonly deletable?: boolean;
}

/**
 * Check if a given object implements the ContactAttributes interface.
 */
export function instanceOfContactAttributes(value: object): value is ContactAttributes {
    return true;
}

export function ContactAttributesFromJSON(json: any): ContactAttributes {
    return ContactAttributesFromJSONTyped(json, false);
}

export function ContactAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'taxId': json['tax_id'] == null ? undefined : json['tax_id'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : json['address'],
        'town': json['town'] == null ? undefined : json['town'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'totalPaidIncomes': json['total_paid_incomes'] == null ? undefined : json['total_paid_incomes'],
        'totalUnpaidIncomes': json['total_unpaid_incomes'] == null ? undefined : json['total_unpaid_incomes'],
        'totalIncomes': json['total_incomes'] == null ? undefined : json['total_incomes'],
        'totalPaidExpenses': json['total_paid_expenses'] == null ? undefined : json['total_paid_expenses'],
        'totalUnpaidExpenses': json['total_unpaid_expenses'] == null ? undefined : json['total_unpaid_expenses'],
        'totalExpenses': json['total_expenses'] == null ? undefined : json['total_expenses'],
        'clientNumber': json['client_number'] == null ? undefined : json['client_number'],
        'supplierNumber': json['supplier_number'] == null ? undefined : json['supplier_number'],
        'isClient': json['is_client'] == null ? undefined : json['is_client'],
        'isSupplier': json['is_supplier'] == null ? undefined : json['is_supplier'],
        'isEmployee': json['is_employee'] == null ? undefined : json['is_employee'],
        'isSupplierOfDirectGoods': json['is_supplier_of_direct_goods'] == null ? undefined : json['is_supplier_of_direct_goods'],
        'bankAccountNumber': json['bank_account_number'] == null ? undefined : json['bank_account_number'],
        'bankAccountSwiftBic': json['bank_account_swift_bic'] == null ? undefined : json['bank_account_swift_bic'],
        'deletable': json['deletable'] == null ? undefined : json['deletable'],
    };
}

export function ContactAttributesToJSON(json: any): ContactAttributes {
    return ContactAttributesToJSONTyped(json, false);
}

export function ContactAttributesToJSONTyped(value?: Omit<ContactAttributes, 'total_paid_incomes'|'total_unpaid_incomes'|'total_incomes'|'total_paid_expenses'|'total_unpaid_expenses'|'total_expenses'|'is_client'|'is_supplier'|'is_employee'|'deletable'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'tax_id': value['taxId'],
        'phone': value['phone'],
        'email': value['email'],
        'address': value['address'],
        'town': value['town'],
        'zip_code': value['zipCode'],
        'country_code': value['countryCode'],
        'client_number': value['clientNumber'],
        'supplier_number': value['supplierNumber'],
        'is_supplier_of_direct_goods': value['isSupplierOfDirectGoods'],
        'bank_account_number': value['bankAccountNumber'],
        'bank_account_swift_bic': value['bankAccountSwiftBic'],
    };
}

