/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactResponseData } from './ContactResponseData';
import {
    ContactResponseDataFromJSON,
    ContactResponseDataFromJSONTyped,
    ContactResponseDataToJSON,
    ContactResponseDataToJSONTyped,
} from './ContactResponseData';

/**
 * 
 * @export
 * @interface ContactResponse
 */
export interface ContactResponse {
    /**
     * 
     * @type {ContactResponseData}
     * @memberof ContactResponse
     */
    data?: ContactResponseData;
}

/**
 * Check if a given object implements the ContactResponse interface.
 */
export function instanceOfContactResponse(value: object): value is ContactResponse {
    return true;
}

export function ContactResponseFromJSON(json: any): ContactResponse {
    return ContactResponseFromJSONTyped(json, false);
}

export function ContactResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ContactResponseDataFromJSON(json['data']),
    };
}

export function ContactResponseToJSON(json: any): ContactResponse {
    return ContactResponseToJSONTyped(json, false);
}

export function ContactResponseToJSONTyped(value?: ContactResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ContactResponseDataToJSON(value['data']),
    };
}

