/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseErrorsInnerSource
 */
export interface ErrorResponseErrorsInnerSource {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseErrorsInnerSource
     */
    pointer?: string;
}

/**
 * Check if a given object implements the ErrorResponseErrorsInnerSource interface.
 */
export function instanceOfErrorResponseErrorsInnerSource(value: object): value is ErrorResponseErrorsInnerSource {
    return true;
}

export function ErrorResponseErrorsInnerSourceFromJSON(json: any): ErrorResponseErrorsInnerSource {
    return ErrorResponseErrorsInnerSourceFromJSONTyped(json, false);
}

export function ErrorResponseErrorsInnerSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseErrorsInnerSource {
    if (json == null) {
        return json;
    }
    return {
        
        'pointer': json['pointer'] == null ? undefined : json['pointer'],
    };
}

export function ErrorResponseErrorsInnerSourceToJSON(json: any): ErrorResponseErrorsInnerSource {
    return ErrorResponseErrorsInnerSourceToJSONTyped(json, false);
}

export function ErrorResponseErrorsInnerSourceToJSONTyped(value?: ErrorResponseErrorsInnerSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pointer': value['pointer'],
    };
}

