/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorResponseErrorsInnerSource } from './ErrorResponseErrorsInnerSource';
import {
    ErrorResponseErrorsInnerSourceFromJSON,
    ErrorResponseErrorsInnerSourceFromJSONTyped,
    ErrorResponseErrorsInnerSourceToJSON,
    ErrorResponseErrorsInnerSourceToJSONTyped,
} from './ErrorResponseErrorsInnerSource';

/**
 * 
 * @export
 * @interface ErrorResponseErrorsInner
 */
export interface ErrorResponseErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseErrorsInner
     */
    detail?: string;
    /**
     * 
     * @type {ErrorResponseErrorsInnerSource}
     * @memberof ErrorResponseErrorsInner
     */
    source?: ErrorResponseErrorsInnerSource;
}

/**
 * Check if a given object implements the ErrorResponseErrorsInner interface.
 */
export function instanceOfErrorResponseErrorsInner(value: object): value is ErrorResponseErrorsInner {
    return true;
}

export function ErrorResponseErrorsInnerFromJSON(json: any): ErrorResponseErrorsInner {
    return ErrorResponseErrorsInnerFromJSONTyped(json, false);
}

export function ErrorResponseErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseErrorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
        'source': json['source'] == null ? undefined : ErrorResponseErrorsInnerSourceFromJSON(json['source']),
    };
}

export function ErrorResponseErrorsInnerToJSON(json: any): ErrorResponseErrorsInner {
    return ErrorResponseErrorsInnerToJSONTyped(json, false);
}

export function ErrorResponseErrorsInnerToJSONTyped(value?: ErrorResponseErrorsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
        'source': ErrorResponseErrorsInnerSourceToJSON(value['source']),
    };
}

