/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBookEntriesFilterFieldQueryParameter
 */
export interface GetBookEntriesFilterFieldQueryParameter {
    /**
     * 
     * @type {string}
     * @memberof GetBookEntriesFilterFieldQueryParameter
     */
    field?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBookEntriesFilterFieldQueryParameter
     */
    term?: string | null;
}

/**
 * Check if a given object implements the GetBookEntriesFilterFieldQueryParameter interface.
 */
export function instanceOfGetBookEntriesFilterFieldQueryParameter(value: object): value is GetBookEntriesFilterFieldQueryParameter {
    return true;
}

export function GetBookEntriesFilterFieldQueryParameterFromJSON(json: any): GetBookEntriesFilterFieldQueryParameter {
    return GetBookEntriesFilterFieldQueryParameterFromJSONTyped(json, false);
}

export function GetBookEntriesFilterFieldQueryParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBookEntriesFilterFieldQueryParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'term': json['term'] == null ? undefined : json['term'],
    };
}

export function GetBookEntriesFilterFieldQueryParameterToJSON(json: any): GetBookEntriesFilterFieldQueryParameter {
    return GetBookEntriesFilterFieldQueryParameterToJSONTyped(json, false);
}

export function GetBookEntriesFilterFieldQueryParameterToJSONTyped(value?: GetBookEntriesFilterFieldQueryParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'term': value['term'],
    };
}

