/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceRelationshipsAnalyticCategoriesDataInner
 */
export interface InvoiceRelationshipsAnalyticCategoriesDataInner {
    /**
     * 
     * @type {string}
     * @memberof InvoiceRelationshipsAnalyticCategoriesDataInner
     */
    id?: string;
    /**
     * 
     * @type {InvoiceRelationshipsAnalyticCategoriesDataInnerTypeEnum}
     * @memberof InvoiceRelationshipsAnalyticCategoriesDataInner
     */
    type?: InvoiceRelationshipsAnalyticCategoriesDataInnerTypeEnum;
}


/**
 * @export
 */
export const InvoiceRelationshipsAnalyticCategoriesDataInnerTypeEnum = {
    AnalyticCategories: 'analytic_categories'
} as const;
export type InvoiceRelationshipsAnalyticCategoriesDataInnerTypeEnum = typeof InvoiceRelationshipsAnalyticCategoriesDataInnerTypeEnum[keyof typeof InvoiceRelationshipsAnalyticCategoriesDataInnerTypeEnum];


/**
 * Check if a given object implements the InvoiceRelationshipsAnalyticCategoriesDataInner interface.
 */
export function instanceOfInvoiceRelationshipsAnalyticCategoriesDataInner(value: object): value is InvoiceRelationshipsAnalyticCategoriesDataInner {
    return true;
}

export function InvoiceRelationshipsAnalyticCategoriesDataInnerFromJSON(json: any): InvoiceRelationshipsAnalyticCategoriesDataInner {
    return InvoiceRelationshipsAnalyticCategoriesDataInnerFromJSONTyped(json, false);
}

export function InvoiceRelationshipsAnalyticCategoriesDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsAnalyticCategoriesDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function InvoiceRelationshipsAnalyticCategoriesDataInnerToJSON(json: any): InvoiceRelationshipsAnalyticCategoriesDataInner {
    return InvoiceRelationshipsAnalyticCategoriesDataInnerToJSONTyped(json, false);
}

export function InvoiceRelationshipsAnalyticCategoriesDataInnerToJSONTyped(value?: InvoiceRelationshipsAnalyticCategoriesDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

