/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceCollectionAllOfIncluded
 */
export interface InvoiceCollectionAllOfIncluded {
    /**
     * 
     * @type {string}
     * @memberof InvoiceCollectionAllOfIncluded
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceCollectionAllOfIncluded
     */
    type?: string;
    /**
     * 
     * @type {object}
     * @memberof InvoiceCollectionAllOfIncluded
     */
    attributes?: object;
}

/**
 * Check if a given object implements the InvoiceCollectionAllOfIncluded interface.
 */
export function instanceOfInvoiceCollectionAllOfIncluded(value: object): value is InvoiceCollectionAllOfIncluded {
    return true;
}

export function InvoiceCollectionAllOfIncludedFromJSON(json: any): InvoiceCollectionAllOfIncluded {
    return InvoiceCollectionAllOfIncludedFromJSONTyped(json, false);
}

export function InvoiceCollectionAllOfIncludedFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceCollectionAllOfIncluded {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
    };
}

export function InvoiceCollectionAllOfIncludedToJSON(json: any): InvoiceCollectionAllOfIncluded {
    return InvoiceCollectionAllOfIncludedToJSONTyped(json, false);
}

export function InvoiceCollectionAllOfIncludedToJSONTyped(value?: InvoiceCollectionAllOfIncluded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': value['attributes'],
    };
}

