/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceRelationshipsAmendedInvoiceData
 */
export interface InvoiceRelationshipsAmendedInvoiceData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceRelationshipsAmendedInvoiceData
     */
    id?: string;
    /**
     * 
     * @type {InvoiceRelationshipsAmendedInvoiceDataTypeEnum}
     * @memberof InvoiceRelationshipsAmendedInvoiceData
     */
    type?: InvoiceRelationshipsAmendedInvoiceDataTypeEnum;
}


/**
 * @export
 */
export const InvoiceRelationshipsAmendedInvoiceDataTypeEnum = {
    Invoices: 'invoices'
} as const;
export type InvoiceRelationshipsAmendedInvoiceDataTypeEnum = typeof InvoiceRelationshipsAmendedInvoiceDataTypeEnum[keyof typeof InvoiceRelationshipsAmendedInvoiceDataTypeEnum];


/**
 * Check if a given object implements the InvoiceRelationshipsAmendedInvoiceData interface.
 */
export function instanceOfInvoiceRelationshipsAmendedInvoiceData(value: object): value is InvoiceRelationshipsAmendedInvoiceData {
    return true;
}

export function InvoiceRelationshipsAmendedInvoiceDataFromJSON(json: any): InvoiceRelationshipsAmendedInvoiceData {
    return InvoiceRelationshipsAmendedInvoiceDataFromJSONTyped(json, false);
}

export function InvoiceRelationshipsAmendedInvoiceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsAmendedInvoiceData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function InvoiceRelationshipsAmendedInvoiceDataToJSON(json: any): InvoiceRelationshipsAmendedInvoiceData {
    return InvoiceRelationshipsAmendedInvoiceDataToJSONTyped(json, false);
}

export function InvoiceRelationshipsAmendedInvoiceDataToJSONTyped(value?: InvoiceRelationshipsAmendedInvoiceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

