/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ItemInvoiceCreate } from './ItemInvoiceCreate';
import {
    instanceOfItemInvoiceCreate,
    ItemInvoiceCreateFromJSON,
    ItemInvoiceCreateFromJSONTyped,
    ItemInvoiceCreateToJSON,
} from './ItemInvoiceCreate';
import type { ItemInvoiceUpdate } from './ItemInvoiceUpdate';
import {
    instanceOfItemInvoiceUpdate,
    ItemInvoiceUpdateFromJSON,
    ItemInvoiceUpdateFromJSONTyped,
    ItemInvoiceUpdateToJSON,
} from './ItemInvoiceUpdate';

/**
 * @type InvoiceRelationshipsItemsDataInner
 * 
 * @export
 */
export type InvoiceRelationshipsItemsDataInner = ItemInvoiceCreate | ItemInvoiceUpdate;

export function InvoiceRelationshipsItemsDataInnerFromJSON(json: any): InvoiceRelationshipsItemsDataInner {
    return InvoiceRelationshipsItemsDataInnerFromJSONTyped(json, false);
}

export function InvoiceRelationshipsItemsDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsItemsDataInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfItemInvoiceCreate(json)) {
        return ItemInvoiceCreateFromJSONTyped(json, true);
    }
    if (instanceOfItemInvoiceUpdate(json)) {
        return ItemInvoiceUpdateFromJSONTyped(json, true);
    }
    return {} as any;
}

export function InvoiceRelationshipsItemsDataInnerToJSON(json: any): any {
    return InvoiceRelationshipsItemsDataInnerToJSONTyped(json, false);
}

export function InvoiceRelationshipsItemsDataInnerToJSONTyped(value?: InvoiceRelationshipsItemsDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfItemInvoiceCreate(value)) {
        return ItemInvoiceCreateToJSON(value as ItemInvoiceCreate);
    }
    if (instanceOfItemInvoiceUpdate(value)) {
        return ItemInvoiceUpdateToJSON(value as ItemInvoiceUpdate);
    }
    return {};
}

