/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceRelationshipsAccountingCategoryData
 */
export interface InvoiceRelationshipsAccountingCategoryData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceRelationshipsAccountingCategoryData
     */
    id?: string;
    /**
     * 
     * @type {InvoiceRelationshipsAccountingCategoryDataTypeEnum}
     * @memberof InvoiceRelationshipsAccountingCategoryData
     */
    type?: InvoiceRelationshipsAccountingCategoryDataTypeEnum;
}


/**
 * @export
 */
export const InvoiceRelationshipsAccountingCategoryDataTypeEnum = {
    AccountingCategories: 'accounting_categories'
} as const;
export type InvoiceRelationshipsAccountingCategoryDataTypeEnum = typeof InvoiceRelationshipsAccountingCategoryDataTypeEnum[keyof typeof InvoiceRelationshipsAccountingCategoryDataTypeEnum];


/**
 * Check if a given object implements the InvoiceRelationshipsAccountingCategoryData interface.
 */
export function instanceOfInvoiceRelationshipsAccountingCategoryData(value: object): value is InvoiceRelationshipsAccountingCategoryData {
    return true;
}

export function InvoiceRelationshipsAccountingCategoryDataFromJSON(json: any): InvoiceRelationshipsAccountingCategoryData {
    return InvoiceRelationshipsAccountingCategoryDataFromJSONTyped(json, false);
}

export function InvoiceRelationshipsAccountingCategoryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsAccountingCategoryData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function InvoiceRelationshipsAccountingCategoryDataToJSON(json: any): InvoiceRelationshipsAccountingCategoryData {
    return InvoiceRelationshipsAccountingCategoryDataToJSONTyped(json, false);
}

export function InvoiceRelationshipsAccountingCategoryDataToJSONTyped(value?: InvoiceRelationshipsAccountingCategoryData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

