/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceRelationshipsContactData
 */
export interface InvoiceRelationshipsContactData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceRelationshipsContactData
     */
    id?: string;
    /**
     * 
     * @type {InvoiceRelationshipsContactDataTypeEnum}
     * @memberof InvoiceRelationshipsContactData
     */
    type?: InvoiceRelationshipsContactDataTypeEnum;
}


/**
 * @export
 */
export const InvoiceRelationshipsContactDataTypeEnum = {
    Contacts: 'contacts'
} as const;
export type InvoiceRelationshipsContactDataTypeEnum = typeof InvoiceRelationshipsContactDataTypeEnum[keyof typeof InvoiceRelationshipsContactDataTypeEnum];


/**
 * Check if a given object implements the InvoiceRelationshipsContactData interface.
 */
export function instanceOfInvoiceRelationshipsContactData(value: object): value is InvoiceRelationshipsContactData {
    return true;
}

export function InvoiceRelationshipsContactDataFromJSON(json: any): InvoiceRelationshipsContactData {
    return InvoiceRelationshipsContactDataFromJSONTyped(json, false);
}

export function InvoiceRelationshipsContactDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsContactData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function InvoiceRelationshipsContactDataToJSON(json: any): InvoiceRelationshipsContactData {
    return InvoiceRelationshipsContactDataToJSONTyped(json, false);
}

export function InvoiceRelationshipsContactDataToJSONTyped(value?: InvoiceRelationshipsContactData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

