/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsItemsDataInner } from './InvoiceRelationshipsItemsDataInner';
import {
    InvoiceRelationshipsItemsDataInnerFromJSON,
    InvoiceRelationshipsItemsDataInnerFromJSONTyped,
    InvoiceRelationshipsItemsDataInnerToJSON,
    InvoiceRelationshipsItemsDataInnerToJSONTyped,
} from './InvoiceRelationshipsItemsDataInner';

/**
 * 
 * @export
 * @interface InvoiceRelationshipsItems
 */
export interface InvoiceRelationshipsItems {
    /**
     * 
     * @type {Array<InvoiceRelationshipsItemsDataInner>}
     * @memberof InvoiceRelationshipsItems
     */
    data?: Array<InvoiceRelationshipsItemsDataInner>;
}

/**
 * Check if a given object implements the InvoiceRelationshipsItems interface.
 */
export function instanceOfInvoiceRelationshipsItems(value: object): value is InvoiceRelationshipsItems {
    return true;
}

export function InvoiceRelationshipsItemsFromJSON(json: any): InvoiceRelationshipsItems {
    return InvoiceRelationshipsItemsFromJSONTyped(json, false);
}

export function InvoiceRelationshipsItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsItems {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(InvoiceRelationshipsItemsDataInnerFromJSON)),
    };
}

export function InvoiceRelationshipsItemsToJSON(json: any): InvoiceRelationshipsItems {
    return InvoiceRelationshipsItemsToJSONTyped(json, false);
}

export function InvoiceRelationshipsItemsToJSONTyped(value?: InvoiceRelationshipsItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(InvoiceRelationshipsItemsDataInnerToJSON)),
    };
}

