/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsAmendedInvoiceData } from './InvoiceRelationshipsAmendedInvoiceData';
import {
    InvoiceRelationshipsAmendedInvoiceDataFromJSON,
    InvoiceRelationshipsAmendedInvoiceDataFromJSONTyped,
    InvoiceRelationshipsAmendedInvoiceDataToJSON,
    InvoiceRelationshipsAmendedInvoiceDataToJSONTyped,
} from './InvoiceRelationshipsAmendedInvoiceData';

/**
 * 
 * @export
 * @interface InvoiceRelationshipsAmendedInvoice
 */
export interface InvoiceRelationshipsAmendedInvoice {
    /**
     * 
     * @type {InvoiceRelationshipsAmendedInvoiceData}
     * @memberof InvoiceRelationshipsAmendedInvoice
     */
    data?: InvoiceRelationshipsAmendedInvoiceData | null;
}

/**
 * Check if a given object implements the InvoiceRelationshipsAmendedInvoice interface.
 */
export function instanceOfInvoiceRelationshipsAmendedInvoice(value: object): value is InvoiceRelationshipsAmendedInvoice {
    return true;
}

export function InvoiceRelationshipsAmendedInvoiceFromJSON(json: any): InvoiceRelationshipsAmendedInvoice {
    return InvoiceRelationshipsAmendedInvoiceFromJSONTyped(json, false);
}

export function InvoiceRelationshipsAmendedInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsAmendedInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : InvoiceRelationshipsAmendedInvoiceDataFromJSON(json['data']),
    };
}

export function InvoiceRelationshipsAmendedInvoiceToJSON(json: any): InvoiceRelationshipsAmendedInvoice {
    return InvoiceRelationshipsAmendedInvoiceToJSONTyped(json, false);
}

export function InvoiceRelationshipsAmendedInvoiceToJSONTyped(value?: InvoiceRelationshipsAmendedInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvoiceRelationshipsAmendedInvoiceDataToJSON(value['data']),
    };
}

