/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceCreateData } from './InvoiceCreateData';
import {
    InvoiceCreateDataFromJSON,
    InvoiceCreateDataFromJSONTyped,
    InvoiceCreateDataToJSON,
    InvoiceCreateDataToJSONTyped,
} from './InvoiceCreateData';

/**
 * 
 * @export
 * @interface InvoiceCreate
 */
export interface InvoiceCreate {
    /**
     * 
     * @type {InvoiceCreateData}
     * @memberof InvoiceCreate
     */
    data: InvoiceCreateData;
}

/**
 * Check if a given object implements the InvoiceCreate interface.
 */
export function instanceOfInvoiceCreate(value: object): value is InvoiceCreate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InvoiceCreateFromJSON(json: any): InvoiceCreate {
    return InvoiceCreateFromJSONTyped(json, false);
}

export function InvoiceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': InvoiceCreateDataFromJSON(json['data']),
    };
}

export function InvoiceCreateToJSON(json: any): InvoiceCreate {
    return InvoiceCreateToJSONTyped(json, false);
}

export function InvoiceCreateToJSONTyped(value?: InvoiceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvoiceCreateDataToJSON(value['data']),
    };
}

