/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceAttributes } from './InvoiceAttributes';
import {
    InvoiceAttributesFromJSON,
    InvoiceAttributesFromJSONTyped,
    InvoiceAttributesToJSON,
    InvoiceAttributesToJSONTyped,
} from './InvoiceAttributes';
import type { InvoiceRelationships } from './InvoiceRelationships';
import {
    InvoiceRelationshipsFromJSON,
    InvoiceRelationshipsFromJSONTyped,
    InvoiceRelationshipsToJSON,
    InvoiceRelationshipsToJSONTyped,
} from './InvoiceRelationships';

/**
 * 
 * @export
 * @interface InvoiceData
 */
export interface InvoiceData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceData
     */
    id?: string;
    /**
     * 
     * @type {InvoiceDataTypeEnum}
     * @memberof InvoiceData
     */
    type?: InvoiceDataTypeEnum;
    /**
     * 
     * @type {InvoiceAttributes}
     * @memberof InvoiceData
     */
    attributes?: InvoiceAttributes;
    /**
     * 
     * @type {InvoiceRelationships}
     * @memberof InvoiceData
     */
    relationships?: InvoiceRelationships;
}


/**
 * @export
 */
export const InvoiceDataTypeEnum = {
    Invoices: 'invoices'
} as const;
export type InvoiceDataTypeEnum = typeof InvoiceDataTypeEnum[keyof typeof InvoiceDataTypeEnum];


/**
 * Check if a given object implements the InvoiceData interface.
 */
export function instanceOfInvoiceData(value: object): value is InvoiceData {
    return true;
}

export function InvoiceDataFromJSON(json: any): InvoiceData {
    return InvoiceDataFromJSONTyped(json, false);
}

export function InvoiceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : InvoiceAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : InvoiceRelationshipsFromJSON(json['relationships']),
    };
}

export function InvoiceDataToJSON(json: any): InvoiceData {
    return InvoiceDataToJSONTyped(json, false);
}

export function InvoiceDataToJSONTyped(value?: InvoiceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': InvoiceAttributesToJSON(value['attributes']),
        'relationships': InvoiceRelationshipsToJSON(value['relationships']),
    };
}

