/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceAttributes } from './InvoiceAttributes';
import {
    InvoiceAttributesFromJSON,
    InvoiceAttributesFromJSONTyped,
    InvoiceAttributesToJSON,
    InvoiceAttributesToJSONTyped,
} from './InvoiceAttributes';
import type { InvoiceRelationships } from './InvoiceRelationships';
import {
    InvoiceRelationshipsFromJSON,
    InvoiceRelationshipsFromJSONTyped,
    InvoiceRelationshipsToJSON,
    InvoiceRelationshipsToJSONTyped,
} from './InvoiceRelationships';

/**
 * 
 * @export
 * @interface InvoiceUpdateData
 */
export interface InvoiceUpdateData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceUpdateData
     */
    id: string;
    /**
     * 
     * @type {InvoiceUpdateDataTypeEnum}
     * @memberof InvoiceUpdateData
     */
    type: InvoiceUpdateDataTypeEnum;
    /**
     * 
     * @type {InvoiceAttributes}
     * @memberof InvoiceUpdateData
     */
    attributes?: InvoiceAttributes;
    /**
     * 
     * @type {InvoiceRelationships}
     * @memberof InvoiceUpdateData
     */
    relationships?: InvoiceRelationships;
}


/**
 * @export
 */
export const InvoiceUpdateDataTypeEnum = {
    Invoices: 'invoices'
} as const;
export type InvoiceUpdateDataTypeEnum = typeof InvoiceUpdateDataTypeEnum[keyof typeof InvoiceUpdateDataTypeEnum];


/**
 * Check if a given object implements the InvoiceUpdateData interface.
 */
export function instanceOfInvoiceUpdateData(value: object): value is InvoiceUpdateData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function InvoiceUpdateDataFromJSON(json: any): InvoiceUpdateData {
    return InvoiceUpdateDataFromJSONTyped(json, false);
}

export function InvoiceUpdateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceUpdateData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : InvoiceAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : InvoiceRelationshipsFromJSON(json['relationships']),
    };
}

export function InvoiceUpdateDataToJSON(json: any): InvoiceUpdateData {
    return InvoiceUpdateDataToJSONTyped(json, false);
}

export function InvoiceUpdateDataToJSONTyped(value?: InvoiceUpdateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': InvoiceAttributesToJSON(value['attributes']),
        'relationships': InvoiceRelationshipsToJSON(value['relationships']),
    };
}

