/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceRelationshipsNumerationData
 */
export interface InvoiceRelationshipsNumerationData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceRelationshipsNumerationData
     */
    id?: string;
    /**
     * 
     * @type {InvoiceRelationshipsNumerationDataTypeEnum}
     * @memberof InvoiceRelationshipsNumerationData
     */
    type?: InvoiceRelationshipsNumerationDataTypeEnum;
}


/**
 * @export
 */
export const InvoiceRelationshipsNumerationDataTypeEnum = {
    NumberingSeries: 'numbering_series'
} as const;
export type InvoiceRelationshipsNumerationDataTypeEnum = typeof InvoiceRelationshipsNumerationDataTypeEnum[keyof typeof InvoiceRelationshipsNumerationDataTypeEnum];


/**
 * Check if a given object implements the InvoiceRelationshipsNumerationData interface.
 */
export function instanceOfInvoiceRelationshipsNumerationData(value: object): value is InvoiceRelationshipsNumerationData {
    return true;
}

export function InvoiceRelationshipsNumerationDataFromJSON(json: any): InvoiceRelationshipsNumerationData {
    return InvoiceRelationshipsNumerationDataFromJSONTyped(json, false);
}

export function InvoiceRelationshipsNumerationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsNumerationData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function InvoiceRelationshipsNumerationDataToJSON(json: any): InvoiceRelationshipsNumerationData {
    return InvoiceRelationshipsNumerationDataToJSONTyped(json, false);
}

export function InvoiceRelationshipsNumerationDataToJSONTyped(value?: InvoiceRelationshipsNumerationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

