/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceResponseIncludedInner
 */
export interface InvoiceResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseIncludedInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseIncludedInner
     */
    type?: string;
    /**
     * 
     * @type {object}
     * @memberof InvoiceResponseIncludedInner
     */
    attributes?: object;
}

/**
 * Check if a given object implements the InvoiceResponseIncludedInner interface.
 */
export function instanceOfInvoiceResponseIncludedInner(value: object): value is InvoiceResponseIncludedInner {
    return true;
}

export function InvoiceResponseIncludedInnerFromJSON(json: any): InvoiceResponseIncludedInner {
    return InvoiceResponseIncludedInnerFromJSONTyped(json, false);
}

export function InvoiceResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
    };
}

export function InvoiceResponseIncludedInnerToJSON(json: any): InvoiceResponseIncludedInner {
    return InvoiceResponseIncludedInnerToJSONTyped(json, false);
}

export function InvoiceResponseIncludedInnerToJSONTyped(value?: InvoiceResponseIncludedInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': value['attributes'],
    };
}

