/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceAttributes
 */
export interface InvoiceAttributes {
    /**
     * 
     * @type {InvoiceAttributesKindEnum}
     * @memberof InvoiceAttributes
     */
    kind?: InvoiceAttributesKindEnum;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    number?: string;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceAttributes
     */
    issueDate?: Date;
    /**
     * 
     * @type {Array<Date>}
     * @memberof InvoiceAttributes
     */
    dueDates?: Array<Date>;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceAttributes
     */
    paidAt?: Date | null;
    /**
     * 
     * @type {InvoiceAttributesPaymentMethodEnum}
     * @memberof InvoiceAttributes
     */
    paymentMethod?: InvoiceAttributesPaymentMethodEnum;
    /**
     * 
     * @type {InvoiceAttributesPaymentStatusEnum}
     * @memberof InvoiceAttributes
     */
    readonly paymentStatus?: InvoiceAttributesPaymentStatusEnum;
    /**
     * 
     * @type {InvoiceAttributesValidationStatusEnum}
     * @memberof InvoiceAttributes
     */
    readonly validationStatus?: InvoiceAttributesValidationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly totalAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly totalAmountWithoutTaxes?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly vatAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly retentionAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly issuingName?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly issuingTaxId?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly issuingAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly issuingPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly issuingTown?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly issuingZipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly issuingCountryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly recipientName?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly recipientTaxId?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly recipientAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly recipientPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly recipientTown?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly recipientZipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly recipientCountryCode?: string;
    /**
     * 
     * @type {number}
     * @memberof InvoiceAttributes
     */
    lastSentAt?: number;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly downloadPdfUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceAttributes
     */
    readonly ephemeralOpenDownloadPdfUrl?: string;
}


/**
 * @export
 */
export const InvoiceAttributesKindEnum = {
    Income: 'income',
    Expenses: 'expenses'
} as const;
export type InvoiceAttributesKindEnum = typeof InvoiceAttributesKindEnum[keyof typeof InvoiceAttributesKindEnum];

/**
 * @export
 */
export const InvoiceAttributesPaymentMethodEnum = {
    Cash: 'cash',
    BankTransfer: 'bank_transfer',
    BankCard: 'bank_card',
    DirectDebit: 'direct_debit',
    Paypal: 'paypal',
    Check: 'check',
    Factoring: 'factoring'
} as const;
export type InvoiceAttributesPaymentMethodEnum = typeof InvoiceAttributesPaymentMethodEnum[keyof typeof InvoiceAttributesPaymentMethodEnum];

/**
 * @export
 */
export const InvoiceAttributesPaymentStatusEnum = {
    Paid: 'paid',
    Unpaid: 'unpaid',
    Due: 'due',
    Pending: 'pending'
} as const;
export type InvoiceAttributesPaymentStatusEnum = typeof InvoiceAttributesPaymentStatusEnum[keyof typeof InvoiceAttributesPaymentStatusEnum];

/**
 * @export
 */
export const InvoiceAttributesValidationStatusEnum = {
    Pending: 'pending',
    Verified: 'verified'
} as const;
export type InvoiceAttributesValidationStatusEnum = typeof InvoiceAttributesValidationStatusEnum[keyof typeof InvoiceAttributesValidationStatusEnum];


/**
 * Check if a given object implements the InvoiceAttributes interface.
 */
export function instanceOfInvoiceAttributes(value: object): value is InvoiceAttributes {
    return true;
}

export function InvoiceAttributesFromJSON(json: any): InvoiceAttributes {
    return InvoiceAttributesFromJSONTyped(json, false);
}

export function InvoiceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'number': json['number'] == null ? undefined : json['number'],
        'issueDate': json['issue_date'] == null ? undefined : (new Date(json['issue_date'])),
        'dueDates': json['due_dates'] == null ? undefined : json['due_dates'],
        'paidAt': json['paid_at'] == null ? undefined : (new Date(json['paid_at'])),
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'paymentStatus': json['payment_status'] == null ? undefined : json['payment_status'],
        'validationStatus': json['validation_status'] == null ? undefined : json['validation_status'],
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
        'totalAmountWithoutTaxes': json['total_amount_without_taxes'] == null ? undefined : json['total_amount_without_taxes'],
        'vatAmount': json['vat_amount'] == null ? undefined : json['vat_amount'],
        'retentionAmount': json['retention_amount'] == null ? undefined : json['retention_amount'],
        'issuingName': json['issuing_name'] == null ? undefined : json['issuing_name'],
        'issuingTaxId': json['issuing_tax_id'] == null ? undefined : json['issuing_tax_id'],
        'issuingAddress': json['issuing_address'] == null ? undefined : json['issuing_address'],
        'issuingPhone': json['issuing_phone'] == null ? undefined : json['issuing_phone'],
        'issuingTown': json['issuing_town'] == null ? undefined : json['issuing_town'],
        'issuingZipCode': json['issuing_zip_code'] == null ? undefined : json['issuing_zip_code'],
        'issuingCountryCode': json['issuing_country_code'] == null ? undefined : json['issuing_country_code'],
        'recipientName': json['recipient_name'] == null ? undefined : json['recipient_name'],
        'recipientTaxId': json['recipient_tax_id'] == null ? undefined : json['recipient_tax_id'],
        'recipientAddress': json['recipient_address'] == null ? undefined : json['recipient_address'],
        'recipientPhone': json['recipient_phone'] == null ? undefined : json['recipient_phone'],
        'recipientTown': json['recipient_town'] == null ? undefined : json['recipient_town'],
        'recipientZipCode': json['recipient_zip_code'] == null ? undefined : json['recipient_zip_code'],
        'recipientCountryCode': json['recipient_country_code'] == null ? undefined : json['recipient_country_code'],
        'lastSentAt': json['last_sent_at'] == null ? undefined : json['last_sent_at'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'downloadPdfUrl': json['download_pdf_url'] == null ? undefined : json['download_pdf_url'],
        'ephemeralOpenDownloadPdfUrl': json['ephemeral_open_download_pdf_url'] == null ? undefined : json['ephemeral_open_download_pdf_url'],
    };
}

export function InvoiceAttributesToJSON(json: any): InvoiceAttributes {
    return InvoiceAttributesToJSONTyped(json, false);
}

export function InvoiceAttributesToJSONTyped(value?: Omit<InvoiceAttributes, 'payment_status'|'validation_status'|'total_amount'|'total_amount_without_taxes'|'vat_amount'|'retention_amount'|'issuing_name'|'issuing_tax_id'|'issuing_address'|'issuing_phone'|'issuing_town'|'issuing_zip_code'|'issuing_country_code'|'recipient_name'|'recipient_tax_id'|'recipient_address'|'recipient_phone'|'recipient_town'|'recipient_zip_code'|'recipient_country_code'|'download_pdf_url'|'ephemeral_open_download_pdf_url'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'number': value['number'],
        'issue_date': value['issueDate'] == null ? value['issueDate'] : value['issueDate'].toISOString().substring(0,10),
        'due_dates': value['dueDates'],
        'paid_at': value['paidAt'] == null ? value['paidAt'] : value['paidAt'].toISOString().substring(0,10),
        'payment_method': value['paymentMethod'],
        'last_sent_at': value['lastSentAt'],
        'tags': value['tags'],
        'notes': value['notes'],
    };
}

