/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceResponseIncludedInner } from './InvoiceResponseIncludedInner';
import {
    InvoiceResponseIncludedInnerFromJSON,
    InvoiceResponseIncludedInnerFromJSONTyped,
    InvoiceResponseIncludedInnerToJSON,
    InvoiceResponseIncludedInnerToJSONTyped,
} from './InvoiceResponseIncludedInner';
import type { InvoiceData } from './InvoiceData';
import {
    InvoiceDataFromJSON,
    InvoiceDataFromJSONTyped,
    InvoiceDataToJSON,
    InvoiceDataToJSONTyped,
} from './InvoiceData';

/**
 * 
 * @export
 * @interface InvoiceResponse
 */
export interface InvoiceResponse {
    /**
     * 
     * @type {InvoiceData}
     * @memberof InvoiceResponse
     */
    data?: InvoiceData;
    /**
     * 
     * @type {Array<InvoiceResponseIncludedInner>}
     * @memberof InvoiceResponse
     */
    included?: Array<InvoiceResponseIncludedInner>;
}

/**
 * Check if a given object implements the InvoiceResponse interface.
 */
export function instanceOfInvoiceResponse(value: object): value is InvoiceResponse {
    return true;
}

export function InvoiceResponseFromJSON(json: any): InvoiceResponse {
    return InvoiceResponseFromJSONTyped(json, false);
}

export function InvoiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : InvoiceDataFromJSON(json['data']),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(InvoiceResponseIncludedInnerFromJSON)),
    };
}

export function InvoiceResponseToJSON(json: any): InvoiceResponse {
    return InvoiceResponseToJSONTyped(json, false);
}

export function InvoiceResponseToJSONTyped(value?: InvoiceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvoiceDataToJSON(value['data']),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(InvoiceResponseIncludedInnerToJSON)),
    };
}

