/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsContactData } from './InvoiceRelationshipsContactData';
import {
    InvoiceRelationshipsContactDataFromJSON,
    InvoiceRelationshipsContactDataFromJSONTyped,
    InvoiceRelationshipsContactDataToJSON,
    InvoiceRelationshipsContactDataToJSONTyped,
} from './InvoiceRelationshipsContactData';

/**
 * 
 * @export
 * @interface InvoiceRelationshipsContact
 */
export interface InvoiceRelationshipsContact {
    /**
     * 
     * @type {InvoiceRelationshipsContactData}
     * @memberof InvoiceRelationshipsContact
     */
    data?: InvoiceRelationshipsContactData;
}

/**
 * Check if a given object implements the InvoiceRelationshipsContact interface.
 */
export function instanceOfInvoiceRelationshipsContact(value: object): value is InvoiceRelationshipsContact {
    return true;
}

export function InvoiceRelationshipsContactFromJSON(json: any): InvoiceRelationshipsContact {
    return InvoiceRelationshipsContactFromJSONTyped(json, false);
}

export function InvoiceRelationshipsContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsContact {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : InvoiceRelationshipsContactDataFromJSON(json['data']),
    };
}

export function InvoiceRelationshipsContactToJSON(json: any): InvoiceRelationshipsContact {
    return InvoiceRelationshipsContactToJSONTyped(json, false);
}

export function InvoiceRelationshipsContactToJSONTyped(value?: InvoiceRelationshipsContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvoiceRelationshipsContactDataToJSON(value['data']),
    };
}

