/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsAccountingSubcategoryData } from './InvoiceRelationshipsAccountingSubcategoryData';
import {
    InvoiceRelationshipsAccountingSubcategoryDataFromJSON,
    InvoiceRelationshipsAccountingSubcategoryDataFromJSONTyped,
    InvoiceRelationshipsAccountingSubcategoryDataToJSON,
    InvoiceRelationshipsAccountingSubcategoryDataToJSONTyped,
} from './InvoiceRelationshipsAccountingSubcategoryData';

/**
 * 
 * @export
 * @interface InvoiceRelationshipsAccountingSubcategory
 */
export interface InvoiceRelationshipsAccountingSubcategory {
    /**
     * 
     * @type {InvoiceRelationshipsAccountingSubcategoryData}
     * @memberof InvoiceRelationshipsAccountingSubcategory
     */
    data?: InvoiceRelationshipsAccountingSubcategoryData | null;
}

/**
 * Check if a given object implements the InvoiceRelationshipsAccountingSubcategory interface.
 */
export function instanceOfInvoiceRelationshipsAccountingSubcategory(value: object): value is InvoiceRelationshipsAccountingSubcategory {
    return true;
}

export function InvoiceRelationshipsAccountingSubcategoryFromJSON(json: any): InvoiceRelationshipsAccountingSubcategory {
    return InvoiceRelationshipsAccountingSubcategoryFromJSONTyped(json, false);
}

export function InvoiceRelationshipsAccountingSubcategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsAccountingSubcategory {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : InvoiceRelationshipsAccountingSubcategoryDataFromJSON(json['data']),
    };
}

export function InvoiceRelationshipsAccountingSubcategoryToJSON(json: any): InvoiceRelationshipsAccountingSubcategory {
    return InvoiceRelationshipsAccountingSubcategoryToJSONTyped(json, false);
}

export function InvoiceRelationshipsAccountingSubcategoryToJSONTyped(value?: InvoiceRelationshipsAccountingSubcategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvoiceRelationshipsAccountingSubcategoryDataToJSON(value['data']),
    };
}

