/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceRelationshipsAccountingSubcategoryData
 */
export interface InvoiceRelationshipsAccountingSubcategoryData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceRelationshipsAccountingSubcategoryData
     */
    id?: string;
    /**
     * 
     * @type {InvoiceRelationshipsAccountingSubcategoryDataTypeEnum}
     * @memberof InvoiceRelationshipsAccountingSubcategoryData
     */
    type?: InvoiceRelationshipsAccountingSubcategoryDataTypeEnum;
}


/**
 * @export
 */
export const InvoiceRelationshipsAccountingSubcategoryDataTypeEnum = {
    AccountingSubcategories: 'accounting_subcategories'
} as const;
export type InvoiceRelationshipsAccountingSubcategoryDataTypeEnum = typeof InvoiceRelationshipsAccountingSubcategoryDataTypeEnum[keyof typeof InvoiceRelationshipsAccountingSubcategoryDataTypeEnum];


/**
 * Check if a given object implements the InvoiceRelationshipsAccountingSubcategoryData interface.
 */
export function instanceOfInvoiceRelationshipsAccountingSubcategoryData(value: object): value is InvoiceRelationshipsAccountingSubcategoryData {
    return true;
}

export function InvoiceRelationshipsAccountingSubcategoryDataFromJSON(json: any): InvoiceRelationshipsAccountingSubcategoryData {
    return InvoiceRelationshipsAccountingSubcategoryDataFromJSONTyped(json, false);
}

export function InvoiceRelationshipsAccountingSubcategoryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsAccountingSubcategoryData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function InvoiceRelationshipsAccountingSubcategoryDataToJSON(json: any): InvoiceRelationshipsAccountingSubcategoryData {
    return InvoiceRelationshipsAccountingSubcategoryDataToJSONTyped(json, false);
}

export function InvoiceRelationshipsAccountingSubcategoryDataToJSONTyped(value?: InvoiceRelationshipsAccountingSubcategoryData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

