/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsItems } from './InvoiceRelationshipsItems';
import {
    InvoiceRelationshipsItemsFromJSON,
    InvoiceRelationshipsItemsFromJSONTyped,
    InvoiceRelationshipsItemsToJSON,
    InvoiceRelationshipsItemsToJSONTyped,
} from './InvoiceRelationshipsItems';
import type { InvoiceRelationshipsAmendedInvoice } from './InvoiceRelationshipsAmendedInvoice';
import {
    InvoiceRelationshipsAmendedInvoiceFromJSON,
    InvoiceRelationshipsAmendedInvoiceFromJSONTyped,
    InvoiceRelationshipsAmendedInvoiceToJSON,
    InvoiceRelationshipsAmendedInvoiceToJSONTyped,
} from './InvoiceRelationshipsAmendedInvoice';
import type { InvoiceRelationshipsAnalyticCategories } from './InvoiceRelationshipsAnalyticCategories';
import {
    InvoiceRelationshipsAnalyticCategoriesFromJSON,
    InvoiceRelationshipsAnalyticCategoriesFromJSONTyped,
    InvoiceRelationshipsAnalyticCategoriesToJSON,
    InvoiceRelationshipsAnalyticCategoriesToJSONTyped,
} from './InvoiceRelationshipsAnalyticCategories';
import type { InvoiceRelationshipsAmendingInvoices } from './InvoiceRelationshipsAmendingInvoices';
import {
    InvoiceRelationshipsAmendingInvoicesFromJSON,
    InvoiceRelationshipsAmendingInvoicesFromJSONTyped,
    InvoiceRelationshipsAmendingInvoicesToJSON,
    InvoiceRelationshipsAmendingInvoicesToJSONTyped,
} from './InvoiceRelationshipsAmendingInvoices';
import type { InvoiceRelationshipsAccountingSubcategory } from './InvoiceRelationshipsAccountingSubcategory';
import {
    InvoiceRelationshipsAccountingSubcategoryFromJSON,
    InvoiceRelationshipsAccountingSubcategoryFromJSONTyped,
    InvoiceRelationshipsAccountingSubcategoryToJSON,
    InvoiceRelationshipsAccountingSubcategoryToJSONTyped,
} from './InvoiceRelationshipsAccountingSubcategory';
import type { InvoiceRelationshipsContact } from './InvoiceRelationshipsContact';
import {
    InvoiceRelationshipsContactFromJSON,
    InvoiceRelationshipsContactFromJSONTyped,
    InvoiceRelationshipsContactToJSON,
    InvoiceRelationshipsContactToJSONTyped,
} from './InvoiceRelationshipsContact';
import type { InvoiceRelationshipsNumeration } from './InvoiceRelationshipsNumeration';
import {
    InvoiceRelationshipsNumerationFromJSON,
    InvoiceRelationshipsNumerationFromJSONTyped,
    InvoiceRelationshipsNumerationToJSON,
    InvoiceRelationshipsNumerationToJSONTyped,
} from './InvoiceRelationshipsNumeration';
import type { InvoiceRelationshipsAccountingCategory } from './InvoiceRelationshipsAccountingCategory';
import {
    InvoiceRelationshipsAccountingCategoryFromJSON,
    InvoiceRelationshipsAccountingCategoryFromJSONTyped,
    InvoiceRelationshipsAccountingCategoryToJSON,
    InvoiceRelationshipsAccountingCategoryToJSONTyped,
} from './InvoiceRelationshipsAccountingCategory';

/**
 * 
 * @export
 * @interface InvoiceRelationships
 */
export interface InvoiceRelationships {
    /**
     * 
     * @type {InvoiceRelationshipsContact}
     * @memberof InvoiceRelationships
     */
    contact?: InvoiceRelationshipsContact;
    /**
     * 
     * @type {InvoiceRelationshipsAccountingCategory}
     * @memberof InvoiceRelationships
     */
    accountingCategory?: InvoiceRelationshipsAccountingCategory;
    /**
     * 
     * @type {InvoiceRelationshipsAccountingSubcategory}
     * @memberof InvoiceRelationships
     */
    accountingSubcategory?: InvoiceRelationshipsAccountingSubcategory;
    /**
     * 
     * @type {InvoiceRelationshipsNumeration}
     * @memberof InvoiceRelationships
     */
    numeration?: InvoiceRelationshipsNumeration;
    /**
     * 
     * @type {InvoiceRelationshipsAnalyticCategories}
     * @memberof InvoiceRelationships
     */
    analyticCategories?: InvoiceRelationshipsAnalyticCategories;
    /**
     * 
     * @type {InvoiceRelationshipsItems}
     * @memberof InvoiceRelationships
     */
    items?: InvoiceRelationshipsItems;
    /**
     * 
     * @type {InvoiceRelationshipsAmendedInvoice}
     * @memberof InvoiceRelationships
     */
    amendedInvoice?: InvoiceRelationshipsAmendedInvoice;
    /**
     * 
     * @type {InvoiceRelationshipsAmendingInvoices}
     * @memberof InvoiceRelationships
     */
    amendingInvoices?: InvoiceRelationshipsAmendingInvoices;
}

/**
 * Check if a given object implements the InvoiceRelationships interface.
 */
export function instanceOfInvoiceRelationships(value: object): value is InvoiceRelationships {
    return true;
}

export function InvoiceRelationshipsFromJSON(json: any): InvoiceRelationships {
    return InvoiceRelationshipsFromJSONTyped(json, false);
}

export function InvoiceRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'contact': json['contact'] == null ? undefined : InvoiceRelationshipsContactFromJSON(json['contact']),
        'accountingCategory': json['accounting_category'] == null ? undefined : InvoiceRelationshipsAccountingCategoryFromJSON(json['accounting_category']),
        'accountingSubcategory': json['accounting_subcategory'] == null ? undefined : InvoiceRelationshipsAccountingSubcategoryFromJSON(json['accounting_subcategory']),
        'numeration': json['numeration'] == null ? undefined : InvoiceRelationshipsNumerationFromJSON(json['numeration']),
        'analyticCategories': json['analytic_categories'] == null ? undefined : InvoiceRelationshipsAnalyticCategoriesFromJSON(json['analytic_categories']),
        'items': json['items'] == null ? undefined : InvoiceRelationshipsItemsFromJSON(json['items']),
        'amendedInvoice': json['amended_invoice'] == null ? undefined : InvoiceRelationshipsAmendedInvoiceFromJSON(json['amended_invoice']),
        'amendingInvoices': json['amending_invoices'] == null ? undefined : InvoiceRelationshipsAmendingInvoicesFromJSON(json['amending_invoices']),
    };
}

export function InvoiceRelationshipsToJSON(json: any): InvoiceRelationships {
    return InvoiceRelationshipsToJSONTyped(json, false);
}

export function InvoiceRelationshipsToJSONTyped(value?: InvoiceRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact': InvoiceRelationshipsContactToJSON(value['contact']),
        'accounting_category': InvoiceRelationshipsAccountingCategoryToJSON(value['accountingCategory']),
        'accounting_subcategory': InvoiceRelationshipsAccountingSubcategoryToJSON(value['accountingSubcategory']),
        'numeration': InvoiceRelationshipsNumerationToJSON(value['numeration']),
        'analytic_categories': InvoiceRelationshipsAnalyticCategoriesToJSON(value['analyticCategories']),
        'items': InvoiceRelationshipsItemsToJSON(value['items']),
        'amended_invoice': InvoiceRelationshipsAmendedInvoiceToJSON(value['amendedInvoice']),
        'amending_invoices': InvoiceRelationshipsAmendingInvoicesToJSON(value['amendingInvoices']),
    };
}

