/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceCollectionAllOfIncluded } from './InvoiceCollectionAllOfIncluded';
import {
    InvoiceCollectionAllOfIncludedFromJSON,
    InvoiceCollectionAllOfIncludedFromJSONTyped,
    InvoiceCollectionAllOfIncludedToJSON,
    InvoiceCollectionAllOfIncludedToJSONTyped,
} from './InvoiceCollectionAllOfIncluded';
import type { InvoiceData } from './InvoiceData';
import {
    InvoiceDataFromJSON,
    InvoiceDataFromJSONTyped,
    InvoiceDataToJSON,
    InvoiceDataToJSONTyped,
} from './InvoiceData';
import type { PaginationMetaMeta } from './PaginationMetaMeta';
import {
    PaginationMetaMetaFromJSON,
    PaginationMetaMetaFromJSONTyped,
    PaginationMetaMetaToJSON,
    PaginationMetaMetaToJSONTyped,
} from './PaginationMetaMeta';

/**
 * 
 * @export
 * @interface InvoiceCollection
 */
export interface InvoiceCollection {
    /**
     * 
     * @type {PaginationMetaMeta}
     * @memberof InvoiceCollection
     */
    meta?: PaginationMetaMeta;
    /**
     * 
     * @type {Array<InvoiceData>}
     * @memberof InvoiceCollection
     */
    data?: Array<InvoiceData>;
    /**
     * 
     * @type {Array<InvoiceCollectionAllOfIncluded>}
     * @memberof InvoiceCollection
     */
    included?: Array<InvoiceCollectionAllOfIncluded>;
}

/**
 * Check if a given object implements the InvoiceCollection interface.
 */
export function instanceOfInvoiceCollection(value: object): value is InvoiceCollection {
    return true;
}

export function InvoiceCollectionFromJSON(json: any): InvoiceCollection {
    return InvoiceCollectionFromJSONTyped(json, false);
}

export function InvoiceCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PaginationMetaMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(InvoiceDataFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(InvoiceCollectionAllOfIncludedFromJSON)),
    };
}

export function InvoiceCollectionToJSON(json: any): InvoiceCollection {
    return InvoiceCollectionToJSONTyped(json, false);
}

export function InvoiceCollectionToJSONTyped(value?: InvoiceCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PaginationMetaMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(InvoiceDataToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(InvoiceCollectionAllOfIncludedToJSON)),
    };
}

