/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceAttributes } from './InvoiceAttributes';
import {
    InvoiceAttributesFromJSON,
    InvoiceAttributesFromJSONTyped,
    InvoiceAttributesToJSON,
    InvoiceAttributesToJSONTyped,
} from './InvoiceAttributes';
import type { InvoiceRelationships } from './InvoiceRelationships';
import {
    InvoiceRelationshipsFromJSON,
    InvoiceRelationshipsFromJSONTyped,
    InvoiceRelationshipsToJSON,
    InvoiceRelationshipsToJSONTyped,
} from './InvoiceRelationships';

/**
 * 
 * @export
 * @interface InvoiceCreateData
 */
export interface InvoiceCreateData {
    /**
     * 
     * @type {InvoiceCreateDataTypeEnum}
     * @memberof InvoiceCreateData
     */
    type: InvoiceCreateDataTypeEnum;
    /**
     * 
     * @type {InvoiceAttributes}
     * @memberof InvoiceCreateData
     */
    attributes?: InvoiceAttributes;
    /**
     * 
     * @type {InvoiceRelationships}
     * @memberof InvoiceCreateData
     */
    relationships?: InvoiceRelationships;
}


/**
 * @export
 */
export const InvoiceCreateDataTypeEnum = {
    Invoices: 'invoices'
} as const;
export type InvoiceCreateDataTypeEnum = typeof InvoiceCreateDataTypeEnum[keyof typeof InvoiceCreateDataTypeEnum];


/**
 * Check if a given object implements the InvoiceCreateData interface.
 */
export function instanceOfInvoiceCreateData(value: object): value is InvoiceCreateData {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function InvoiceCreateDataFromJSON(json: any): InvoiceCreateData {
    return InvoiceCreateDataFromJSONTyped(json, false);
}

export function InvoiceCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : InvoiceAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : InvoiceRelationshipsFromJSON(json['relationships']),
    };
}

export function InvoiceCreateDataToJSON(json: any): InvoiceCreateData {
    return InvoiceCreateDataToJSONTyped(json, false);
}

export function InvoiceCreateDataToJSONTyped(value?: InvoiceCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': InvoiceAttributesToJSON(value['attributes']),
        'relationships': InvoiceRelationshipsToJSON(value['relationships']),
    };
}

