/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsAccountingCategoryData } from './InvoiceRelationshipsAccountingCategoryData';
import {
    InvoiceRelationshipsAccountingCategoryDataFromJSON,
    InvoiceRelationshipsAccountingCategoryDataFromJSONTyped,
    InvoiceRelationshipsAccountingCategoryDataToJSON,
    InvoiceRelationshipsAccountingCategoryDataToJSONTyped,
} from './InvoiceRelationshipsAccountingCategoryData';

/**
 * 
 * @export
 * @interface InvoiceRelationshipsAccountingCategory
 */
export interface InvoiceRelationshipsAccountingCategory {
    /**
     * 
     * @type {InvoiceRelationshipsAccountingCategoryData}
     * @memberof InvoiceRelationshipsAccountingCategory
     */
    data?: InvoiceRelationshipsAccountingCategoryData | null;
}

/**
 * Check if a given object implements the InvoiceRelationshipsAccountingCategory interface.
 */
export function instanceOfInvoiceRelationshipsAccountingCategory(value: object): value is InvoiceRelationshipsAccountingCategory {
    return true;
}

export function InvoiceRelationshipsAccountingCategoryFromJSON(json: any): InvoiceRelationshipsAccountingCategory {
    return InvoiceRelationshipsAccountingCategoryFromJSONTyped(json, false);
}

export function InvoiceRelationshipsAccountingCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsAccountingCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : InvoiceRelationshipsAccountingCategoryDataFromJSON(json['data']),
    };
}

export function InvoiceRelationshipsAccountingCategoryToJSON(json: any): InvoiceRelationshipsAccountingCategory {
    return InvoiceRelationshipsAccountingCategoryToJSONTyped(json, false);
}

export function InvoiceRelationshipsAccountingCategoryToJSONTyped(value?: InvoiceRelationshipsAccountingCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvoiceRelationshipsAccountingCategoryDataToJSON(value['data']),
    };
}

