/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsNumerationData } from './InvoiceRelationshipsNumerationData';
import {
    InvoiceRelationshipsNumerationDataFromJSON,
    InvoiceRelationshipsNumerationDataFromJSONTyped,
    InvoiceRelationshipsNumerationDataToJSON,
    InvoiceRelationshipsNumerationDataToJSONTyped,
} from './InvoiceRelationshipsNumerationData';

/**
 * 
 * @export
 * @interface InvoiceRelationshipsNumeration
 */
export interface InvoiceRelationshipsNumeration {
    /**
     * 
     * @type {InvoiceRelationshipsNumerationData}
     * @memberof InvoiceRelationshipsNumeration
     */
    data?: InvoiceRelationshipsNumerationData | null;
}

/**
 * Check if a given object implements the InvoiceRelationshipsNumeration interface.
 */
export function instanceOfInvoiceRelationshipsNumeration(value: object): value is InvoiceRelationshipsNumeration {
    return true;
}

export function InvoiceRelationshipsNumerationFromJSON(json: any): InvoiceRelationshipsNumeration {
    return InvoiceRelationshipsNumerationFromJSONTyped(json, false);
}

export function InvoiceRelationshipsNumerationFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceRelationshipsNumeration {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : InvoiceRelationshipsNumerationDataFromJSON(json['data']),
    };
}

export function InvoiceRelationshipsNumerationToJSON(json: any): InvoiceRelationshipsNumeration {
    return InvoiceRelationshipsNumerationToJSONTyped(json, false);
}

export function InvoiceRelationshipsNumerationToJSONTyped(value?: InvoiceRelationshipsNumeration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvoiceRelationshipsNumerationDataToJSON(value['data']),
    };
}

