/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemAttributes } from './ItemAttributes';
import {
    ItemAttributesFromJSON,
    ItemAttributesFromJSONTyped,
    ItemAttributesToJSON,
    ItemAttributesToJSONTyped,
} from './ItemAttributes';

/**
 * 
 * @export
 * @interface ItemInvoiceCreate
 */
export interface ItemInvoiceCreate {
    /**
     * 
     * @type {ItemInvoiceCreateTypeEnum}
     * @memberof ItemInvoiceCreate
     */
    type?: ItemInvoiceCreateTypeEnum;
    /**
     * 
     * @type {ItemAttributes}
     * @memberof ItemInvoiceCreate
     */
    attributes?: ItemAttributes;
}


/**
 * @export
 */
export const ItemInvoiceCreateTypeEnum = {
    BookEntryItems: 'book_entry_items'
} as const;
export type ItemInvoiceCreateTypeEnum = typeof ItemInvoiceCreateTypeEnum[keyof typeof ItemInvoiceCreateTypeEnum];


/**
 * Check if a given object implements the ItemInvoiceCreate interface.
 */
export function instanceOfItemInvoiceCreate(value: object): value is ItemInvoiceCreate {
    return true;
}

export function ItemInvoiceCreateFromJSON(json: any): ItemInvoiceCreate {
    return ItemInvoiceCreateFromJSONTyped(json, false);
}

export function ItemInvoiceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemInvoiceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : ItemAttributesFromJSON(json['attributes']),
    };
}

export function ItemInvoiceCreateToJSON(json: any): ItemInvoiceCreate {
    return ItemInvoiceCreateToJSONTyped(json, false);
}

export function ItemInvoiceCreateToJSONTyped(value?: ItemInvoiceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': ItemAttributesToJSON(value['attributes']),
    };
}

