/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemAttributes } from './ItemAttributes';
import {
    ItemAttributesFromJSON,
    ItemAttributesFromJSONTyped,
    ItemAttributesToJSON,
    ItemAttributesToJSONTyped,
} from './ItemAttributes';

/**
 * 
 * @export
 * @interface ItemInvoiceUpdate
 */
export interface ItemInvoiceUpdate {
    /**
     * 
     * @type {string}
     * @memberof ItemInvoiceUpdate
     */
    id?: string;
    /**
     * 
     * @type {ItemInvoiceUpdateTypeEnum}
     * @memberof ItemInvoiceUpdate
     */
    type?: ItemInvoiceUpdateTypeEnum;
    /**
     * 
     * @type {ItemAttributes}
     * @memberof ItemInvoiceUpdate
     */
    attributes?: ItemAttributes;
}


/**
 * @export
 */
export const ItemInvoiceUpdateTypeEnum = {
    BookEntryItems: 'book_entry_items'
} as const;
export type ItemInvoiceUpdateTypeEnum = typeof ItemInvoiceUpdateTypeEnum[keyof typeof ItemInvoiceUpdateTypeEnum];


/**
 * Check if a given object implements the ItemInvoiceUpdate interface.
 */
export function instanceOfItemInvoiceUpdate(value: object): value is ItemInvoiceUpdate {
    return true;
}

export function ItemInvoiceUpdateFromJSON(json: any): ItemInvoiceUpdate {
    return ItemInvoiceUpdateFromJSONTyped(json, false);
}

export function ItemInvoiceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemInvoiceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : ItemAttributesFromJSON(json['attributes']),
    };
}

export function ItemInvoiceUpdateToJSON(json: any): ItemInvoiceUpdate {
    return ItemInvoiceUpdateToJSONTyped(json, false);
}

export function ItemInvoiceUpdateToJSONTyped(value?: ItemInvoiceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': ItemAttributesToJSON(value['attributes']),
    };
}

