/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemAttributes
 */
export interface ItemAttributes {
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    concept?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    unitaryAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    quantity?: string;
    /**
     * 
     * @type {ItemAttributesKindEnum}
     * @memberof ItemAttributes
     */
    kind?: ItemAttributesKindEnum;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    vatPercent?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    retentionPercent?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    discountPercent?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    deductibleVatPercent?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    deductibleExpensePercent?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    readonly vatAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    readonly retentionAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    readonly discountAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributes
     */
    readonly totalAmount?: string;
}


/**
 * @export
 */
export const ItemAttributesKindEnum = {
    Current: 'current',
    Assets: 'assets',
    Reimbursement: 'reimbursement'
} as const;
export type ItemAttributesKindEnum = typeof ItemAttributesKindEnum[keyof typeof ItemAttributesKindEnum];


/**
 * Check if a given object implements the ItemAttributes interface.
 */
export function instanceOfItemAttributes(value: object): value is ItemAttributes {
    return true;
}

export function ItemAttributesFromJSON(json: any): ItemAttributes {
    return ItemAttributesFromJSONTyped(json, false);
}

export function ItemAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'concept': json['concept'] == null ? undefined : json['concept'],
        'unitaryAmount': json['unitary_amount'] == null ? undefined : json['unitary_amount'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'vatPercent': json['vat_percent'] == null ? undefined : json['vat_percent'],
        'retentionPercent': json['retention_percent'] == null ? undefined : json['retention_percent'],
        'discountPercent': json['discount_percent'] == null ? undefined : json['discount_percent'],
        'deductibleVatPercent': json['deductible_vat_percent'] == null ? undefined : json['deductible_vat_percent'],
        'deductibleExpensePercent': json['deductible_expense_percent'] == null ? undefined : json['deductible_expense_percent'],
        'description': json['description'] == null ? undefined : json['description'],
        'vatAmount': json['vat_amount'] == null ? undefined : json['vat_amount'],
        'retentionAmount': json['retention_amount'] == null ? undefined : json['retention_amount'],
        'discountAmount': json['discount_amount'] == null ? undefined : json['discount_amount'],
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
    };
}

export function ItemAttributesToJSON(json: any): ItemAttributes {
    return ItemAttributesToJSONTyped(json, false);
}

export function ItemAttributesToJSONTyped(value?: Omit<ItemAttributes, 'vat_amount'|'retention_amount'|'discount_amount'|'total_amount'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'concept': value['concept'],
        'unitary_amount': value['unitaryAmount'],
        'quantity': value['quantity'],
        'kind': value['kind'],
        'vat_percent': value['vatPercent'],
        'retention_percent': value['retentionPercent'],
        'discount_percent': value['discountPercent'],
        'deductible_vat_percent': value['deductibleVatPercent'],
        'deductible_expense_percent': value['deductibleExpensePercent'],
        'description': value['description'],
    };
}

