/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumberingSeriesAttributes } from './NumberingSeriesAttributes';
import {
    NumberingSeriesAttributesFromJSON,
    NumberingSeriesAttributesFromJSONTyped,
    NumberingSeriesAttributesToJSON,
    NumberingSeriesAttributesToJSONTyped,
} from './NumberingSeriesAttributes';

/**
 * 
 * @export
 * @interface NumberingSeriesUpdateData
 */
export interface NumberingSeriesUpdateData {
    /**
     * 
     * @type {string}
     * @memberof NumberingSeriesUpdateData
     */
    id: string;
    /**
     * 
     * @type {NumberingSeriesUpdateDataTypeEnum}
     * @memberof NumberingSeriesUpdateData
     */
    type: NumberingSeriesUpdateDataTypeEnum;
    /**
     * 
     * @type {NumberingSeriesAttributes}
     * @memberof NumberingSeriesUpdateData
     */
    attributes?: NumberingSeriesAttributes;
}


/**
 * @export
 */
export const NumberingSeriesUpdateDataTypeEnum = {
    NumberingSeries: 'numbering_series'
} as const;
export type NumberingSeriesUpdateDataTypeEnum = typeof NumberingSeriesUpdateDataTypeEnum[keyof typeof NumberingSeriesUpdateDataTypeEnum];


/**
 * Check if a given object implements the NumberingSeriesUpdateData interface.
 */
export function instanceOfNumberingSeriesUpdateData(value: object): value is NumberingSeriesUpdateData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function NumberingSeriesUpdateDataFromJSON(json: any): NumberingSeriesUpdateData {
    return NumberingSeriesUpdateDataFromJSONTyped(json, false);
}

export function NumberingSeriesUpdateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSeriesUpdateData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : NumberingSeriesAttributesFromJSON(json['attributes']),
    };
}

export function NumberingSeriesUpdateDataToJSON(json: any): NumberingSeriesUpdateData {
    return NumberingSeriesUpdateDataToJSONTyped(json, false);
}

export function NumberingSeriesUpdateDataToJSONTyped(value?: NumberingSeriesUpdateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': NumberingSeriesAttributesToJSON(value['attributes']),
    };
}

