/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumberingSeriesAttributes } from './NumberingSeriesAttributes';
import {
    NumberingSeriesAttributesFromJSON,
    NumberingSeriesAttributesFromJSONTyped,
    NumberingSeriesAttributesToJSON,
    NumberingSeriesAttributesToJSONTyped,
} from './NumberingSeriesAttributes';

/**
 * 
 * @export
 * @interface NumberingSeriesData
 */
export interface NumberingSeriesData {
    /**
     * 
     * @type {string}
     * @memberof NumberingSeriesData
     */
    id?: string;
    /**
     * 
     * @type {NumberingSeriesDataTypeEnum}
     * @memberof NumberingSeriesData
     */
    type?: NumberingSeriesDataTypeEnum;
    /**
     * 
     * @type {NumberingSeriesAttributes}
     * @memberof NumberingSeriesData
     */
    attributes?: NumberingSeriesAttributes;
}


/**
 * @export
 */
export const NumberingSeriesDataTypeEnum = {
    NumberingSeries: 'numbering_series'
} as const;
export type NumberingSeriesDataTypeEnum = typeof NumberingSeriesDataTypeEnum[keyof typeof NumberingSeriesDataTypeEnum];


/**
 * Check if a given object implements the NumberingSeriesData interface.
 */
export function instanceOfNumberingSeriesData(value: object): value is NumberingSeriesData {
    return true;
}

export function NumberingSeriesDataFromJSON(json: any): NumberingSeriesData {
    return NumberingSeriesDataFromJSONTyped(json, false);
}

export function NumberingSeriesDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSeriesData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : NumberingSeriesAttributesFromJSON(json['attributes']),
    };
}

export function NumberingSeriesDataToJSON(json: any): NumberingSeriesData {
    return NumberingSeriesDataToJSONTyped(json, false);
}

export function NumberingSeriesDataToJSONTyped(value?: NumberingSeriesData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': NumberingSeriesAttributesToJSON(value['attributes']),
    };
}

