/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumberingSeriesAttributes } from './NumberingSeriesAttributes';
import {
    NumberingSeriesAttributesFromJSON,
    NumberingSeriesAttributesFromJSONTyped,
    NumberingSeriesAttributesToJSON,
    NumberingSeriesAttributesToJSONTyped,
} from './NumberingSeriesAttributes';

/**
 * 
 * @export
 * @interface NumberingSeriesCreateData
 */
export interface NumberingSeriesCreateData {
    /**
     * 
     * @type {NumberingSeriesCreateDataTypeEnum}
     * @memberof NumberingSeriesCreateData
     */
    type: NumberingSeriesCreateDataTypeEnum;
    /**
     * 
     * @type {NumberingSeriesAttributes}
     * @memberof NumberingSeriesCreateData
     */
    attributes: NumberingSeriesAttributes;
}


/**
 * @export
 */
export const NumberingSeriesCreateDataTypeEnum = {
    NumberingSeries: 'numbering_series'
} as const;
export type NumberingSeriesCreateDataTypeEnum = typeof NumberingSeriesCreateDataTypeEnum[keyof typeof NumberingSeriesCreateDataTypeEnum];


/**
 * Check if a given object implements the NumberingSeriesCreateData interface.
 */
export function instanceOfNumberingSeriesCreateData(value: object): value is NumberingSeriesCreateData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function NumberingSeriesCreateDataFromJSON(json: any): NumberingSeriesCreateData {
    return NumberingSeriesCreateDataFromJSONTyped(json, false);
}

export function NumberingSeriesCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSeriesCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': NumberingSeriesAttributesFromJSON(json['attributes']),
    };
}

export function NumberingSeriesCreateDataToJSON(json: any): NumberingSeriesCreateData {
    return NumberingSeriesCreateDataToJSONTyped(json, false);
}

export function NumberingSeriesCreateDataToJSONTyped(value?: NumberingSeriesCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': NumberingSeriesAttributesToJSON(value['attributes']),
    };
}

