/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumberingSeriesUpdateData } from './NumberingSeriesUpdateData';
import {
    NumberingSeriesUpdateDataFromJSON,
    NumberingSeriesUpdateDataFromJSONTyped,
    NumberingSeriesUpdateDataToJSON,
    NumberingSeriesUpdateDataToJSONTyped,
} from './NumberingSeriesUpdateData';

/**
 * 
 * @export
 * @interface NumberingSeriesUpdate
 */
export interface NumberingSeriesUpdate {
    /**
     * 
     * @type {NumberingSeriesUpdateData}
     * @memberof NumberingSeriesUpdate
     */
    data: NumberingSeriesUpdateData;
}

/**
 * Check if a given object implements the NumberingSeriesUpdate interface.
 */
export function instanceOfNumberingSeriesUpdate(value: object): value is NumberingSeriesUpdate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NumberingSeriesUpdateFromJSON(json: any): NumberingSeriesUpdate {
    return NumberingSeriesUpdateFromJSONTyped(json, false);
}

export function NumberingSeriesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSeriesUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NumberingSeriesUpdateDataFromJSON(json['data']),
    };
}

export function NumberingSeriesUpdateToJSON(json: any): NumberingSeriesUpdate {
    return NumberingSeriesUpdateToJSONTyped(json, false);
}

export function NumberingSeriesUpdateToJSONTyped(value?: NumberingSeriesUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NumberingSeriesUpdateDataToJSON(value['data']),
    };
}

