/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumberingSeriesData } from './NumberingSeriesData';
import {
    NumberingSeriesDataFromJSON,
    NumberingSeriesDataFromJSONTyped,
    NumberingSeriesDataToJSON,
    NumberingSeriesDataToJSONTyped,
} from './NumberingSeriesData';

/**
 * 
 * @export
 * @interface NumberingSeriesResponse
 */
export interface NumberingSeriesResponse {
    /**
     * 
     * @type {NumberingSeriesData}
     * @memberof NumberingSeriesResponse
     */
    data?: NumberingSeriesData;
}

/**
 * Check if a given object implements the NumberingSeriesResponse interface.
 */
export function instanceOfNumberingSeriesResponse(value: object): value is NumberingSeriesResponse {
    return true;
}

export function NumberingSeriesResponseFromJSON(json: any): NumberingSeriesResponse {
    return NumberingSeriesResponseFromJSONTyped(json, false);
}

export function NumberingSeriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSeriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : NumberingSeriesDataFromJSON(json['data']),
    };
}

export function NumberingSeriesResponseToJSON(json: any): NumberingSeriesResponse {
    return NumberingSeriesResponseToJSONTyped(json, false);
}

export function NumberingSeriesResponseToJSONTyped(value?: NumberingSeriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NumberingSeriesDataToJSON(value['data']),
    };
}

