/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NumberingSeriesAttributes
 */
export interface NumberingSeriesAttributes {
    /**
     * 
     * @type {string}
     * @memberof NumberingSeriesAttributes
     */
    prefix?: string;
    /**
     * 
     * @type {NumberingSeriesAttributesApplicableToEnum}
     * @memberof NumberingSeriesAttributes
     */
    applicableTo?: NumberingSeriesAttributesApplicableToEnum;
    /**
     * 
     * @type {boolean}
     * @memberof NumberingSeriesAttributes
     */
    _default?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NumberingSeriesAttributes
     */
    amending?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NumberingSeriesAttributes
     */
    readonly deletable?: boolean;
}


/**
 * @export
 */
export const NumberingSeriesAttributesApplicableToEnum = {
    Invoices: 'invoices',
    Tickets: 'tickets'
} as const;
export type NumberingSeriesAttributesApplicableToEnum = typeof NumberingSeriesAttributesApplicableToEnum[keyof typeof NumberingSeriesAttributesApplicableToEnum];


/**
 * Check if a given object implements the NumberingSeriesAttributes interface.
 */
export function instanceOfNumberingSeriesAttributes(value: object): value is NumberingSeriesAttributes {
    return true;
}

export function NumberingSeriesAttributesFromJSON(json: any): NumberingSeriesAttributes {
    return NumberingSeriesAttributesFromJSONTyped(json, false);
}

export function NumberingSeriesAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSeriesAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'applicableTo': json['applicable_to'] == null ? undefined : json['applicable_to'],
        '_default': json['default'] == null ? undefined : json['default'],
        'amending': json['amending'] == null ? undefined : json['amending'],
        'deletable': json['deletable'] == null ? undefined : json['deletable'],
    };
}

export function NumberingSeriesAttributesToJSON(json: any): NumberingSeriesAttributes {
    return NumberingSeriesAttributesToJSONTyped(json, false);
}

export function NumberingSeriesAttributesToJSONTyped(value?: Omit<NumberingSeriesAttributes, 'deletable'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prefix': value['prefix'],
        'applicable_to': value['applicableTo'],
        'default': value['_default'],
        'amending': value['amending'],
    };
}

