/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumberingSeriesData } from './NumberingSeriesData';
import {
    NumberingSeriesDataFromJSON,
    NumberingSeriesDataFromJSONTyped,
    NumberingSeriesDataToJSON,
    NumberingSeriesDataToJSONTyped,
} from './NumberingSeriesData';

/**
 * 
 * @export
 * @interface NumberingSeriesCollection
 */
export interface NumberingSeriesCollection {
    /**
     * 
     * @type {Array<NumberingSeriesData>}
     * @memberof NumberingSeriesCollection
     */
    data?: Array<NumberingSeriesData>;
}

/**
 * Check if a given object implements the NumberingSeriesCollection interface.
 */
export function instanceOfNumberingSeriesCollection(value: object): value is NumberingSeriesCollection {
    return true;
}

export function NumberingSeriesCollectionFromJSON(json: any): NumberingSeriesCollection {
    return NumberingSeriesCollectionFromJSONTyped(json, false);
}

export function NumberingSeriesCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSeriesCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(NumberingSeriesDataFromJSON)),
    };
}

export function NumberingSeriesCollectionToJSON(json: any): NumberingSeriesCollection {
    return NumberingSeriesCollectionToJSONTyped(json, false);
}

export function NumberingSeriesCollectionToJSONTyped(value?: NumberingSeriesCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(NumberingSeriesDataToJSON)),
    };
}

