/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumberingSeriesCreateData } from './NumberingSeriesCreateData';
import {
    NumberingSeriesCreateDataFromJSON,
    NumberingSeriesCreateDataFromJSONTyped,
    NumberingSeriesCreateDataToJSON,
    NumberingSeriesCreateDataToJSONTyped,
} from './NumberingSeriesCreateData';

/**
 * 
 * @export
 * @interface NumberingSeriesCreate
 */
export interface NumberingSeriesCreate {
    /**
     * 
     * @type {NumberingSeriesCreateData}
     * @memberof NumberingSeriesCreate
     */
    data: NumberingSeriesCreateData;
}

/**
 * Check if a given object implements the NumberingSeriesCreate interface.
 */
export function instanceOfNumberingSeriesCreate(value: object): value is NumberingSeriesCreate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NumberingSeriesCreateFromJSON(json: any): NumberingSeriesCreate {
    return NumberingSeriesCreateFromJSONTyped(json, false);
}

export function NumberingSeriesCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSeriesCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NumberingSeriesCreateDataFromJSON(json['data']),
    };
}

export function NumberingSeriesCreateToJSON(json: any): NumberingSeriesCreate {
    return NumberingSeriesCreateToJSONTyped(json, false);
}

export function NumberingSeriesCreateToJSONTyped(value?: NumberingSeriesCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NumberingSeriesCreateDataToJSON(value['data']),
    };
}

