/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMetaMetaPaginationInfo
 */
export interface PaginationMetaMetaPaginationInfo {
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaMetaPaginationInfo
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaMetaPaginationInfo
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaMetaPaginationInfo
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the PaginationMetaMetaPaginationInfo interface.
 */
export function instanceOfPaginationMetaMetaPaginationInfo(value: object): value is PaginationMetaMetaPaginationInfo {
    return true;
}

export function PaginationMetaMetaPaginationInfoFromJSON(json: any): PaginationMetaMetaPaginationInfo {
    return PaginationMetaMetaPaginationInfoFromJSONTyped(json, false);
}

export function PaginationMetaMetaPaginationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMetaMetaPaginationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'totalResults': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function PaginationMetaMetaPaginationInfoToJSON(json: any): PaginationMetaMetaPaginationInfo {
    return PaginationMetaMetaPaginationInfoToJSONTyped(json, false);
}

export function PaginationMetaMetaPaginationInfoToJSONTyped(value?: PaginationMetaMetaPaginationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_pages': value['totalPages'],
        'current_page': value['currentPage'],
        'total_results': value['totalResults'],
    };
}

