/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMetaMetaPaginationInfo } from './PaginationMetaMetaPaginationInfo';
import {
    PaginationMetaMetaPaginationInfoFromJSON,
    PaginationMetaMetaPaginationInfoFromJSONTyped,
    PaginationMetaMetaPaginationInfoToJSON,
    PaginationMetaMetaPaginationInfoToJSONTyped,
} from './PaginationMetaMetaPaginationInfo';

/**
 * 
 * @export
 * @interface PaginationMetaMeta
 */
export interface PaginationMetaMeta {
    /**
     * 
     * @type {PaginationMetaMetaPaginationInfo}
     * @memberof PaginationMetaMeta
     */
    paginationInfo?: PaginationMetaMetaPaginationInfo;
}

/**
 * Check if a given object implements the PaginationMetaMeta interface.
 */
export function instanceOfPaginationMetaMeta(value: object): value is PaginationMetaMeta {
    return true;
}

export function PaginationMetaMetaFromJSON(json: any): PaginationMetaMeta {
    return PaginationMetaMetaFromJSONTyped(json, false);
}

export function PaginationMetaMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMetaMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'paginationInfo': json['pagination_info'] == null ? undefined : PaginationMetaMetaPaginationInfoFromJSON(json['pagination_info']),
    };
}

export function PaginationMetaMetaToJSON(json: any): PaginationMetaMeta {
    return PaginationMetaMetaToJSONTyped(json, false);
}

export function PaginationMetaMetaToJSONTyped(value?: PaginationMetaMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination_info': PaginationMetaMetaPaginationInfoToJSON(value['paginationInfo']),
    };
}

