/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMetaMeta } from './PaginationMetaMeta';
import {
    PaginationMetaMetaFromJSON,
    PaginationMetaMetaFromJSONTyped,
    PaginationMetaMetaToJSON,
    PaginationMetaMetaToJSONTyped,
} from './PaginationMetaMeta';
import type { PaysheetData } from './PaysheetData';
import {
    PaysheetDataFromJSON,
    PaysheetDataFromJSONTyped,
    PaysheetDataToJSON,
    PaysheetDataToJSONTyped,
} from './PaysheetData';

/**
 * 
 * @export
 * @interface PaysheetCollection
 */
export interface PaysheetCollection {
    /**
     * 
     * @type {PaginationMetaMeta}
     * @memberof PaysheetCollection
     */
    meta?: PaginationMetaMeta;
    /**
     * 
     * @type {Array<PaysheetData>}
     * @memberof PaysheetCollection
     */
    data?: Array<PaysheetData>;
}

/**
 * Check if a given object implements the PaysheetCollection interface.
 */
export function instanceOfPaysheetCollection(value: object): value is PaysheetCollection {
    return true;
}

export function PaysheetCollectionFromJSON(json: any): PaysheetCollection {
    return PaysheetCollectionFromJSONTyped(json, false);
}

export function PaysheetCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PaginationMetaMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PaysheetDataFromJSON)),
    };
}

export function PaysheetCollectionToJSON(json: any): PaysheetCollection {
    return PaysheetCollectionToJSONTyped(json, false);
}

export function PaysheetCollectionToJSONTyped(value?: PaysheetCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PaginationMetaMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PaysheetDataToJSON)),
    };
}

