/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaysheetAttributes
 */
export interface PaysheetAttributes {
    /**
     * 
     * @type {PaysheetAttributesKindEnum}
     * @memberof PaysheetAttributes
     */
    readonly kind?: PaysheetAttributesKindEnum;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    number?: string;
    /**
     * 
     * @type {Date}
     * @memberof PaysheetAttributes
     */
    issueDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PaysheetAttributes
     */
    paidAt?: Date | null;
    /**
     * 
     * @type {PaysheetAttributesPaymentMethodEnum}
     * @memberof PaysheetAttributes
     */
    paymentMethod?: PaysheetAttributesPaymentMethodEnum;
    /**
     * 
     * @type {PaysheetAttributesPaymentStatusEnum}
     * @memberof PaysheetAttributes
     */
    readonly paymentStatus?: PaysheetAttributesPaymentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    netPay?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly grossPay?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    employeeSsAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    employeeRetention?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    companySsAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly issuingName?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly issuingTaxId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly issuingAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly issuingPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly issuingTown?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly issuingZipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly issuingCountryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly recipientName?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly recipientTaxId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly recipientAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly recipientPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly recipientTown?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly recipientZipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    readonly recipientCountryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PaysheetAttributes
     */
    tags?: string;
}


/**
 * @export
 */
export const PaysheetAttributesKindEnum = {
    Expenses: 'expenses'
} as const;
export type PaysheetAttributesKindEnum = typeof PaysheetAttributesKindEnum[keyof typeof PaysheetAttributesKindEnum];

/**
 * @export
 */
export const PaysheetAttributesPaymentMethodEnum = {
    Cash: 'cash',
    BankTransfer: 'bank_transfer',
    BankCard: 'bank_card',
    DirectDebit: 'direct_debit',
    Paypal: 'paypal',
    Check: 'check',
    Factoring: 'factoring'
} as const;
export type PaysheetAttributesPaymentMethodEnum = typeof PaysheetAttributesPaymentMethodEnum[keyof typeof PaysheetAttributesPaymentMethodEnum];

/**
 * @export
 */
export const PaysheetAttributesPaymentStatusEnum = {
    Paid: 'paid',
    Unpaid: 'unpaid',
    Due: 'due',
    Pending: 'pending'
} as const;
export type PaysheetAttributesPaymentStatusEnum = typeof PaysheetAttributesPaymentStatusEnum[keyof typeof PaysheetAttributesPaymentStatusEnum];


/**
 * Check if a given object implements the PaysheetAttributes interface.
 */
export function instanceOfPaysheetAttributes(value: object): value is PaysheetAttributes {
    return true;
}

export function PaysheetAttributesFromJSON(json: any): PaysheetAttributes {
    return PaysheetAttributesFromJSONTyped(json, false);
}

export function PaysheetAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'number': json['number'] == null ? undefined : json['number'],
        'issueDate': json['issue_date'] == null ? undefined : (new Date(json['issue_date'])),
        'paidAt': json['paid_at'] == null ? undefined : (new Date(json['paid_at'])),
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'paymentStatus': json['payment_status'] == null ? undefined : json['payment_status'],
        'netPay': json['net_pay'] == null ? undefined : json['net_pay'],
        'grossPay': json['gross_pay'] == null ? undefined : json['gross_pay'],
        'employeeSsAmount': json['employee_ss_amount'] == null ? undefined : json['employee_ss_amount'],
        'employeeRetention': json['employee_retention'] == null ? undefined : json['employee_retention'],
        'companySsAmount': json['company_ss_amount'] == null ? undefined : json['company_ss_amount'],
        'issuingName': json['issuing_name'] == null ? undefined : json['issuing_name'],
        'issuingTaxId': json['issuing_tax_id'] == null ? undefined : json['issuing_tax_id'],
        'issuingAddress': json['issuing_address'] == null ? undefined : json['issuing_address'],
        'issuingPhone': json['issuing_phone'] == null ? undefined : json['issuing_phone'],
        'issuingTown': json['issuing_town'] == null ? undefined : json['issuing_town'],
        'issuingZipCode': json['issuing_zip_code'] == null ? undefined : json['issuing_zip_code'],
        'issuingCountryCode': json['issuing_country_code'] == null ? undefined : json['issuing_country_code'],
        'recipientName': json['recipient_name'] == null ? undefined : json['recipient_name'],
        'recipientTaxId': json['recipient_tax_id'] == null ? undefined : json['recipient_tax_id'],
        'recipientAddress': json['recipient_address'] == null ? undefined : json['recipient_address'],
        'recipientPhone': json['recipient_phone'] == null ? undefined : json['recipient_phone'],
        'recipientTown': json['recipient_town'] == null ? undefined : json['recipient_town'],
        'recipientZipCode': json['recipient_zip_code'] == null ? undefined : json['recipient_zip_code'],
        'recipientCountryCode': json['recipient_country_code'] == null ? undefined : json['recipient_country_code'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function PaysheetAttributesToJSON(json: any): PaysheetAttributes {
    return PaysheetAttributesToJSONTyped(json, false);
}

export function PaysheetAttributesToJSONTyped(value?: Omit<PaysheetAttributes, 'kind'|'payment_status'|'gross_pay'|'issuing_name'|'issuing_tax_id'|'issuing_address'|'issuing_phone'|'issuing_town'|'issuing_zip_code'|'issuing_country_code'|'recipient_name'|'recipient_tax_id'|'recipient_address'|'recipient_phone'|'recipient_town'|'recipient_zip_code'|'recipient_country_code'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'issue_date': value['issueDate'] == null ? value['issueDate'] : value['issueDate'].toISOString().substring(0,10),
        'paid_at': value['paidAt'] == null ? value['paidAt'] : value['paidAt'].toISOString().substring(0,10),
        'payment_method': value['paymentMethod'],
        'net_pay': value['netPay'],
        'employee_ss_amount': value['employeeSsAmount'],
        'employee_retention': value['employeeRetention'],
        'company_ss_amount': value['companySsAmount'],
        'tags': value['tags'],
    };
}

