/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsAnalyticCategories } from './InvoiceRelationshipsAnalyticCategories';
import {
    InvoiceRelationshipsAnalyticCategoriesFromJSON,
    InvoiceRelationshipsAnalyticCategoriesFromJSONTyped,
    InvoiceRelationshipsAnalyticCategoriesToJSON,
    InvoiceRelationshipsAnalyticCategoriesToJSONTyped,
} from './InvoiceRelationshipsAnalyticCategories';
import type { InvoiceRelationshipsAccountingSubcategory } from './InvoiceRelationshipsAccountingSubcategory';
import {
    InvoiceRelationshipsAccountingSubcategoryFromJSON,
    InvoiceRelationshipsAccountingSubcategoryFromJSONTyped,
    InvoiceRelationshipsAccountingSubcategoryToJSON,
    InvoiceRelationshipsAccountingSubcategoryToJSONTyped,
} from './InvoiceRelationshipsAccountingSubcategory';
import type { InvoiceRelationshipsContact } from './InvoiceRelationshipsContact';
import {
    InvoiceRelationshipsContactFromJSON,
    InvoiceRelationshipsContactFromJSONTyped,
    InvoiceRelationshipsContactToJSON,
    InvoiceRelationshipsContactToJSONTyped,
} from './InvoiceRelationshipsContact';
import type { InvoiceRelationshipsNumeration } from './InvoiceRelationshipsNumeration';
import {
    InvoiceRelationshipsNumerationFromJSON,
    InvoiceRelationshipsNumerationFromJSONTyped,
    InvoiceRelationshipsNumerationToJSON,
    InvoiceRelationshipsNumerationToJSONTyped,
} from './InvoiceRelationshipsNumeration';
import type { InvoiceRelationshipsAccountingCategory } from './InvoiceRelationshipsAccountingCategory';
import {
    InvoiceRelationshipsAccountingCategoryFromJSON,
    InvoiceRelationshipsAccountingCategoryFromJSONTyped,
    InvoiceRelationshipsAccountingCategoryToJSON,
    InvoiceRelationshipsAccountingCategoryToJSONTyped,
} from './InvoiceRelationshipsAccountingCategory';

/**
 * 
 * @export
 * @interface PaysheetRelationships
 */
export interface PaysheetRelationships {
    /**
     * 
     * @type {InvoiceRelationshipsContact}
     * @memberof PaysheetRelationships
     */
    contact?: InvoiceRelationshipsContact;
    /**
     * 
     * @type {InvoiceRelationshipsAccountingCategory}
     * @memberof PaysheetRelationships
     */
    accountingCategory?: InvoiceRelationshipsAccountingCategory;
    /**
     * 
     * @type {InvoiceRelationshipsAccountingSubcategory}
     * @memberof PaysheetRelationships
     */
    accountingSubcategory?: InvoiceRelationshipsAccountingSubcategory;
    /**
     * 
     * @type {InvoiceRelationshipsNumeration}
     * @memberof PaysheetRelationships
     */
    numeration?: InvoiceRelationshipsNumeration;
    /**
     * 
     * @type {InvoiceRelationshipsAnalyticCategories}
     * @memberof PaysheetRelationships
     */
    analyticCategories?: InvoiceRelationshipsAnalyticCategories;
}

/**
 * Check if a given object implements the PaysheetRelationships interface.
 */
export function instanceOfPaysheetRelationships(value: object): value is PaysheetRelationships {
    return true;
}

export function PaysheetRelationshipsFromJSON(json: any): PaysheetRelationships {
    return PaysheetRelationshipsFromJSONTyped(json, false);
}

export function PaysheetRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'contact': json['contact'] == null ? undefined : InvoiceRelationshipsContactFromJSON(json['contact']),
        'accountingCategory': json['accounting_category'] == null ? undefined : InvoiceRelationshipsAccountingCategoryFromJSON(json['accounting_category']),
        'accountingSubcategory': json['accounting_subcategory'] == null ? undefined : InvoiceRelationshipsAccountingSubcategoryFromJSON(json['accounting_subcategory']),
        'numeration': json['numeration'] == null ? undefined : InvoiceRelationshipsNumerationFromJSON(json['numeration']),
        'analyticCategories': json['analytic_categories'] == null ? undefined : InvoiceRelationshipsAnalyticCategoriesFromJSON(json['analytic_categories']),
    };
}

export function PaysheetRelationshipsToJSON(json: any): PaysheetRelationships {
    return PaysheetRelationshipsToJSONTyped(json, false);
}

export function PaysheetRelationshipsToJSONTyped(value?: PaysheetRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact': InvoiceRelationshipsContactToJSON(value['contact']),
        'accounting_category': InvoiceRelationshipsAccountingCategoryToJSON(value['accountingCategory']),
        'accounting_subcategory': InvoiceRelationshipsAccountingSubcategoryToJSON(value['accountingSubcategory']),
        'numeration': InvoiceRelationshipsNumerationToJSON(value['numeration']),
        'analytic_categories': InvoiceRelationshipsAnalyticCategoriesToJSON(value['analyticCategories']),
    };
}

