/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaysheetData } from './PaysheetData';
import {
    PaysheetDataFromJSON,
    PaysheetDataFromJSONTyped,
    PaysheetDataToJSON,
    PaysheetDataToJSONTyped,
} from './PaysheetData';

/**
 * 
 * @export
 * @interface PaysheetResponse
 */
export interface PaysheetResponse {
    /**
     * 
     * @type {PaysheetData}
     * @memberof PaysheetResponse
     */
    data?: PaysheetData;
}

/**
 * Check if a given object implements the PaysheetResponse interface.
 */
export function instanceOfPaysheetResponse(value: object): value is PaysheetResponse {
    return true;
}

export function PaysheetResponseFromJSON(json: any): PaysheetResponse {
    return PaysheetResponseFromJSONTyped(json, false);
}

export function PaysheetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PaysheetDataFromJSON(json['data']),
    };
}

export function PaysheetResponseToJSON(json: any): PaysheetResponse {
    return PaysheetResponseToJSONTyped(json, false);
}

export function PaysheetResponseToJSONTyped(value?: PaysheetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaysheetDataToJSON(value['data']),
    };
}

