/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaysheetAttributes } from './PaysheetAttributes';
import {
    PaysheetAttributesFromJSON,
    PaysheetAttributesFromJSONTyped,
    PaysheetAttributesToJSON,
    PaysheetAttributesToJSONTyped,
} from './PaysheetAttributes';
import type { PaysheetRelationships } from './PaysheetRelationships';
import {
    PaysheetRelationshipsFromJSON,
    PaysheetRelationshipsFromJSONTyped,
    PaysheetRelationshipsToJSON,
    PaysheetRelationshipsToJSONTyped,
} from './PaysheetRelationships';

/**
 * 
 * @export
 * @interface PaysheetData
 */
export interface PaysheetData {
    /**
     * 
     * @type {string}
     * @memberof PaysheetData
     */
    id?: string;
    /**
     * 
     * @type {PaysheetDataTypeEnum}
     * @memberof PaysheetData
     */
    type?: PaysheetDataTypeEnum;
    /**
     * 
     * @type {PaysheetAttributes}
     * @memberof PaysheetData
     */
    attributes?: PaysheetAttributes;
    /**
     * 
     * @type {PaysheetRelationships}
     * @memberof PaysheetData
     */
    relationships?: PaysheetRelationships;
}


/**
 * @export
 */
export const PaysheetDataTypeEnum = {
    Paysheets: 'paysheets'
} as const;
export type PaysheetDataTypeEnum = typeof PaysheetDataTypeEnum[keyof typeof PaysheetDataTypeEnum];


/**
 * Check if a given object implements the PaysheetData interface.
 */
export function instanceOfPaysheetData(value: object): value is PaysheetData {
    return true;
}

export function PaysheetDataFromJSON(json: any): PaysheetData {
    return PaysheetDataFromJSONTyped(json, false);
}

export function PaysheetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : PaysheetAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : PaysheetRelationshipsFromJSON(json['relationships']),
    };
}

export function PaysheetDataToJSON(json: any): PaysheetData {
    return PaysheetDataToJSONTyped(json, false);
}

export function PaysheetDataToJSONTyped(value?: PaysheetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': PaysheetAttributesToJSON(value['attributes']),
        'relationships': PaysheetRelationshipsToJSON(value['relationships']),
    };
}

