/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaysheetAttributes } from './PaysheetAttributes';
import {
    PaysheetAttributesFromJSON,
    PaysheetAttributesFromJSONTyped,
    PaysheetAttributesToJSON,
    PaysheetAttributesToJSONTyped,
} from './PaysheetAttributes';
import type { PaysheetRelationships } from './PaysheetRelationships';
import {
    PaysheetRelationshipsFromJSON,
    PaysheetRelationshipsFromJSONTyped,
    PaysheetRelationshipsToJSON,
    PaysheetRelationshipsToJSONTyped,
} from './PaysheetRelationships';

/**
 * 
 * @export
 * @interface PaysheetCreateData
 */
export interface PaysheetCreateData {
    /**
     * 
     * @type {PaysheetCreateDataTypeEnum}
     * @memberof PaysheetCreateData
     */
    type: PaysheetCreateDataTypeEnum;
    /**
     * 
     * @type {PaysheetAttributes}
     * @memberof PaysheetCreateData
     */
    attributes?: PaysheetAttributes;
    /**
     * 
     * @type {PaysheetRelationships}
     * @memberof PaysheetCreateData
     */
    relationships?: PaysheetRelationships;
}


/**
 * @export
 */
export const PaysheetCreateDataTypeEnum = {
    Paysheets: 'paysheets'
} as const;
export type PaysheetCreateDataTypeEnum = typeof PaysheetCreateDataTypeEnum[keyof typeof PaysheetCreateDataTypeEnum];


/**
 * Check if a given object implements the PaysheetCreateData interface.
 */
export function instanceOfPaysheetCreateData(value: object): value is PaysheetCreateData {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PaysheetCreateDataFromJSON(json: any): PaysheetCreateData {
    return PaysheetCreateDataFromJSONTyped(json, false);
}

export function PaysheetCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : PaysheetAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : PaysheetRelationshipsFromJSON(json['relationships']),
    };
}

export function PaysheetCreateDataToJSON(json: any): PaysheetCreateData {
    return PaysheetCreateDataToJSONTyped(json, false);
}

export function PaysheetCreateDataToJSONTyped(value?: PaysheetCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': PaysheetAttributesToJSON(value['attributes']),
        'relationships': PaysheetRelationshipsToJSON(value['relationships']),
    };
}

