/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaysheetAttributes } from './PaysheetAttributes';
import {
    PaysheetAttributesFromJSON,
    PaysheetAttributesFromJSONTyped,
    PaysheetAttributesToJSON,
    PaysheetAttributesToJSONTyped,
} from './PaysheetAttributes';
import type { PaysheetRelationships } from './PaysheetRelationships';
import {
    PaysheetRelationshipsFromJSON,
    PaysheetRelationshipsFromJSONTyped,
    PaysheetRelationshipsToJSON,
    PaysheetRelationshipsToJSONTyped,
} from './PaysheetRelationships';

/**
 * 
 * @export
 * @interface PaysheetUpdateData
 */
export interface PaysheetUpdateData {
    /**
     * 
     * @type {string}
     * @memberof PaysheetUpdateData
     */
    id: string;
    /**
     * 
     * @type {PaysheetUpdateDataTypeEnum}
     * @memberof PaysheetUpdateData
     */
    type: PaysheetUpdateDataTypeEnum;
    /**
     * 
     * @type {PaysheetAttributes}
     * @memberof PaysheetUpdateData
     */
    attributes?: PaysheetAttributes;
    /**
     * 
     * @type {PaysheetRelationships}
     * @memberof PaysheetUpdateData
     */
    relationships?: PaysheetRelationships;
}


/**
 * @export
 */
export const PaysheetUpdateDataTypeEnum = {
    Paysheets: 'paysheets'
} as const;
export type PaysheetUpdateDataTypeEnum = typeof PaysheetUpdateDataTypeEnum[keyof typeof PaysheetUpdateDataTypeEnum];


/**
 * Check if a given object implements the PaysheetUpdateData interface.
 */
export function instanceOfPaysheetUpdateData(value: object): value is PaysheetUpdateData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PaysheetUpdateDataFromJSON(json: any): PaysheetUpdateData {
    return PaysheetUpdateDataFromJSONTyped(json, false);
}

export function PaysheetUpdateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetUpdateData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : PaysheetAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : PaysheetRelationshipsFromJSON(json['relationships']),
    };
}

export function PaysheetUpdateDataToJSON(json: any): PaysheetUpdateData {
    return PaysheetUpdateDataToJSONTyped(json, false);
}

export function PaysheetUpdateDataToJSONTyped(value?: PaysheetUpdateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': PaysheetAttributesToJSON(value['attributes']),
        'relationships': PaysheetRelationshipsToJSON(value['relationships']),
    };
}

