/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaysheetUpdateData } from './PaysheetUpdateData';
import {
    PaysheetUpdateDataFromJSON,
    PaysheetUpdateDataFromJSONTyped,
    PaysheetUpdateDataToJSON,
    PaysheetUpdateDataToJSONTyped,
} from './PaysheetUpdateData';

/**
 * 
 * @export
 * @interface PaysheetUpdate
 */
export interface PaysheetUpdate {
    /**
     * 
     * @type {PaysheetUpdateData}
     * @memberof PaysheetUpdate
     */
    data: PaysheetUpdateData;
}

/**
 * Check if a given object implements the PaysheetUpdate interface.
 */
export function instanceOfPaysheetUpdate(value: object): value is PaysheetUpdate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaysheetUpdateFromJSON(json: any): PaysheetUpdate {
    return PaysheetUpdateFromJSONTyped(json, false);
}

export function PaysheetUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PaysheetUpdateDataFromJSON(json['data']),
    };
}

export function PaysheetUpdateToJSON(json: any): PaysheetUpdate {
    return PaysheetUpdateToJSONTyped(json, false);
}

export function PaysheetUpdateToJSONTyped(value?: PaysheetUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaysheetUpdateDataToJSON(value['data']),
    };
}

