/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaysheetCreateData } from './PaysheetCreateData';
import {
    PaysheetCreateDataFromJSON,
    PaysheetCreateDataFromJSONTyped,
    PaysheetCreateDataToJSON,
    PaysheetCreateDataToJSONTyped,
} from './PaysheetCreateData';

/**
 * 
 * @export
 * @interface PaysheetCreate
 */
export interface PaysheetCreate {
    /**
     * 
     * @type {PaysheetCreateData}
     * @memberof PaysheetCreate
     */
    data: PaysheetCreateData;
}

/**
 * Check if a given object implements the PaysheetCreate interface.
 */
export function instanceOfPaysheetCreate(value: object): value is PaysheetCreate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaysheetCreateFromJSON(json: any): PaysheetCreate {
    return PaysheetCreateFromJSONTyped(json, false);
}

export function PaysheetCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaysheetCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PaysheetCreateDataFromJSON(json['data']),
    };
}

export function PaysheetCreateToJSON(json: any): PaysheetCreate {
    return PaysheetCreateToJSONTyped(json, false);
}

export function PaysheetCreateToJSONTyped(value?: PaysheetCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaysheetCreateDataToJSON(value['data']),
    };
}

