/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketAttributes
 */
export interface TicketAttributes {
    /**
     * 
     * @type {TicketAttributesKindEnum}
     * @memberof TicketAttributes
     */
    kind?: TicketAttributesKindEnum;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    number?: string;
    /**
     * 
     * @type {Date}
     * @memberof TicketAttributes
     */
    issueDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketAttributes
     */
    paidAt?: Date | null;
    /**
     * 
     * @type {TicketAttributesPaymentMethodEnum}
     * @memberof TicketAttributes
     */
    paymentMethod?: TicketAttributesPaymentMethodEnum;
    /**
     * 
     * @type {TicketAttributesPaymentStatusEnum}
     * @memberof TicketAttributes
     */
    readonly paymentStatus?: TicketAttributesPaymentStatusEnum;
    /**
     * 
     * @type {TicketAttributesValidationStatusEnum}
     * @memberof TicketAttributes
     */
    readonly validationStatus?: TicketAttributesValidationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly totalAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly totalAmountWithoutTaxes?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly vatAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    issuingName?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly issuingTaxId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly issuingAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly issuingPhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly issuingTown?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly issuingZipCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly issuingCountryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    recipientName?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly recipientTaxId?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly recipientAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly recipientPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly recipientTown?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly recipientZipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly recipientCountryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAttributes
     */
    readonly downloadPdfUrl?: string;
}


/**
 * @export
 */
export const TicketAttributesKindEnum = {
    Income: 'income',
    Expenses: 'expenses'
} as const;
export type TicketAttributesKindEnum = typeof TicketAttributesKindEnum[keyof typeof TicketAttributesKindEnum];

/**
 * @export
 */
export const TicketAttributesPaymentMethodEnum = {
    Cash: 'cash',
    BankTransfer: 'bank_transfer',
    BankCard: 'bank_card',
    DirectDebit: 'direct_debit',
    Paypal: 'paypal',
    Check: 'check',
    Factoring: 'factoring'
} as const;
export type TicketAttributesPaymentMethodEnum = typeof TicketAttributesPaymentMethodEnum[keyof typeof TicketAttributesPaymentMethodEnum];

/**
 * @export
 */
export const TicketAttributesPaymentStatusEnum = {
    Paid: 'paid',
    Unpaid: 'unpaid',
    Due: 'due',
    Pending: 'pending'
} as const;
export type TicketAttributesPaymentStatusEnum = typeof TicketAttributesPaymentStatusEnum[keyof typeof TicketAttributesPaymentStatusEnum];

/**
 * @export
 */
export const TicketAttributesValidationStatusEnum = {
    Pending: 'pending',
    Verified: 'verified'
} as const;
export type TicketAttributesValidationStatusEnum = typeof TicketAttributesValidationStatusEnum[keyof typeof TicketAttributesValidationStatusEnum];


/**
 * Check if a given object implements the TicketAttributes interface.
 */
export function instanceOfTicketAttributes(value: object): value is TicketAttributes {
    return true;
}

export function TicketAttributesFromJSON(json: any): TicketAttributes {
    return TicketAttributesFromJSONTyped(json, false);
}

export function TicketAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'number': json['number'] == null ? undefined : json['number'],
        'issueDate': json['issue_date'] == null ? undefined : (new Date(json['issue_date'])),
        'paidAt': json['paid_at'] == null ? undefined : (new Date(json['paid_at'])),
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'paymentStatus': json['payment_status'] == null ? undefined : json['payment_status'],
        'validationStatus': json['validation_status'] == null ? undefined : json['validation_status'],
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
        'totalAmountWithoutTaxes': json['total_amount_without_taxes'] == null ? undefined : json['total_amount_without_taxes'],
        'vatAmount': json['vat_amount'] == null ? undefined : json['vat_amount'],
        'issuingName': json['issuing_name'] == null ? undefined : json['issuing_name'],
        'issuingTaxId': json['issuing_tax_id'] == null ? undefined : json['issuing_tax_id'],
        'issuingAddress': json['issuing_address'] == null ? undefined : json['issuing_address'],
        'issuingPhone': json['issuing_phone'] == null ? undefined : json['issuing_phone'],
        'issuingTown': json['issuing_town'] == null ? undefined : json['issuing_town'],
        'issuingZipCode': json['issuing_zip_code'] == null ? undefined : json['issuing_zip_code'],
        'issuingCountryCode': json['issuing_country_code'] == null ? undefined : json['issuing_country_code'],
        'recipientName': json['recipient_name'] == null ? undefined : json['recipient_name'],
        'recipientTaxId': json['recipient_tax_id'] == null ? undefined : json['recipient_tax_id'],
        'recipientAddress': json['recipient_address'] == null ? undefined : json['recipient_address'],
        'recipientPhone': json['recipient_phone'] == null ? undefined : json['recipient_phone'],
        'recipientTown': json['recipient_town'] == null ? undefined : json['recipient_town'],
        'recipientZipCode': json['recipient_zip_code'] == null ? undefined : json['recipient_zip_code'],
        'recipientCountryCode': json['recipient_country_code'] == null ? undefined : json['recipient_country_code'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'downloadPdfUrl': json['download_pdf_url'] == null ? undefined : json['download_pdf_url'],
    };
}

export function TicketAttributesToJSON(json: any): TicketAttributes {
    return TicketAttributesToJSONTyped(json, false);
}

export function TicketAttributesToJSONTyped(value?: Omit<TicketAttributes, 'payment_status'|'validation_status'|'total_amount'|'total_amount_without_taxes'|'vat_amount'|'issuing_tax_id'|'issuing_address'|'issuing_phone'|'issuing_town'|'issuing_zip_code'|'issuing_country_code'|'recipient_tax_id'|'recipient_address'|'recipient_phone'|'recipient_town'|'recipient_zip_code'|'recipient_country_code'|'download_pdf_url'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'number': value['number'],
        'issue_date': value['issueDate'] == null ? value['issueDate'] : value['issueDate'].toISOString().substring(0,10),
        'paid_at': value['paidAt'] == null ? value['paidAt'] : value['paidAt'].toISOString().substring(0,10),
        'payment_method': value['paymentMethod'],
        'issuing_name': value['issuingName'],
        'recipient_name': value['recipientName'],
        'tags': value['tags'],
        'notes': value['notes'],
    };
}

