/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceRelationshipsItems } from './InvoiceRelationshipsItems';
import {
    InvoiceRelationshipsItemsFromJSON,
    InvoiceRelationshipsItemsFromJSONTyped,
    InvoiceRelationshipsItemsToJSON,
    InvoiceRelationshipsItemsToJSONTyped,
} from './InvoiceRelationshipsItems';
import type { TicketRelationshipsAmendingTickets } from './TicketRelationshipsAmendingTickets';
import {
    TicketRelationshipsAmendingTicketsFromJSON,
    TicketRelationshipsAmendingTicketsFromJSONTyped,
    TicketRelationshipsAmendingTicketsToJSON,
    TicketRelationshipsAmendingTicketsToJSONTyped,
} from './TicketRelationshipsAmendingTickets';
import type { InvoiceRelationshipsAnalyticCategories } from './InvoiceRelationshipsAnalyticCategories';
import {
    InvoiceRelationshipsAnalyticCategoriesFromJSON,
    InvoiceRelationshipsAnalyticCategoriesFromJSONTyped,
    InvoiceRelationshipsAnalyticCategoriesToJSON,
    InvoiceRelationshipsAnalyticCategoriesToJSONTyped,
} from './InvoiceRelationshipsAnalyticCategories';
import type { InvoiceRelationshipsAccountingSubcategory } from './InvoiceRelationshipsAccountingSubcategory';
import {
    InvoiceRelationshipsAccountingSubcategoryFromJSON,
    InvoiceRelationshipsAccountingSubcategoryFromJSONTyped,
    InvoiceRelationshipsAccountingSubcategoryToJSON,
    InvoiceRelationshipsAccountingSubcategoryToJSONTyped,
} from './InvoiceRelationshipsAccountingSubcategory';
import type { TicketRelationshipsAmendedTicket } from './TicketRelationshipsAmendedTicket';
import {
    TicketRelationshipsAmendedTicketFromJSON,
    TicketRelationshipsAmendedTicketFromJSONTyped,
    TicketRelationshipsAmendedTicketToJSON,
    TicketRelationshipsAmendedTicketToJSONTyped,
} from './TicketRelationshipsAmendedTicket';
import type { InvoiceRelationshipsNumeration } from './InvoiceRelationshipsNumeration';
import {
    InvoiceRelationshipsNumerationFromJSON,
    InvoiceRelationshipsNumerationFromJSONTyped,
    InvoiceRelationshipsNumerationToJSON,
    InvoiceRelationshipsNumerationToJSONTyped,
} from './InvoiceRelationshipsNumeration';
import type { InvoiceRelationshipsAccountingCategory } from './InvoiceRelationshipsAccountingCategory';
import {
    InvoiceRelationshipsAccountingCategoryFromJSON,
    InvoiceRelationshipsAccountingCategoryFromJSONTyped,
    InvoiceRelationshipsAccountingCategoryToJSON,
    InvoiceRelationshipsAccountingCategoryToJSONTyped,
} from './InvoiceRelationshipsAccountingCategory';

/**
 * 
 * @export
 * @interface TicketRelationships
 */
export interface TicketRelationships {
    /**
     * 
     * @type {InvoiceRelationshipsAccountingCategory}
     * @memberof TicketRelationships
     */
    accountingCategory?: InvoiceRelationshipsAccountingCategory;
    /**
     * 
     * @type {InvoiceRelationshipsAccountingSubcategory}
     * @memberof TicketRelationships
     */
    accountingSubcategory?: InvoiceRelationshipsAccountingSubcategory;
    /**
     * 
     * @type {InvoiceRelationshipsNumeration}
     * @memberof TicketRelationships
     */
    numeration?: InvoiceRelationshipsNumeration;
    /**
     * 
     * @type {InvoiceRelationshipsAnalyticCategories}
     * @memberof TicketRelationships
     */
    analyticCategories?: InvoiceRelationshipsAnalyticCategories;
    /**
     * 
     * @type {InvoiceRelationshipsItems}
     * @memberof TicketRelationships
     */
    items?: InvoiceRelationshipsItems;
    /**
     * 
     * @type {TicketRelationshipsAmendedTicket}
     * @memberof TicketRelationships
     */
    amendedTicket?: TicketRelationshipsAmendedTicket;
    /**
     * 
     * @type {TicketRelationshipsAmendingTickets}
     * @memberof TicketRelationships
     */
    amendingTickets?: TicketRelationshipsAmendingTickets;
}

/**
 * Check if a given object implements the TicketRelationships interface.
 */
export function instanceOfTicketRelationships(value: object): value is TicketRelationships {
    return true;
}

export function TicketRelationshipsFromJSON(json: any): TicketRelationships {
    return TicketRelationshipsFromJSONTyped(json, false);
}

export function TicketRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'accountingCategory': json['accounting_category'] == null ? undefined : InvoiceRelationshipsAccountingCategoryFromJSON(json['accounting_category']),
        'accountingSubcategory': json['accounting_subcategory'] == null ? undefined : InvoiceRelationshipsAccountingSubcategoryFromJSON(json['accounting_subcategory']),
        'numeration': json['numeration'] == null ? undefined : InvoiceRelationshipsNumerationFromJSON(json['numeration']),
        'analyticCategories': json['analytic_categories'] == null ? undefined : InvoiceRelationshipsAnalyticCategoriesFromJSON(json['analytic_categories']),
        'items': json['items'] == null ? undefined : InvoiceRelationshipsItemsFromJSON(json['items']),
        'amendedTicket': json['amended_ticket'] == null ? undefined : TicketRelationshipsAmendedTicketFromJSON(json['amended_ticket']),
        'amendingTickets': json['amending_tickets'] == null ? undefined : TicketRelationshipsAmendingTicketsFromJSON(json['amending_tickets']),
    };
}

export function TicketRelationshipsToJSON(json: any): TicketRelationships {
    return TicketRelationshipsToJSONTyped(json, false);
}

export function TicketRelationshipsToJSONTyped(value?: TicketRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounting_category': InvoiceRelationshipsAccountingCategoryToJSON(value['accountingCategory']),
        'accounting_subcategory': InvoiceRelationshipsAccountingSubcategoryToJSON(value['accountingSubcategory']),
        'numeration': InvoiceRelationshipsNumerationToJSON(value['numeration']),
        'analytic_categories': InvoiceRelationshipsAnalyticCategoriesToJSON(value['analyticCategories']),
        'items': InvoiceRelationshipsItemsToJSON(value['items']),
        'amended_ticket': TicketRelationshipsAmendedTicketToJSON(value['amendedTicket']),
        'amending_tickets': TicketRelationshipsAmendingTicketsToJSON(value['amendingTickets']),
    };
}

