/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketData } from './TicketData';
import {
    TicketDataFromJSON,
    TicketDataFromJSONTyped,
    TicketDataToJSON,
    TicketDataToJSONTyped,
} from './TicketData';
import type { InvoiceCollectionAllOfIncluded } from './InvoiceCollectionAllOfIncluded';
import {
    InvoiceCollectionAllOfIncludedFromJSON,
    InvoiceCollectionAllOfIncludedFromJSONTyped,
    InvoiceCollectionAllOfIncludedToJSON,
    InvoiceCollectionAllOfIncludedToJSONTyped,
} from './InvoiceCollectionAllOfIncluded';
import type { PaginationMetaMeta } from './PaginationMetaMeta';
import {
    PaginationMetaMetaFromJSON,
    PaginationMetaMetaFromJSONTyped,
    PaginationMetaMetaToJSON,
    PaginationMetaMetaToJSONTyped,
} from './PaginationMetaMeta';

/**
 * 
 * @export
 * @interface TicketCollection
 */
export interface TicketCollection {
    /**
     * 
     * @type {PaginationMetaMeta}
     * @memberof TicketCollection
     */
    meta?: PaginationMetaMeta;
    /**
     * 
     * @type {Array<TicketData>}
     * @memberof TicketCollection
     */
    data?: Array<TicketData>;
    /**
     * 
     * @type {Array<InvoiceCollectionAllOfIncluded>}
     * @memberof TicketCollection
     */
    included?: Array<InvoiceCollectionAllOfIncluded>;
}

/**
 * Check if a given object implements the TicketCollection interface.
 */
export function instanceOfTicketCollection(value: object): value is TicketCollection {
    return true;
}

export function TicketCollectionFromJSON(json: any): TicketCollection {
    return TicketCollectionFromJSONTyped(json, false);
}

export function TicketCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PaginationMetaMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TicketDataFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(InvoiceCollectionAllOfIncludedFromJSON)),
    };
}

export function TicketCollectionToJSON(json: any): TicketCollection {
    return TicketCollectionToJSONTyped(json, false);
}

export function TicketCollectionToJSONTyped(value?: TicketCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PaginationMetaMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TicketDataToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(InvoiceCollectionAllOfIncludedToJSON)),
    };
}

