/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketAttributes } from './TicketAttributes';
import {
    TicketAttributesFromJSON,
    TicketAttributesFromJSONTyped,
    TicketAttributesToJSON,
    TicketAttributesToJSONTyped,
} from './TicketAttributes';
import type { TicketRelationships } from './TicketRelationships';
import {
    TicketRelationshipsFromJSON,
    TicketRelationshipsFromJSONTyped,
    TicketRelationshipsToJSON,
    TicketRelationshipsToJSONTyped,
} from './TicketRelationships';

/**
 * 
 * @export
 * @interface TicketData
 */
export interface TicketData {
    /**
     * 
     * @type {string}
     * @memberof TicketData
     */
    id?: string;
    /**
     * 
     * @type {TicketDataTypeEnum}
     * @memberof TicketData
     */
    type?: TicketDataTypeEnum;
    /**
     * 
     * @type {TicketAttributes}
     * @memberof TicketData
     */
    attributes?: TicketAttributes;
    /**
     * 
     * @type {TicketRelationships}
     * @memberof TicketData
     */
    relationships?: TicketRelationships;
}


/**
 * @export
 */
export const TicketDataTypeEnum = {
    Tickets: 'tickets'
} as const;
export type TicketDataTypeEnum = typeof TicketDataTypeEnum[keyof typeof TicketDataTypeEnum];


/**
 * Check if a given object implements the TicketData interface.
 */
export function instanceOfTicketData(value: object): value is TicketData {
    return true;
}

export function TicketDataFromJSON(json: any): TicketData {
    return TicketDataFromJSONTyped(json, false);
}

export function TicketDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : TicketAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : TicketRelationshipsFromJSON(json['relationships']),
    };
}

export function TicketDataToJSON(json: any): TicketData {
    return TicketDataToJSONTyped(json, false);
}

export function TicketDataToJSONTyped(value?: TicketData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': TicketAttributesToJSON(value['attributes']),
        'relationships': TicketRelationshipsToJSON(value['relationships']),
    };
}

