/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketAttributes } from './TicketAttributes';
import {
    TicketAttributesFromJSON,
    TicketAttributesFromJSONTyped,
    TicketAttributesToJSON,
    TicketAttributesToJSONTyped,
} from './TicketAttributes';
import type { TicketRelationships } from './TicketRelationships';
import {
    TicketRelationshipsFromJSON,
    TicketRelationshipsFromJSONTyped,
    TicketRelationshipsToJSON,
    TicketRelationshipsToJSONTyped,
} from './TicketRelationships';

/**
 * 
 * @export
 * @interface TicketUpdateData
 */
export interface TicketUpdateData {
    /**
     * 
     * @type {string}
     * @memberof TicketUpdateData
     */
    id: string;
    /**
     * 
     * @type {TicketUpdateDataTypeEnum}
     * @memberof TicketUpdateData
     */
    type: TicketUpdateDataTypeEnum;
    /**
     * 
     * @type {TicketAttributes}
     * @memberof TicketUpdateData
     */
    attributes?: TicketAttributes;
    /**
     * 
     * @type {TicketRelationships}
     * @memberof TicketUpdateData
     */
    relationships?: TicketRelationships;
}


/**
 * @export
 */
export const TicketUpdateDataTypeEnum = {
    Tickets: 'tickets'
} as const;
export type TicketUpdateDataTypeEnum = typeof TicketUpdateDataTypeEnum[keyof typeof TicketUpdateDataTypeEnum];


/**
 * Check if a given object implements the TicketUpdateData interface.
 */
export function instanceOfTicketUpdateData(value: object): value is TicketUpdateData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TicketUpdateDataFromJSON(json: any): TicketUpdateData {
    return TicketUpdateDataFromJSONTyped(json, false);
}

export function TicketUpdateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketUpdateData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : TicketAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : TicketRelationshipsFromJSON(json['relationships']),
    };
}

export function TicketUpdateDataToJSON(json: any): TicketUpdateData {
    return TicketUpdateDataToJSONTyped(json, false);
}

export function TicketUpdateDataToJSONTyped(value?: TicketUpdateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': TicketAttributesToJSON(value['attributes']),
        'relationships': TicketRelationshipsToJSON(value['relationships']),
    };
}

