/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketRelationshipsAmendedTicketData } from './TicketRelationshipsAmendedTicketData';
import {
    TicketRelationshipsAmendedTicketDataFromJSON,
    TicketRelationshipsAmendedTicketDataFromJSONTyped,
    TicketRelationshipsAmendedTicketDataToJSON,
    TicketRelationshipsAmendedTicketDataToJSONTyped,
} from './TicketRelationshipsAmendedTicketData';

/**
 * 
 * @export
 * @interface TicketRelationshipsAmendedTicket
 */
export interface TicketRelationshipsAmendedTicket {
    /**
     * 
     * @type {TicketRelationshipsAmendedTicketData}
     * @memberof TicketRelationshipsAmendedTicket
     */
    data?: TicketRelationshipsAmendedTicketData | null;
}

/**
 * Check if a given object implements the TicketRelationshipsAmendedTicket interface.
 */
export function instanceOfTicketRelationshipsAmendedTicket(value: object): value is TicketRelationshipsAmendedTicket {
    return true;
}

export function TicketRelationshipsAmendedTicketFromJSON(json: any): TicketRelationshipsAmendedTicket {
    return TicketRelationshipsAmendedTicketFromJSONTyped(json, false);
}

export function TicketRelationshipsAmendedTicketFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketRelationshipsAmendedTicket {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : TicketRelationshipsAmendedTicketDataFromJSON(json['data']),
    };
}

export function TicketRelationshipsAmendedTicketToJSON(json: any): TicketRelationshipsAmendedTicket {
    return TicketRelationshipsAmendedTicketToJSONTyped(json, false);
}

export function TicketRelationshipsAmendedTicketToJSONTyped(value?: TicketRelationshipsAmendedTicket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TicketRelationshipsAmendedTicketDataToJSON(value['data']),
    };
}

