/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketRelationshipsAmendingTicketsDataInner } from './TicketRelationshipsAmendingTicketsDataInner';
import {
    TicketRelationshipsAmendingTicketsDataInnerFromJSON,
    TicketRelationshipsAmendingTicketsDataInnerFromJSONTyped,
    TicketRelationshipsAmendingTicketsDataInnerToJSON,
    TicketRelationshipsAmendingTicketsDataInnerToJSONTyped,
} from './TicketRelationshipsAmendingTicketsDataInner';

/**
 * 
 * @export
 * @interface TicketRelationshipsAmendingTickets
 */
export interface TicketRelationshipsAmendingTickets {
    /**
     * 
     * @type {Array<TicketRelationshipsAmendingTicketsDataInner>}
     * @memberof TicketRelationshipsAmendingTickets
     */
    data?: Array<TicketRelationshipsAmendingTicketsDataInner>;
}

/**
 * Check if a given object implements the TicketRelationshipsAmendingTickets interface.
 */
export function instanceOfTicketRelationshipsAmendingTickets(value: object): value is TicketRelationshipsAmendingTickets {
    return true;
}

export function TicketRelationshipsAmendingTicketsFromJSON(json: any): TicketRelationshipsAmendingTickets {
    return TicketRelationshipsAmendingTicketsFromJSONTyped(json, false);
}

export function TicketRelationshipsAmendingTicketsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketRelationshipsAmendingTickets {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TicketRelationshipsAmendingTicketsDataInnerFromJSON)),
    };
}

export function TicketRelationshipsAmendingTicketsToJSON(json: any): TicketRelationshipsAmendingTickets {
    return TicketRelationshipsAmendingTicketsToJSONTyped(json, false);
}

export function TicketRelationshipsAmendingTicketsToJSONTyped(value?: TicketRelationshipsAmendingTickets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TicketRelationshipsAmendingTicketsDataInnerToJSON)),
    };
}

