/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketData } from './TicketData';
import {
    TicketDataFromJSON,
    TicketDataFromJSONTyped,
    TicketDataToJSON,
    TicketDataToJSONTyped,
} from './TicketData';
import type { InvoiceResponseIncludedInner } from './InvoiceResponseIncludedInner';
import {
    InvoiceResponseIncludedInnerFromJSON,
    InvoiceResponseIncludedInnerFromJSONTyped,
    InvoiceResponseIncludedInnerToJSON,
    InvoiceResponseIncludedInnerToJSONTyped,
} from './InvoiceResponseIncludedInner';

/**
 * 
 * @export
 * @interface TicketResponse
 */
export interface TicketResponse {
    /**
     * 
     * @type {TicketData}
     * @memberof TicketResponse
     */
    data?: TicketData;
    /**
     * 
     * @type {Array<InvoiceResponseIncludedInner>}
     * @memberof TicketResponse
     */
    included?: Array<InvoiceResponseIncludedInner>;
}

/**
 * Check if a given object implements the TicketResponse interface.
 */
export function instanceOfTicketResponse(value: object): value is TicketResponse {
    return true;
}

export function TicketResponseFromJSON(json: any): TicketResponse {
    return TicketResponseFromJSONTyped(json, false);
}

export function TicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : TicketDataFromJSON(json['data']),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(InvoiceResponseIncludedInnerFromJSON)),
    };
}

export function TicketResponseToJSON(json: any): TicketResponse {
    return TicketResponseToJSONTyped(json, false);
}

export function TicketResponseToJSONTyped(value?: TicketResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TicketDataToJSON(value['data']),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(InvoiceResponseIncludedInnerToJSON)),
    };
}

