/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketUpdateData } from './TicketUpdateData';
import {
    TicketUpdateDataFromJSON,
    TicketUpdateDataFromJSONTyped,
    TicketUpdateDataToJSON,
    TicketUpdateDataToJSONTyped,
} from './TicketUpdateData';

/**
 * 
 * @export
 * @interface TicketUpdate
 */
export interface TicketUpdate {
    /**
     * 
     * @type {TicketUpdateData}
     * @memberof TicketUpdate
     */
    data: TicketUpdateData;
}

/**
 * Check if a given object implements the TicketUpdate interface.
 */
export function instanceOfTicketUpdate(value: object): value is TicketUpdate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TicketUpdateFromJSON(json: any): TicketUpdate {
    return TicketUpdateFromJSONTyped(json, false);
}

export function TicketUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TicketUpdateDataFromJSON(json['data']),
    };
}

export function TicketUpdateToJSON(json: any): TicketUpdate {
    return TicketUpdateToJSONTyped(json, false);
}

export function TicketUpdateToJSONTyped(value?: TicketUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TicketUpdateDataToJSON(value['data']),
    };
}

