/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketCreateData } from './TicketCreateData';
import {
    TicketCreateDataFromJSON,
    TicketCreateDataFromJSONTyped,
    TicketCreateDataToJSON,
    TicketCreateDataToJSONTyped,
} from './TicketCreateData';

/**
 * 
 * @export
 * @interface TicketCreate
 */
export interface TicketCreate {
    /**
     * 
     * @type {TicketCreateData}
     * @memberof TicketCreate
     */
    data: TicketCreateData;
}

/**
 * Check if a given object implements the TicketCreate interface.
 */
export function instanceOfTicketCreate(value: object): value is TicketCreate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TicketCreateFromJSON(json: any): TicketCreate {
    return TicketCreateFromJSONTyped(json, false);
}

export function TicketCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TicketCreateDataFromJSON(json['data']),
    };
}

export function TicketCreateToJSON(json: any): TicketCreate {
    return TicketCreateToJSONTyped(json, false);
}

export function TicketCreateToJSONTyped(value?: TicketCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TicketCreateDataToJSON(value['data']),
    };
}

