/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketRelationshipsAmendingTicketsDataInner
 */
export interface TicketRelationshipsAmendingTicketsDataInner {
    /**
     * 
     * @type {string}
     * @memberof TicketRelationshipsAmendingTicketsDataInner
     */
    id?: string;
    /**
     * 
     * @type {TicketRelationshipsAmendingTicketsDataInnerTypeEnum}
     * @memberof TicketRelationshipsAmendingTicketsDataInner
     */
    type?: TicketRelationshipsAmendingTicketsDataInnerTypeEnum;
}


/**
 * @export
 */
export const TicketRelationshipsAmendingTicketsDataInnerTypeEnum = {
    Tickets: 'tickets'
} as const;
export type TicketRelationshipsAmendingTicketsDataInnerTypeEnum = typeof TicketRelationshipsAmendingTicketsDataInnerTypeEnum[keyof typeof TicketRelationshipsAmendingTicketsDataInnerTypeEnum];


/**
 * Check if a given object implements the TicketRelationshipsAmendingTicketsDataInner interface.
 */
export function instanceOfTicketRelationshipsAmendingTicketsDataInner(value: object): value is TicketRelationshipsAmendingTicketsDataInner {
    return true;
}

export function TicketRelationshipsAmendingTicketsDataInnerFromJSON(json: any): TicketRelationshipsAmendingTicketsDataInner {
    return TicketRelationshipsAmendingTicketsDataInnerFromJSONTyped(json, false);
}

export function TicketRelationshipsAmendingTicketsDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketRelationshipsAmendingTicketsDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function TicketRelationshipsAmendingTicketsDataInnerToJSON(json: any): TicketRelationshipsAmendingTicketsDataInner {
    return TicketRelationshipsAmendingTicketsDataInnerToJSONTyped(json, false);
}

export function TicketRelationshipsAmendingTicketsDataInnerToJSONTyped(value?: TicketRelationshipsAmendingTicketsDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

