/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketAttributes } from './TicketAttributes';
import {
    TicketAttributesFromJSON,
    TicketAttributesFromJSONTyped,
    TicketAttributesToJSON,
    TicketAttributesToJSONTyped,
} from './TicketAttributes';
import type { TicketRelationships } from './TicketRelationships';
import {
    TicketRelationshipsFromJSON,
    TicketRelationshipsFromJSONTyped,
    TicketRelationshipsToJSON,
    TicketRelationshipsToJSONTyped,
} from './TicketRelationships';

/**
 * 
 * @export
 * @interface TicketCreateData
 */
export interface TicketCreateData {
    /**
     * 
     * @type {TicketCreateDataTypeEnum}
     * @memberof TicketCreateData
     */
    type: TicketCreateDataTypeEnum;
    /**
     * 
     * @type {TicketAttributes}
     * @memberof TicketCreateData
     */
    attributes?: TicketAttributes;
    /**
     * 
     * @type {TicketRelationships}
     * @memberof TicketCreateData
     */
    relationships?: TicketRelationships;
}


/**
 * @export
 */
export const TicketCreateDataTypeEnum = {
    Tickets: 'tickets'
} as const;
export type TicketCreateDataTypeEnum = typeof TicketCreateDataTypeEnum[keyof typeof TicketCreateDataTypeEnum];


/**
 * Check if a given object implements the TicketCreateData interface.
 */
export function instanceOfTicketCreateData(value: object): value is TicketCreateData {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TicketCreateDataFromJSON(json: any): TicketCreateData {
    return TicketCreateDataFromJSONTyped(json, false);
}

export function TicketCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : TicketAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : TicketRelationshipsFromJSON(json['relationships']),
    };
}

export function TicketCreateDataToJSON(json: any): TicketCreateData {
    return TicketCreateDataToJSONTyped(json, false);
}

export function TicketCreateDataToJSONTyped(value?: TicketCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'attributes': TicketAttributesToJSON(value['attributes']),
        'relationships': TicketRelationshipsToJSON(value['relationships']),
    };
}

