/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountingSubcategoryCollection,
  AccountingSubcategoryCreate,
  AccountingSubcategoryResponse,
  AccountingSubcategoryUpdate,
  ErrorResponse,
} from '../models/index';
import {
    AccountingSubcategoryCollectionFromJSON,
    AccountingSubcategoryCollectionToJSON,
    AccountingSubcategoryCreateFromJSON,
    AccountingSubcategoryCreateToJSON,
    AccountingSubcategoryResponseFromJSON,
    AccountingSubcategoryResponseToJSON,
    AccountingSubcategoryUpdateFromJSON,
    AccountingSubcategoryUpdateToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface CreateAccountingSubcategoryRequest {
    accountingSubcategoryCreate: AccountingSubcategoryCreate;
}

export interface DeleteAccountingSubcategoryRequest {
    id: string;
}

export interface GetAccountingSubcategoriesRequest {
    filterAccountingCategoryId?: string | null;
}

export interface GetAccountingSubcategoryRequest {
    id: string;
}

export interface UpdateAccountingSubcategoryRequest {
    id: string;
    accountingSubcategoryUpdate: AccountingSubcategoryUpdate;
}

/**
 * 
 */
export class AccountingSubcategoriesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAccountingSubcategory without sending the request
     */
    async createAccountingSubcategoryRequestOpts(requestParameters: CreateAccountingSubcategoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountingSubcategoryCreate'] == null) {
            throw new runtime.RequiredError(
                'accountingSubcategoryCreate',
                'Required parameter "accountingSubcategoryCreate" was null or undefined when calling createAccountingSubcategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/accounting_subcategories`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountingSubcategoryCreateToJSON(requestParameters['accountingSubcategoryCreate']),
        };
    }

    /**
     * Create a new accounting subcategory
     */
    async createAccountingSubcategoryRaw(requestParameters: CreateAccountingSubcategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountingSubcategoryResponse>> {
        const requestOptions = await this.createAccountingSubcategoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountingSubcategoryResponseFromJSON(jsonValue));
    }

    /**
     * Create a new accounting subcategory
     */
    async createAccountingSubcategory(requestParameters: CreateAccountingSubcategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountingSubcategoryResponse> {
        const response = await this.createAccountingSubcategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAccountingSubcategory without sending the request
     */
    async deleteAccountingSubcategoryRequestOpts(requestParameters: DeleteAccountingSubcategoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAccountingSubcategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/accounting_subcategories/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an accounting subcategory
     */
    async deleteAccountingSubcategoryRaw(requestParameters: DeleteAccountingSubcategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteAccountingSubcategoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an accounting subcategory
     */
    async deleteAccountingSubcategory(requestParameters: DeleteAccountingSubcategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAccountingSubcategoryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAccountingSubcategories without sending the request
     */
    async getAccountingSubcategoriesRequestOpts(requestParameters: GetAccountingSubcategoriesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filterAccountingCategoryId'] != null) {
            queryParameters['filter[accounting_category_id]'] = requestParameters['filterAccountingCategoryId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/accounting_subcategories`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all accounting subcategories
     */
    async getAccountingSubcategoriesRaw(requestParameters: GetAccountingSubcategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountingSubcategoryCollection>> {
        const requestOptions = await this.getAccountingSubcategoriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountingSubcategoryCollectionFromJSON(jsonValue));
    }

    /**
     * Retrieve all accounting subcategories
     */
    async getAccountingSubcategories(requestParameters: GetAccountingSubcategoriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountingSubcategoryCollection> {
        const response = await this.getAccountingSubcategoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAccountingSubcategory without sending the request
     */
    async getAccountingSubcategoryRequestOpts(requestParameters: GetAccountingSubcategoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAccountingSubcategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/accounting_subcategories/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a specific accounting subcategory
     */
    async getAccountingSubcategoryRaw(requestParameters: GetAccountingSubcategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountingSubcategoryResponse>> {
        const requestOptions = await this.getAccountingSubcategoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountingSubcategoryResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific accounting subcategory
     */
    async getAccountingSubcategory(requestParameters: GetAccountingSubcategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountingSubcategoryResponse> {
        const response = await this.getAccountingSubcategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAccountingSubcategory without sending the request
     */
    async updateAccountingSubcategoryRequestOpts(requestParameters: UpdateAccountingSubcategoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAccountingSubcategory().'
            );
        }

        if (requestParameters['accountingSubcategoryUpdate'] == null) {
            throw new runtime.RequiredError(
                'accountingSubcategoryUpdate',
                'Required parameter "accountingSubcategoryUpdate" was null or undefined when calling updateAccountingSubcategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/accounting_subcategories/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AccountingSubcategoryUpdateToJSON(requestParameters['accountingSubcategoryUpdate']),
        };
    }

    /**
     * Update an accounting subcategory
     */
    async updateAccountingSubcategoryRaw(requestParameters: UpdateAccountingSubcategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountingSubcategoryResponse>> {
        const requestOptions = await this.updateAccountingSubcategoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountingSubcategoryResponseFromJSON(jsonValue));
    }

    /**
     * Update an accounting subcategory
     */
    async updateAccountingSubcategory(requestParameters: UpdateAccountingSubcategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountingSubcategoryResponse> {
        const response = await this.updateAccountingSubcategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
