/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContactCollection,
  ContactCreate,
  ContactResponse,
  ContactUpdate,
  ErrorResponse,
} from '../models/index';
import {
    ContactCollectionFromJSON,
    ContactCollectionToJSON,
    ContactCreateFromJSON,
    ContactCreateToJSON,
    ContactResponseFromJSON,
    ContactResponseToJSON,
    ContactUpdateFromJSON,
    ContactUpdateToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface CreateContactRequest {
    contactCreate: ContactCreate;
}

export interface DeleteContactRequest {
    id: string;
}

export interface GetContactRequest {
    id: string;
}

export interface GetContactsRequest {
    filterQ?: string | null;
    filterKind?: GetContactsFilterKindEnum;
    filterTaxId?: string | null;
    filterCountry?: string | null;
    filterEmail?: string | null;
    sort?: string;
    pageNumber?: number;
}

export interface UpdateContactRequest {
    id: string;
    contactUpdate: ContactUpdate;
}

/**
 * 
 */
export class ContactsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createContact without sending the request
     */
    async createContactRequestOpts(requestParameters: CreateContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactCreate'] == null) {
            throw new runtime.RequiredError(
                'contactCreate',
                'Required parameter "contactCreate" was null or undefined when calling createContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/contacts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContactCreateToJSON(requestParameters['contactCreate']),
        };
    }

    /**
     * Create a new contact
     */
    async createContactRaw(requestParameters: CreateContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactResponse>> {
        const requestOptions = await this.createContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactResponseFromJSON(jsonValue));
    }

    /**
     * Create a new contact
     */
    async createContact(requestParameters: CreateContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactResponse> {
        const response = await this.createContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteContact without sending the request
     */
    async deleteContactRequestOpts(requestParameters: DeleteContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/contacts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a contact
     */
    async deleteContactRaw(requestParameters: DeleteContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a contact
     */
    async deleteContact(requestParameters: DeleteContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteContactRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getContact without sending the request
     */
    async getContactRequestOpts(requestParameters: GetContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/contacts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a specific contact
     */
    async getContactRaw(requestParameters: GetContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactResponse>> {
        const requestOptions = await this.getContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific contact
     */
    async getContact(requestParameters: GetContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactResponse> {
        const response = await this.getContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getContacts without sending the request
     */
    async getContactsRequestOpts(requestParameters: GetContactsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filterQ'] != null) {
            queryParameters['filter[q]'] = requestParameters['filterQ'];
        }

        if (requestParameters['filterKind'] != null) {
            queryParameters['filter[kind]'] = requestParameters['filterKind'];
        }

        if (requestParameters['filterTaxId'] != null) {
            queryParameters['filter[tax_id]'] = requestParameters['filterTaxId'];
        }

        if (requestParameters['filterCountry'] != null) {
            queryParameters['filter[country]'] = requestParameters['filterCountry'];
        }

        if (requestParameters['filterEmail'] != null) {
            queryParameters['filter[email]'] = requestParameters['filterEmail'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/contacts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all contacts
     */
    async getContactsRaw(requestParameters: GetContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactCollection>> {
        const requestOptions = await this.getContactsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactCollectionFromJSON(jsonValue));
    }

    /**
     * Retrieve all contacts
     */
    async getContacts(requestParameters: GetContactsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactCollection> {
        const response = await this.getContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateContact without sending the request
     */
    async updateContactRequestOpts(requestParameters: UpdateContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateContact().'
            );
        }

        if (requestParameters['contactUpdate'] == null) {
            throw new runtime.RequiredError(
                'contactUpdate',
                'Required parameter "contactUpdate" was null or undefined when calling updateContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/contacts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ContactUpdateToJSON(requestParameters['contactUpdate']),
        };
    }

    /**
     * Update a contact
     */
    async updateContactRaw(requestParameters: UpdateContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactResponse>> {
        const requestOptions = await this.updateContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactResponseFromJSON(jsonValue));
    }

    /**
     * Update a contact
     */
    async updateContact(requestParameters: UpdateContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactResponse> {
        const response = await this.updateContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetContactsFilterKindEnum = {
    Income: 'income',
    Expenses: 'expenses',
    Employee: 'employee',
    Supplier: 'supplier',
    Client: 'client',
    Assets: 'assets'
} as const;
export type GetContactsFilterKindEnum = typeof GetContactsFilterKindEnum[keyof typeof GetContactsFilterKindEnum];
