/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GetBookEntriesFilterFieldQueryParameter,
  InvoiceCollection,
  InvoiceCreate,
  InvoiceResponse,
  InvoiceUpdate,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetBookEntriesFilterFieldQueryParameterFromJSON,
    GetBookEntriesFilterFieldQueryParameterToJSON,
    InvoiceCollectionFromJSON,
    InvoiceCollectionToJSON,
    InvoiceCreateFromJSON,
    InvoiceCreateToJSON,
    InvoiceResponseFromJSON,
    InvoiceResponseToJSON,
    InvoiceUpdateFromJSON,
    InvoiceUpdateToJSON,
} from '../models/index';

export interface CreateInvoiceRequest {
    invoiceCreate: InvoiceCreate;
}

export interface DeleteInvoiceRequest {
    id: string;
}

export interface GetInvoiceRequest {
    id: string;
    include?: GetInvoiceIncludeEnum;
}

export interface GetInvoicesRequest {
    filterKind?: GetInvoicesFilterKindEnum;
    filterQ?: string | null;
    filterPeriod?: string | null;
    filterPaymentStatus?: GetInvoicesFilterPaymentStatusEnum;
    filterContactId?: string | null;
    filterFieldQuery?: GetBookEntriesFilterFieldQueryParameter;
    sort?: string;
    pageNumber?: number;
    include?: GetInvoicesIncludeEnum;
}

export interface UpdateInvoiceRequest {
    id: string;
    invoiceUpdate: InvoiceUpdate;
}

/**
 * 
 */
export class InvoicesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createInvoice without sending the request
     */
    async createInvoiceRequestOpts(requestParameters: CreateInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['invoiceCreate'] == null) {
            throw new runtime.RequiredError(
                'invoiceCreate',
                'Required parameter "invoiceCreate" was null or undefined when calling createInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/invoices`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvoiceCreateToJSON(requestParameters['invoiceCreate']),
        };
    }

    /**
     * Create a new invoice
     */
    async createInvoiceRaw(requestParameters: CreateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceResponse>> {
        const requestOptions = await this.createInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Create a new invoice
     */
    async createInvoice(requestParameters: CreateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceResponse> {
        const response = await this.createInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteInvoice without sending the request
     */
    async deleteInvoiceRequestOpts(requestParameters: DeleteInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/invoices/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an invoice
     */
    async deleteInvoiceRaw(requestParameters: DeleteInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an invoice
     */
    async deleteInvoice(requestParameters: DeleteInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteInvoiceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getInvoice without sending the request
     */
    async getInvoiceRequestOpts(requestParameters: GetInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInvoice().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/invoices/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a specific invoice
     */
    async getInvoiceRaw(requestParameters: GetInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceResponse>> {
        const requestOptions = await this.getInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific invoice
     */
    async getInvoice(requestParameters: GetInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceResponse> {
        const response = await this.getInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInvoices without sending the request
     */
    async getInvoicesRequestOpts(requestParameters: GetInvoicesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filterKind'] != null) {
            queryParameters['filter[kind]'] = requestParameters['filterKind'];
        }

        if (requestParameters['filterQ'] != null) {
            queryParameters['filter[q]'] = requestParameters['filterQ'];
        }

        if (requestParameters['filterPeriod'] != null) {
            queryParameters['filter[period]'] = requestParameters['filterPeriod'];
        }

        if (requestParameters['filterPaymentStatus'] != null) {
            queryParameters['filter[payment_status]'] = requestParameters['filterPaymentStatus'];
        }

        if (requestParameters['filterContactId'] != null) {
            queryParameters['filter[contact_id]'] = requestParameters['filterContactId'];
        }

        if (requestParameters['filterFieldQuery'] != null) {
            queryParameters['filter[field_query]'] = requestParameters['filterFieldQuery'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/invoices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all invoices
     */
    async getInvoicesRaw(requestParameters: GetInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceCollection>> {
        const requestOptions = await this.getInvoicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceCollectionFromJSON(jsonValue));
    }

    /**
     * Retrieve all invoices
     */
    async getInvoices(requestParameters: GetInvoicesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceCollection> {
        const response = await this.getInvoicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateInvoice without sending the request
     */
    async updateInvoiceRequestOpts(requestParameters: UpdateInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateInvoice().'
            );
        }

        if (requestParameters['invoiceUpdate'] == null) {
            throw new runtime.RequiredError(
                'invoiceUpdate',
                'Required parameter "invoiceUpdate" was null or undefined when calling updateInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/invoices/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: InvoiceUpdateToJSON(requestParameters['invoiceUpdate']),
        };
    }

    /**
     * Update an invoice
     */
    async updateInvoiceRaw(requestParameters: UpdateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceResponse>> {
        const requestOptions = await this.updateInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Update an invoice
     */
    async updateInvoice(requestParameters: UpdateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceResponse> {
        const response = await this.updateInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetInvoiceIncludeEnum = {
    Items: 'items'
} as const;
export type GetInvoiceIncludeEnum = typeof GetInvoiceIncludeEnum[keyof typeof GetInvoiceIncludeEnum];
/**
 * @export
 */
export const GetInvoicesFilterKindEnum = {
    Income: 'income',
    Expenses: 'expenses',
    Employee: 'employee',
    Supplier: 'supplier',
    Client: 'client',
    Assets: 'assets'
} as const;
export type GetInvoicesFilterKindEnum = typeof GetInvoicesFilterKindEnum[keyof typeof GetInvoicesFilterKindEnum];
/**
 * @export
 */
export const GetInvoicesFilterPaymentStatusEnum = {
    Paid: 'paid',
    Unpaid: 'unpaid',
    Due: 'due',
    Pending: 'pending'
} as const;
export type GetInvoicesFilterPaymentStatusEnum = typeof GetInvoicesFilterPaymentStatusEnum[keyof typeof GetInvoicesFilterPaymentStatusEnum];
/**
 * @export
 */
export const GetInvoicesIncludeEnum = {
    Items: 'items'
} as const;
export type GetInvoicesIncludeEnum = typeof GetInvoicesIncludeEnum[keyof typeof GetInvoicesIncludeEnum];
