/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  NumberingSeriesCollection,
  NumberingSeriesCreate,
  NumberingSeriesResponse,
  NumberingSeriesUpdate,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    NumberingSeriesCollectionFromJSON,
    NumberingSeriesCollectionToJSON,
    NumberingSeriesCreateFromJSON,
    NumberingSeriesCreateToJSON,
    NumberingSeriesResponseFromJSON,
    NumberingSeriesResponseToJSON,
    NumberingSeriesUpdateFromJSON,
    NumberingSeriesUpdateToJSON,
} from '../models/index';

export interface CreateNumberingSeriesRequest {
    numberingSeriesCreate: NumberingSeriesCreate;
}

export interface DeleteNumberingSeriesRequest {
    id: string;
}

export interface GetNumberingSerieRequest {
    id: string;
}

export interface GetNumberingSeriesRequest {
    filterPrefix?: string | null;
    filterApplicableTo?: GetNumberingSeriesFilterApplicableToEnum;
    filterAmending?: boolean | null;
}

export interface UpdateNumberingSeriesRequest {
    id: string;
    numberingSeriesUpdate: NumberingSeriesUpdate;
}

/**
 * 
 */
export class NumberingSeriesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createNumberingSeries without sending the request
     */
    async createNumberingSeriesRequestOpts(requestParameters: CreateNumberingSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['numberingSeriesCreate'] == null) {
            throw new runtime.RequiredError(
                'numberingSeriesCreate',
                'Required parameter "numberingSeriesCreate" was null or undefined when calling createNumberingSeries().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/numbering_series`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NumberingSeriesCreateToJSON(requestParameters['numberingSeriesCreate']),
        };
    }

    /**
     * Create a new numbering series
     */
    async createNumberingSeriesRaw(requestParameters: CreateNumberingSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NumberingSeriesResponse>> {
        const requestOptions = await this.createNumberingSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NumberingSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Create a new numbering series
     */
    async createNumberingSeries(requestParameters: CreateNumberingSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NumberingSeriesResponse> {
        const response = await this.createNumberingSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteNumberingSeries without sending the request
     */
    async deleteNumberingSeriesRequestOpts(requestParameters: DeleteNumberingSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteNumberingSeries().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/numbering_series/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a numbering series
     */
    async deleteNumberingSeriesRaw(requestParameters: DeleteNumberingSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteNumberingSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a numbering series
     */
    async deleteNumberingSeries(requestParameters: DeleteNumberingSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteNumberingSeriesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getNumberingSerie without sending the request
     */
    async getNumberingSerieRequestOpts(requestParameters: GetNumberingSerieRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getNumberingSerie().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/numbering_series/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a specific numbering series
     */
    async getNumberingSerieRaw(requestParameters: GetNumberingSerieRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NumberingSeriesResponse>> {
        const requestOptions = await this.getNumberingSerieRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NumberingSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific numbering series
     */
    async getNumberingSerie(requestParameters: GetNumberingSerieRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NumberingSeriesResponse> {
        const response = await this.getNumberingSerieRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNumberingSeries without sending the request
     */
    async getNumberingSeriesRequestOpts(requestParameters: GetNumberingSeriesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filterPrefix'] != null) {
            queryParameters['filter[prefix]'] = requestParameters['filterPrefix'];
        }

        if (requestParameters['filterApplicableTo'] != null) {
            queryParameters['filter[applicable_to]'] = requestParameters['filterApplicableTo'];
        }

        if (requestParameters['filterAmending'] != null) {
            queryParameters['filter[amending]'] = requestParameters['filterAmending'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/numbering_series`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all numbering series
     */
    async getNumberingSeriesRaw(requestParameters: GetNumberingSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NumberingSeriesCollection>> {
        const requestOptions = await this.getNumberingSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NumberingSeriesCollectionFromJSON(jsonValue));
    }

    /**
     * Retrieve all numbering series
     */
    async getNumberingSeries(requestParameters: GetNumberingSeriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NumberingSeriesCollection> {
        const response = await this.getNumberingSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateNumberingSeries without sending the request
     */
    async updateNumberingSeriesRequestOpts(requestParameters: UpdateNumberingSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateNumberingSeries().'
            );
        }

        if (requestParameters['numberingSeriesUpdate'] == null) {
            throw new runtime.RequiredError(
                'numberingSeriesUpdate',
                'Required parameter "numberingSeriesUpdate" was null or undefined when calling updateNumberingSeries().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/numbering_series/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: NumberingSeriesUpdateToJSON(requestParameters['numberingSeriesUpdate']),
        };
    }

    /**
     * Update a numbering series
     */
    async updateNumberingSeriesRaw(requestParameters: UpdateNumberingSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NumberingSeriesResponse>> {
        const requestOptions = await this.updateNumberingSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NumberingSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Update a numbering series
     */
    async updateNumberingSeries(requestParameters: UpdateNumberingSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NumberingSeriesResponse> {
        const response = await this.updateNumberingSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetNumberingSeriesFilterApplicableToEnum = {
    Invoices: 'invoices',
    Tickets: 'tickets',
    Budgets: 'budgets'
} as const;
export type GetNumberingSeriesFilterApplicableToEnum = typeof GetNumberingSeriesFilterApplicableToEnum[keyof typeof GetNumberingSeriesFilterApplicableToEnum];
