/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GetBookEntriesFilterFieldQueryParameter,
  PaysheetCollection,
  PaysheetCreate,
  PaysheetResponse,
  PaysheetUpdate,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetBookEntriesFilterFieldQueryParameterFromJSON,
    GetBookEntriesFilterFieldQueryParameterToJSON,
    PaysheetCollectionFromJSON,
    PaysheetCollectionToJSON,
    PaysheetCreateFromJSON,
    PaysheetCreateToJSON,
    PaysheetResponseFromJSON,
    PaysheetResponseToJSON,
    PaysheetUpdateFromJSON,
    PaysheetUpdateToJSON,
} from '../models/index';

export interface CreatePaysheetRequest {
    paysheetCreate: PaysheetCreate;
}

export interface DeletePaysheetRequest {
    id: string;
}

export interface GetPaysheetRequest {
    id: string;
}

export interface GetPaysheetsRequest {
    filterQ?: string | null;
    filterPeriod?: string | null;
    filterPaymentStatus?: GetPaysheetsFilterPaymentStatusEnum;
    filterContactId?: string | null;
    filterFieldQuery?: GetBookEntriesFilterFieldQueryParameter;
    sort?: string;
    pageNumber?: number;
}

export interface UpdatePaysheetRequest {
    id: string;
    paysheetUpdate: PaysheetUpdate;
}

/**
 * 
 */
export class PaysheetsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPaysheet without sending the request
     */
    async createPaysheetRequestOpts(requestParameters: CreatePaysheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paysheetCreate'] == null) {
            throw new runtime.RequiredError(
                'paysheetCreate',
                'Required parameter "paysheetCreate" was null or undefined when calling createPaysheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/paysheets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaysheetCreateToJSON(requestParameters['paysheetCreate']),
        };
    }

    /**
     * Create a new paysheet
     */
    async createPaysheetRaw(requestParameters: CreatePaysheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaysheetResponse>> {
        const requestOptions = await this.createPaysheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaysheetResponseFromJSON(jsonValue));
    }

    /**
     * Create a new paysheet
     */
    async createPaysheet(requestParameters: CreatePaysheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaysheetResponse> {
        const response = await this.createPaysheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePaysheet without sending the request
     */
    async deletePaysheetRequestOpts(requestParameters: DeletePaysheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePaysheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/paysheets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a paysheet
     */
    async deletePaysheetRaw(requestParameters: DeletePaysheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePaysheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a paysheet
     */
    async deletePaysheet(requestParameters: DeletePaysheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePaysheetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getPaysheet without sending the request
     */
    async getPaysheetRequestOpts(requestParameters: GetPaysheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPaysheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/paysheets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a specific paysheet
     */
    async getPaysheetRaw(requestParameters: GetPaysheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaysheetResponse>> {
        const requestOptions = await this.getPaysheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaysheetResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific paysheet
     */
    async getPaysheet(requestParameters: GetPaysheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaysheetResponse> {
        const response = await this.getPaysheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPaysheets without sending the request
     */
    async getPaysheetsRequestOpts(requestParameters: GetPaysheetsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filterQ'] != null) {
            queryParameters['filter[q]'] = requestParameters['filterQ'];
        }

        if (requestParameters['filterPeriod'] != null) {
            queryParameters['filter[period]'] = requestParameters['filterPeriod'];
        }

        if (requestParameters['filterPaymentStatus'] != null) {
            queryParameters['filter[payment_status]'] = requestParameters['filterPaymentStatus'];
        }

        if (requestParameters['filterContactId'] != null) {
            queryParameters['filter[contact_id]'] = requestParameters['filterContactId'];
        }

        if (requestParameters['filterFieldQuery'] != null) {
            queryParameters['filter[field_query]'] = requestParameters['filterFieldQuery'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/paysheets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all paysheets
     */
    async getPaysheetsRaw(requestParameters: GetPaysheetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaysheetCollection>> {
        const requestOptions = await this.getPaysheetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaysheetCollectionFromJSON(jsonValue));
    }

    /**
     * Retrieve all paysheets
     */
    async getPaysheets(requestParameters: GetPaysheetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaysheetCollection> {
        const response = await this.getPaysheetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePaysheet without sending the request
     */
    async updatePaysheetRequestOpts(requestParameters: UpdatePaysheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePaysheet().'
            );
        }

        if (requestParameters['paysheetUpdate'] == null) {
            throw new runtime.RequiredError(
                'paysheetUpdate',
                'Required parameter "paysheetUpdate" was null or undefined when calling updatePaysheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/paysheets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PaysheetUpdateToJSON(requestParameters['paysheetUpdate']),
        };
    }

    /**
     * Update a paysheet
     */
    async updatePaysheetRaw(requestParameters: UpdatePaysheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaysheetResponse>> {
        const requestOptions = await this.updatePaysheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaysheetResponseFromJSON(jsonValue));
    }

    /**
     * Update a paysheet
     */
    async updatePaysheet(requestParameters: UpdatePaysheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaysheetResponse> {
        const response = await this.updatePaysheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetPaysheetsFilterPaymentStatusEnum = {
    Paid: 'paid',
    Unpaid: 'unpaid',
    Due: 'due',
    Pending: 'pending'
} as const;
export type GetPaysheetsFilterPaymentStatusEnum = typeof GetPaysheetsFilterPaymentStatusEnum[keyof typeof GetPaysheetsFilterPaymentStatusEnum];
