/* tslint:disable */
/* eslint-disable */
/**
 * Quipu API
 * Quipu is an invoice and taxes software as a service for freelances and companies.  To use our API you need to sign up in our software. You will have 15 days to try it for free. If you need more time, contact our support team to extend the trial period.  For more information about our API, libraries and other applications, visit: https://getquipu.com/en/integrations.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GetBookEntriesFilterFieldQueryParameter,
  TicketCollection,
  TicketCreate,
  TicketResponse,
  TicketUpdate,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetBookEntriesFilterFieldQueryParameterFromJSON,
    GetBookEntriesFilterFieldQueryParameterToJSON,
    TicketCollectionFromJSON,
    TicketCollectionToJSON,
    TicketCreateFromJSON,
    TicketCreateToJSON,
    TicketResponseFromJSON,
    TicketResponseToJSON,
    TicketUpdateFromJSON,
    TicketUpdateToJSON,
} from '../models/index';

export interface CreateTicketRequest {
    ticketCreate: TicketCreate;
}

export interface DeleteTicketRequest {
    id: string;
}

export interface GetTicketRequest {
    id: string;
    include?: GetTicketIncludeEnum;
}

export interface GetTicketsRequest {
    filterKind?: GetTicketsFilterKindEnum;
    filterQ?: string | null;
    filterPeriod?: string | null;
    filterPaymentStatus?: GetTicketsFilterPaymentStatusEnum;
    filterContactId?: string | null;
    filterFieldQuery?: GetBookEntriesFilterFieldQueryParameter;
    sort?: string;
    pageNumber?: number;
    include?: GetTicketsIncludeEnum;
}

export interface UpdateTicketRequest {
    id: string;
    ticketUpdate: TicketUpdate;
}

/**
 * 
 */
export class TicketsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTicket without sending the request
     */
    async createTicketRequestOpts(requestParameters: CreateTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketCreate'] == null) {
            throw new runtime.RequiredError(
                'ticketCreate',
                'Required parameter "ticketCreate" was null or undefined when calling createTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/tickets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TicketCreateToJSON(requestParameters['ticketCreate']),
        };
    }

    /**
     * Create a new ticket
     */
    async createTicketRaw(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketResponse>> {
        const requestOptions = await this.createTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketResponseFromJSON(jsonValue));
    }

    /**
     * Create a new ticket
     */
    async createTicket(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketResponse> {
        const response = await this.createTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTicket without sending the request
     */
    async deleteTicketRequestOpts(requestParameters: DeleteTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a ticket
     */
    async deleteTicketRaw(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a ticket
     */
    async deleteTicket(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTicketRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTicket without sending the request
     */
    async getTicketRequestOpts(requestParameters: GetTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTicket().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a specific ticket
     */
    async getTicketRaw(requestParameters: GetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketResponse>> {
        const requestOptions = await this.getTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific ticket
     */
    async getTicket(requestParameters: GetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketResponse> {
        const response = await this.getTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTickets without sending the request
     */
    async getTicketsRequestOpts(requestParameters: GetTicketsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filterKind'] != null) {
            queryParameters['filter[kind]'] = requestParameters['filterKind'];
        }

        if (requestParameters['filterQ'] != null) {
            queryParameters['filter[q]'] = requestParameters['filterQ'];
        }

        if (requestParameters['filterPeriod'] != null) {
            queryParameters['filter[period]'] = requestParameters['filterPeriod'];
        }

        if (requestParameters['filterPaymentStatus'] != null) {
            queryParameters['filter[payment_status]'] = requestParameters['filterPaymentStatus'];
        }

        if (requestParameters['filterContactId'] != null) {
            queryParameters['filter[contact_id]'] = requestParameters['filterContactId'];
        }

        if (requestParameters['filterFieldQuery'] != null) {
            queryParameters['filter[field_query]'] = requestParameters['filterFieldQuery'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/tickets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all tickets
     */
    async getTicketsRaw(requestParameters: GetTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketCollection>> {
        const requestOptions = await this.getTicketsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketCollectionFromJSON(jsonValue));
    }

    /**
     * Retrieve all tickets
     */
    async getTickets(requestParameters: GetTicketsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketCollection> {
        const response = await this.getTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTicket without sending the request
     */
    async updateTicketRequestOpts(requestParameters: UpdateTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTicket().'
            );
        }

        if (requestParameters['ticketUpdate'] == null) {
            throw new runtime.RequiredError(
                'ticketUpdate',
                'Required parameter "ticketUpdate" was null or undefined when calling updateTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.quipu.v1+json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }


        let urlPath = `/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TicketUpdateToJSON(requestParameters['ticketUpdate']),
        };
    }

    /**
     * Update a ticket
     */
    async updateTicketRaw(requestParameters: UpdateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketResponse>> {
        const requestOptions = await this.updateTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketResponseFromJSON(jsonValue));
    }

    /**
     * Update a ticket
     */
    async updateTicket(requestParameters: UpdateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketResponse> {
        const response = await this.updateTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetTicketIncludeEnum = {
    Items: 'items'
} as const;
export type GetTicketIncludeEnum = typeof GetTicketIncludeEnum[keyof typeof GetTicketIncludeEnum];
/**
 * @export
 */
export const GetTicketsFilterKindEnum = {
    Income: 'income',
    Expenses: 'expenses',
    Employee: 'employee',
    Supplier: 'supplier',
    Client: 'client',
    Assets: 'assets'
} as const;
export type GetTicketsFilterKindEnum = typeof GetTicketsFilterKindEnum[keyof typeof GetTicketsFilterKindEnum];
/**
 * @export
 */
export const GetTicketsFilterPaymentStatusEnum = {
    Paid: 'paid',
    Unpaid: 'unpaid',
    Due: 'due',
    Pending: 'pending'
} as const;
export type GetTicketsFilterPaymentStatusEnum = typeof GetTicketsFilterPaymentStatusEnum[keyof typeof GetTicketsFilterPaymentStatusEnum];
/**
 * @export
 */
export const GetTicketsIncludeEnum = {
    Items: 'items'
} as const;
export type GetTicketsIncludeEnum = typeof GetTicketsIncludeEnum[keyof typeof GetTicketsIncludeEnum];
